#![no_std]
#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::pedantic)]
#![allow(clippy::needless_range_loop)]
#![allow(clippy::module_name_repetitions)]
#![allow(clippy::must_use_candidate)]
// Branchless kernels use deliberate integer casts for bit-packing; these pedantic
// lints are suppressed crate-wide because the casts are structurally intentional.
// `unnecessary_cast` covers ggen-generated same-type casts used for readability in
// branchless boundary classifiers (e.g., `command_opcode_encoded`).
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_possible_wrap)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::unnecessary_cast)]
// Short single-letter names (s, i, h) are idiomatic in packed-u64 kernel ABIs.
#![allow(clippy::similar_names)]
#![allow(clippy::many_single_char_names)]
// Miscellaneous pedantic lints that don't apply to generated kernel code.
#![allow(clippy::bool_to_int_with_if)]
#![allow(clippy::decimal_bitwise_operands)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::items_after_statements)]
#![allow(clippy::match_same_arms)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::no_effect_underscore_binding)]
#![allow(clippy::struct_excessive_bools)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::assertions_on_constants)]

//! `wasm4games` — a branchless, `no_std`, engine-agnostic *game-pattern foundry*.
//!
//! Game behaviors (input admission, ticks, collision, combat, status, physics, evidence,
//! promotion) are expressed as **bounded byte-class state** transformed by **branchless
//! kernels** that reuse the verified primitives in [`bcinr_logic`]. Every meaningful
//! transition can emit **object-centric evidence** ([`evidence::ocel`]), **runtime span
//! codes** ([`evidence::otel`]), a **receipt chain** ([`evidence::receipt`]), and a
//! **deterministic replay frame** ([`evidence::replay`]).
//!
//! # Quick Start
//!
//! Call a pattern kernel directly for zero-allocation, branch-free game logic:
//!
//! ```
//! use wasm4games::patterns::damage_applied;
//!
//! // state: bits[0..16] = current HP (200)
//! // input: bits[0..16] = base damage (25), bit[16] = crit flag (0 = no crit)
//! let new_state = damage_applied(200, 25);
//! assert_eq!(new_state, 175);
//!
//! // With a crit (bit 16 set), damage is doubled.
//! let crit_state = damage_applied(200, 25 | (1 << 16));
//! assert_eq!(crit_state, 150);
//! ```
//!
//! # Pattern Kernels
//!
//! All 75 pattern kernels live in [`patterns`]. Each kernel is a pure function
//! `(state: u64, input: u64) -> u64` using a packed-u64 ABI. The complete catalog
//! is exposed via [`patterns::PATTERN_REGISTRY`] as [`ir::PatternSpec`] data, which
//! allows iteration, self-checking, and portability verification without any runtime
//! reflection.
//!
//! # Evidence Channels
//!
//! Kernels are intentionally free of side effects; evidence is emitted by the caller
//! using the four channels in [`evidence`]:
//!
//! | Module | Purpose |
//! |---|---|
//! | [`evidence::ocel`] | Object-centric event log (OCEL-style) |
//! | [`evidence::otel`] | Runtime span codes |
//! | [`evidence::receipt`] | Deterministic rolling receipt chain |
//! | [`evidence::replay`] | Deterministic replay frames |
//!
//! # No-std Usage
//!
//! The crate is `#![no_std]` by default. Enable the `alloc` feature for growable
//! structures like [`evidence::ocel::OcelLog`]. Enable the `std` feature if you need
//! the full standard library in tests or integration code.
//!
//! ## Doctrine
//!
//! - Engines project worlds; `wasm4games` operates patterns; `wasm4pm` admits evidence.
//! - Kernels are **generated by ggen** from the input surface in `ggen/`; the committed
//!   files under [`patterns`] are the offline source of truth. See the "GGEN-ONLY USER
//!   SURFACE" covenant in the docs.
//! - `wasm4pm` is *referenced, not vendored*: [`compat`] holds dependency-free mirror
//!   types shaped like `wasm4pm-compat`; the real admission bridge lives in the
//!   workspace-excluded `wasm4games-wasm4pm` crate.

#[cfg(feature = "alloc")]
extern crate alloc;
#[cfg(all(test, feature = "std"))]
extern crate std;

/// Byte-class authority: bounded `u8` state alphabets and the admission status vocabulary.
pub mod class;

/// Dependency-free mirror types that shadow `wasm4pm-compat` shapes for offline operation.
pub mod compat;

/// Golden-vector corpus — the portability oracle binding all 75 pattern kernels.
pub mod corpus;

/// Evidence channels: OCEL events, OTEL spans, receipt chains, and replay frames.
pub mod evidence;

/// Pattern IR: game patterns expressed as static data.
pub mod ir;

/// Generated branchless pattern kernels (75 patterns, ids 1–75).
///
/// All files in this module are produced by `ggen sync` from `ggen/schema/patterns.ttl`.
/// Documentation lints are suppressed here because generated constants are covered by
/// their group-level doc comments in each pattern file.
#[allow(missing_docs)]
pub mod patterns;

/// Offline admissibility proxy and determinism checks.
pub mod verify;

/// Re-export of the marker trait so downstream code uses a single `Branchless` notion.
pub use bcinr_logic::Branchless;

/// Total number of branchless pattern kernels in this crate.
///
/// Equivalent to `patterns::PATTERN_REGISTRY.len()` but available as a compile-time
/// constant for downstream assertions, C-ABI headers, and gap-detection audits.
pub const KERNEL_COUNT: usize = 75;

/// Curated re-exports for ergonomic downstream use.
///
/// Import with `use wasm4games::prelude::*;` to bring the most commonly needed types
/// into scope without spelling out the full module paths.
pub mod prelude {
    /// Byte-class and status types for branchless state management.
    pub use crate::class::{status, ByteClass, Status};

    /// Conformance mirror types for offline wasm4pm mapping.
    pub use crate::compat::{EvidenceState, Verdict};

    /// Object references and OCEL event type.
    pub use crate::evidence::ocel::{ObjectRefs, OcelEvent};

    /// OTEL span code type.
    pub use crate::evidence::otel::SpanCode;

    /// Receipt chain types for deterministic rolling evidence.
    pub use crate::evidence::receipt::{ReceiptChain, ReceiptEnvelope};

    /// Deterministic replay frame type.
    pub use crate::evidence::replay::ReplayFrame;

    /// Pattern IR types for registry iteration and cross-referencing.
    pub use crate::ir::{
        AdmissionRule, EventKind, LoweringKind, ObjectKind, PatternId, PatternSpec,
    };

    /// The static registry of all 75 pattern specs.
    pub use crate::patterns::PATTERN_REGISTRY;

    /// The `Branchless` marker trait re-exported for downstream use.
    pub use crate::Branchless;
}

#[cfg(test)]
mod chain_tests;
