
// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl + ggen/queries/ocel_schema.rq.
// Regenerate: `ggen sync`.

//! Object-centric event schema (OCEL): activity codes and the object types each activity
//! links to, mirrored from the pattern ontology. See [`crate::evidence::ocel`].
//!
//! # OCEL Schema Connection
//!
//! The Object-Centric Event Log (OCEL) model tracks *which object types* each event
//! activity involves. This module mirrors that schema as flat Rust data so that
//! admission-contract checks and replay verification can query schema membership
//! without deserializing the full ontology at runtime.
//!
//! Each [`OcelSchemaEdge`] represents one `(activity, object-type)` edge from the
//! SPARQL query `ggen/queries/ocel_schema.rq` over `ggen/schema/patterns.ttl`.
//! The edges are ordered by `(pattern_id, object_type)` for deterministic iteration.
//!
//! To check whether a given `(event_code, object_code)` pair is schema-valid:
//!
//! ```ignore
//! use wasm4games::evidence::ocel_schema::OCEL_SCHEMA;
//! let valid = OCEL_SCHEMA.iter().any(|e| e.activity == event_code && e.object_type == obj_code);
//! ```

/// One (activity, object-type) edge of the OCEL schema.
///
/// Derived from the `w4g:touchesObject` predicate in `ggen/schema/patterns.ttl`.
/// Each edge asserts that the pattern with `pattern_id` emits events of type
/// `activity` that link to objects of type `object_type`.
///
/// All fields are plain `u16` integers, so `Hash` is derived for free and lets
/// callers collect edges into `HashSet<OcelSchemaEdge>` for O(1) membership tests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OcelSchemaEdge {
    /// Pattern id the edge belongs to.
    pub pattern_id: u16,
    /// Activity (event) code.
    pub activity: u16,
    /// Object-type code linked by the activity.
    pub object_type: u16,
}

impl OcelSchemaEdge {
    /// Returns `true` if this edge matches the given activity and object-type codes.
    #[must_use]
    #[inline(always)]
    pub fn matches(&self, activity: u16, object_type: u16) -> bool {
        self.activity == activity && self.object_type == object_type
    }
}

/// The flat OCEL schema: every (activity, object-type) edge in the catalog.
///
/// Ordered by `(pattern_id, object_type)` for stable, deterministic iteration.
/// Generated from `ggen/schema/patterns.ttl` via `ggen/queries/ocel_schema.rq`.
pub static OCEL_SCHEMA: &[OcelSchemaEdge] = &[
    // input_admitted: InputAdmitted -> player
    OcelSchemaEdge {
        pattern_id: 1,
        activity: 2,
        object_type: 1,
    },
    // fixed_tick_advanced: FixedTickAdvanced -> world
    OcelSchemaEdge {
        pattern_id: 2,
        activity: 1,
        object_type: 2,
    },
    // entity_state_transitioned: EntityStateTransitioned -> entity
    OcelSchemaEdge {
        pattern_id: 3,
        activity: 16,
        object_type: 3,
    },
    // object_spawned: ObjectSpawned -> entity
    OcelSchemaEdge {
        pattern_id: 4,
        activity: 18,
        object_type: 3,
    },
    // aabb_collision_resolved: AabbCollisionResolved -> entity_a
    OcelSchemaEdge {
        pattern_id: 5,
        activity: 17,
        object_type: 4,
    },
    // aabb_collision_resolved: AabbCollisionResolved -> entity_b
    OcelSchemaEdge {
        pattern_id: 5,
        activity: 17,
        object_type: 5,
    },
    // ocel_event_linked: OcelEventLinked -> event
    OcelSchemaEdge {
        pattern_id: 6,
        activity: 33,
        object_type: 9,
    },
    // ocel_event_linked: OcelEventLinked -> object
    OcelSchemaEdge {
        pattern_id: 6,
        activity: 33,
        object_type: 10,
    },
    // otel_span_emitted: OtelSpanEmitted -> span
    OcelSchemaEdge {
        pattern_id: 7,
        activity: 34,
        object_type: 11,
    },
    // replay_frame_recorded: ReplayFrameRecorded -> frame
    OcelSchemaEdge {
        pattern_id: 8,
        activity: 35,
        object_type: 12,
    },
    // receipt_appended: ReceiptAppended -> receipt_chain
    OcelSchemaEdge {
        pattern_id: 9,
        activity: 32,
        object_type: 8,
    },
    // physics_value_rendered: PhysicsValueRendered -> quantity
    OcelSchemaEdge {
        pattern_id: 10,
        activity: 48,
        object_type: 13,
    },
    // semantic_lod_selected: SemanticLodSelected -> hud_widget
    OcelSchemaEdge {
        pattern_id: 11,
        activity: 49,
        object_type: 14,
    },
    // projectile_advanced: ProjectileAdvanced -> projectile
    OcelSchemaEdge {
        pattern_id: 12,
        activity: 50,
        object_type: 15,
    },
    // ai_action_selected: AiActionSelected -> agent
    OcelSchemaEdge {
        pattern_id: 13,
        activity: 64,
        object_type: 19,
    },
    // damage_applied: DamageApplied -> attacker
    OcelSchemaEdge {
        pattern_id: 14,
        activity: 66,
        object_type: 6,
    },
    // damage_applied: DamageApplied -> target
    OcelSchemaEdge {
        pattern_id: 14,
        activity: 66,
        object_type: 7,
    },
    // status_effect_ticked: StatusEffectTicked -> target
    OcelSchemaEdge {
        pattern_id: 15,
        activity: 67,
        object_type: 7,
    },
    // inventory_item_changed: InventoryItemChanged -> player
    OcelSchemaEdge {
        pattern_id: 16,
        activity: 68,
        object_type: 1,
    },
    // inventory_item_changed: InventoryItemChanged -> item
    OcelSchemaEdge {
        pattern_id: 16,
        activity: 68,
        object_type: 20,
    },
    // quest_step_advanced: QuestStepAdvanced -> player
    OcelSchemaEdge {
        pattern_id: 17,
        activity: 69,
        object_type: 1,
    },
    // quest_step_advanced: QuestStepAdvanced -> quest
    OcelSchemaEdge {
        pattern_id: 17,
        activity: 69,
        object_type: 21,
    },
    // mastery_moment_detected: MasteryMomentDetected -> player
    OcelSchemaEdge {
        pattern_id: 18,
        activity: 80,
        object_type: 1,
    },
    // mastery_moment_detected: MasteryMomentDetected -> session
    OcelSchemaEdge {
        pattern_id: 18,
        activity: 80,
        object_type: 16,
    },
    // share_artifact_generated: ShareArtifactGenerated -> player
    OcelSchemaEdge {
        pattern_id: 19,
        activity: 81,
        object_type: 1,
    },
    // share_artifact_generated: ShareArtifactGenerated -> artifact
    OcelSchemaEdge {
        pattern_id: 19,
        activity: 81,
        object_type: 17,
    },
    // nps_prompt_gated: NpsPromptGated -> player
    OcelSchemaEdge {
        pattern_id: 20,
        activity: 82,
        object_type: 1,
    },
    // nps_prompt_gated: NpsPromptGated -> prompt
    OcelSchemaEdge {
        pattern_id: 20,
        activity: 82,
        object_type: 18,
    },
    // path_node_expanded: PathNodeExpanded -> nav_node
    OcelSchemaEdge {
        pattern_id: 21,
        activity: 83,
        object_type: 22,
    },
    // waypoint_reached: WaypointReached -> player
    OcelSchemaEdge {
        pattern_id: 22,
        activity: 84,
        object_type: 1,
    },
    // waypoint_reached: WaypointReached -> nav_node
    OcelSchemaEdge {
        pattern_id: 22,
        activity: 84,
        object_type: 22,
    },
    // heuristic_distance_estimated: HeuristicDistanceEstimated -> nav_node
    OcelSchemaEdge {
        pattern_id: 23,
        activity: 85,
        object_type: 22,
    },
    // path_cost_bounded: PathCostBounded -> nav_node
    OcelSchemaEdge {
        pattern_id: 24,
        activity: 86,
        object_type: 22,
    },
    // nav_state_advanced: NavStateAdvanced -> player
    OcelSchemaEdge {
        pattern_id: 25,
        activity: 87,
        object_type: 1,
    },
    // nav_state_advanced: NavStateAdvanced -> nav_node
    OcelSchemaEdge {
        pattern_id: 25,
        activity: 87,
        object_type: 22,
    },
    // noise_value_sampled: NoiseValueSampled -> world
    OcelSchemaEdge {
        pattern_id: 26,
        activity: 88,
        object_type: 2,
    },
    // tile_variant_selected: TileVariantSelected -> tile
    OcelSchemaEdge {
        pattern_id: 27,
        activity: 89,
        object_type: 23,
    },
    // terrain_height_quantized: TerrainHeightQuantized -> terrain
    OcelSchemaEdge {
        pattern_id: 28,
        activity: 90,
        object_type: 24,
    },
    // spawn_weight_evaluated: SpawnWeightEvaluated -> entity
    OcelSchemaEdge {
        pattern_id: 29,
        activity: 91,
        object_type: 3,
    },
    // biome_class_selected: BiomeClassSelected -> terrain
    OcelSchemaEdge {
        pattern_id: 30,
        activity: 92,
        object_type: 24,
    },
    // currency_delta_applied: CurrencyDeltaApplied -> player
    OcelSchemaEdge {
        pattern_id: 31,
        activity: 93,
        object_type: 1,
    },
    // xp_threshold_crossed: XpThresholdCrossed -> player
    OcelSchemaEdge {
        pattern_id: 32,
        activity: 94,
        object_type: 1,
    },
    // level_gate_evaluated: LevelGateEvaluated -> player
    OcelSchemaEdge {
        pattern_id: 33,
        activity: 95,
        object_type: 1,
    },
    // purchase_admitted: PurchaseAdmitted -> player
    OcelSchemaEdge {
        pattern_id: 34,
        activity: 96,
        object_type: 1,
    },
    // purchase_admitted: PurchaseAdmitted -> item
    OcelSchemaEdge {
        pattern_id: 34,
        activity: 96,
        object_type: 20,
    },
    // reward_tier_selected: RewardTierSelected -> player
    OcelSchemaEdge {
        pattern_id: 35,
        activity: 97,
        object_type: 1,
    },
    // dialogue_node_advanced: DialogueNodeAdvanced -> player
    OcelSchemaEdge {
        pattern_id: 36,
        activity: 98,
        object_type: 1,
    },
    // dialogue_node_advanced: DialogueNodeAdvanced -> npc
    OcelSchemaEdge {
        pattern_id: 36,
        activity: 98,
        object_type: 25,
    },
    // condition_flag_evaluated: ConditionFlagEvaluated -> player
    OcelSchemaEdge {
        pattern_id: 37,
        activity: 99,
        object_type: 1,
    },
    // narrative_branch_selected: NarrativeBranchSelected -> npc
    OcelSchemaEdge {
        pattern_id: 38,
        activity: 100,
        object_type: 25,
    },
    // dialogue_cooldown_bounded: DialogueCooldownBounded -> player
    OcelSchemaEdge {
        pattern_id: 39,
        activity: 101,
        object_type: 1,
    },
    // dialogue_cooldown_bounded: DialogueCooldownBounded -> npc
    OcelSchemaEdge {
        pattern_id: 39,
        activity: 101,
        object_type: 25,
    },
    // choice_weight_selected: ChoiceWeightSelected -> player
    OcelSchemaEdge {
        pattern_id: 40,
        activity: 102,
        object_type: 1,
    },
    // camera_distance_clamped: CameraDistanceClamped -> camera
    OcelSchemaEdge {
        pattern_id: 41,
        activity: 103,
        object_type: 26,
    },
    // look_target_weighted: LookTargetWeighted -> target
    OcelSchemaEdge {
        pattern_id: 42,
        activity: 104,
        object_type: 7,
    },
    // look_target_weighted: LookTargetWeighted -> camera
    OcelSchemaEdge {
        pattern_id: 42,
        activity: 104,
        object_type: 26,
    },
    // fov_adjusted: FovAdjusted -> camera
    OcelSchemaEdge {
        pattern_id: 43,
        activity: 105,
        object_type: 26,
    },
    // camera_shake_applied: CameraShakeApplied -> camera
    OcelSchemaEdge {
        pattern_id: 44,
        activity: 106,
        object_type: 26,
    },
    // camera_follow_lerped: CameraFollowLerped -> player
    OcelSchemaEdge {
        pattern_id: 45,
        activity: 107,
        object_type: 1,
    },
    // camera_follow_lerped: CameraFollowLerped -> camera
    OcelSchemaEdge {
        pattern_id: 45,
        activity: 107,
        object_type: 26,
    },
    // audio_priority_selected: AudioPrioritySelected -> audio_source
    OcelSchemaEdge {
        pattern_id: 46,
        activity: 108,
        object_type: 27,
    },
    // volume_clamped: VolumeClamped -> audio_source
    OcelSchemaEdge {
        pattern_id: 47,
        activity: 109,
        object_type: 27,
    },
    // audio_fade_applied: AudioFadeApplied -> audio_source
    OcelSchemaEdge {
        pattern_id: 48,
        activity: 110,
        object_type: 27,
    },
    // audio_trigger_evaluated: AudioTriggerEvaluated -> entity
    OcelSchemaEdge {
        pattern_id: 49,
        activity: 111,
        object_type: 3,
    },
    // audio_trigger_evaluated: AudioTriggerEvaluated -> audio_source
    OcelSchemaEdge {
        pattern_id: 49,
        activity: 111,
        object_type: 27,
    },
    // audio_distance_attenuated: AudioDistanceAttenuated -> player
    OcelSchemaEdge {
        pattern_id: 50,
        activity: 112,
        object_type: 1,
    },
    // audio_distance_attenuated: AudioDistanceAttenuated -> audio_source
    OcelSchemaEdge {
        pattern_id: 50,
        activity: 112,
        object_type: 27,
    },
    // tick_delta_bounded: TickDeltaBounded -> peer
    OcelSchemaEdge {
        pattern_id: 51,
        activity: 113,
        object_type: 28,
    },
    // lag_compensation_applied: LagCompensationApplied -> player
    OcelSchemaEdge {
        pattern_id: 52,
        activity: 114,
        object_type: 1,
    },
    // lag_compensation_applied: LagCompensationApplied -> peer
    OcelSchemaEdge {
        pattern_id: 52,
        activity: 114,
        object_type: 28,
    },
    // packet_priority_evaluated: PacketPriorityEvaluated -> peer
    OcelSchemaEdge {
        pattern_id: 53,
        activity: 115,
        object_type: 28,
    },
    // prediction_error_bounded: PredictionErrorBounded -> player
    OcelSchemaEdge {
        pattern_id: 54,
        activity: 116,
        object_type: 1,
    },
    // prediction_error_bounded: PredictionErrorBounded -> peer
    OcelSchemaEdge {
        pattern_id: 54,
        activity: 116,
        object_type: 28,
    },
    // sync_state_admitted: SyncStateAdmitted -> session
    OcelSchemaEdge {
        pattern_id: 55,
        activity: 117,
        object_type: 16,
    },
    // sync_state_admitted: SyncStateAdmitted -> peer
    OcelSchemaEdge {
        pattern_id: 55,
        activity: 117,
        object_type: 28,
    },
    // sigma_level_computed: SigmaLevelComputed -> quality_metric
    OcelSchemaEdge {
        pattern_id: 56,
        activity: 118,
        object_type: 29,
    },
    // defect_rate_quantized: DefectRateQuantized -> quality_metric
    OcelSchemaEdge {
        pattern_id: 57,
        activity: 119,
        object_type: 29,
    },
    // ctq_threshold_evaluated: CtqThresholdEvaluated -> quality_metric
    OcelSchemaEdge {
        pattern_id: 58,
        activity: 120,
        object_type: 29,
    },
    // nps_score_bounded: NpsScoreBounded -> player
    OcelSchemaEdge {
        pattern_id: 59,
        activity: 121,
        object_type: 1,
    },
    // nps_score_bounded: NpsScoreBounded -> prompt
    OcelSchemaEdge {
        pattern_id: 59,
        activity: 121,
        object_type: 18,
    },
    // quality_gate_evaluated: QualityGateEvaluated -> quality_metric
    OcelSchemaEdge {
        pattern_id: 60,
        activity: 122,
        object_type: 29,
    },
    // command_opcode_encoded: CommandOpcodeEncoded -> engine_cmd
    OcelSchemaEdge {
        pattern_id: 61,
        activity: 123,
        object_type: 30,
    },
    // capability_flag_evaluated: CapabilityFlagEvaluated -> player
    OcelSchemaEdge {
        pattern_id: 62,
        activity: 124,
        object_type: 1,
    },
    // capability_flag_evaluated: CapabilityFlagEvaluated -> engine_cmd
    OcelSchemaEdge {
        pattern_id: 62,
        activity: 124,
        object_type: 30,
    },
    // bridge_state_transitioned: BridgeStateTransitioned -> engine_cmd
    OcelSchemaEdge {
        pattern_id: 63,
        activity: 125,
        object_type: 30,
    },
    // payload_size_bounded: PayloadSizeBounded -> engine_cmd
    OcelSchemaEdge {
        pattern_id: 64,
        activity: 126,
        object_type: 30,
    },
    // adapter_priority_ranked: AdapterPriorityRanked -> engine_cmd
    OcelSchemaEdge {
        pattern_id: 65,
        activity: 127,
        object_type: 30,
    },
    // reward_signal_clamped: RewardSignalClamped -> agent
    OcelSchemaEdge {
        pattern_id: 66,
        activity: 128,
        object_type: 19,
    },
    // policy_action_selected: PolicyActionSelected -> agent
    OcelSchemaEdge {
        pattern_id: 67,
        activity: 129,
        object_type: 19,
    },
    // observation_class_selected: ObservationClassSelected -> agent
    OcelSchemaEdge {
        pattern_id: 68,
        activity: 130,
        object_type: 19,
    },
    // action_mask_applied: ActionMaskApplied -> agent
    OcelSchemaEdge {
        pattern_id: 69,
        activity: 131,
        object_type: 19,
    },
    // action_mask_applied: ActionMaskApplied -> episode
    OcelSchemaEdge {
        pattern_id: 69,
        activity: 131,
        object_type: 31,
    },
    // episode_return_bounded: EpisodeReturnBounded -> agent
    OcelSchemaEdge {
        pattern_id: 70,
        activity: 132,
        object_type: 19,
    },
    // episode_return_bounded: EpisodeReturnBounded -> episode
    OcelSchemaEdge {
        pattern_id: 70,
        activity: 132,
        object_type: 31,
    },
    // movement_legality_checked: MovementLegalityChecked -> player
    OcelSchemaEdge {
        pattern_id: 71,
        activity: 133,
        object_type: 1,
    },
    // resource_bound_checked: ResourceBoundChecked -> player
    OcelSchemaEdge {
        pattern_id: 72,
        activity: 134,
        object_type: 1,
    },
    // cooldown_legality_checked: CooldownLegalityChecked -> player
    OcelSchemaEdge {
        pattern_id: 73,
        activity: 135,
        object_type: 1,
    },
    // action_rate_bounded: ActionRateBounded -> player
    OcelSchemaEdge {
        pattern_id: 74,
        activity: 136,
        object_type: 1,
    },
    // transition_legality_checked: TransitionLegalityChecked -> entity
    OcelSchemaEdge {
        pattern_id: 75,
        activity: 137,
        object_type: 3,
    },
];