// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (action_mask_applied)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: ActionMaskApplied
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Apply an action mask to a policy output — zero out Q-values for illegal actions.
//! Tests bit at action_index in the valid-actions bitset; branchlessly selects Q-value
//! or zero using the legality flag.

use bcinr_logic::mask::select_u64;

/// ActionMaskApplied kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = valid_actions bitset (up to 32 actions).
/// - `input`: bits[0..8] = action_index (0..31); bits[8..24] = proposed Q-value (u16).
///
/// Returns: bits[0..16] = masked Q-value (Q-value if legal, 0 if illegal);
///          bits[16..24] = is_legal flag (1 if legal, 0 otherwise).
#[inline]
#[must_use]
pub fn action_mask_applied(state: u64, input: u64) -> u64 {
    let valid = state & 0xFFFF_FFFF;
    let idx = input & 0x1F; // ABI: action_index is 0..31; mask to 5 bits to keep shift safe
    let q_val = (input >> 8) & 0xFFFF;
    let legal_bit = (valid >> idx) & 1;
    let legal_mask = 0u64.wrapping_sub(legal_bit);
    let masked_q = select_u64(legal_mask, q_val, 0);
    masked_q | (legal_bit << 16)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn action_mask_applied_reference(state: u64, input: u64) -> u64 {
        let valid = state & 0xFFFF_FFFF;
        let idx = input & 0x1F; // ABI: action_index is 0..31
        let q_val = (input >> 8) & 0xFFFF;
        let legal = (valid >> idx) & 1;
        (q_val * legal) | (legal << 16)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !action_mask_applied_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        action_mask_applied_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(action_mask_applied_reference(s, i), action_mask_applied(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = action_mask_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = action_mask_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // valid=0b1010, idx=1, q=50 -> legal=1, masked_q=50
        let out = action_mask_applied(0b1010, 1 | (50 << 8));
        assert_eq!(out & 0xFFFF, 50);
        assert_eq!((out >> 16) & 0xFF, 1);
        // valid=0b1010, idx=0, q=50 -> legal=0, masked_q=0
        let out2 = action_mask_applied(0b1010, 50 << 8);
        assert_eq!(out2 & 0xFFFF, 0);
        assert_eq!((out2 >> 16) & 0xFF, 0);
        // valid=0xFFFF, idx=15, q=100 -> legal=1, masked_q=100
        let out3 = action_mask_applied(0xFFFF, 15 | (100 << 8));
        assert_eq!(out3 & 0xFFFF, 100);
        assert_eq!((out3 >> 16) & 0xFF, 1);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: legal actions, so the Q-value passes through unmasked.
        &[(0b1010, 1 | (50 << 8)), (0xFFFF, 15 | (100 << 8))]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Illegal action (bit clear) and an out-of-range index (masked to 5 bits) that is illegal:
        // both must force the Q-value to zero.
        &[(0b1010, 50 << 8), (0b0010, 32 | (50 << 8))]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: drops the legality mask, leaking the Q-value for illegal actions.
        let valid = s & 0xFFFF_FFFF;
        let idx = i & 0x1F;
        let q_val = (i >> 8) & 0xFFFF;
        let legal_bit = (valid >> idx) & 1;
        q_val | (legal_bit << 16)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                action_mask_applied(s, i),
                action_mask_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                action_mask_applied(s, i),
                action_mask_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != action_mask_applied_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_action_mask_applied(c: &mut Criterion) {
        c.bench_function("action_mask_applied", |b| {
            b.iter(|| {
                black_box(action_mask_applied(
                    black_box(0b1010),
                    black_box(1 | (50 << 8)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: Q-value is zeroed iff action_index bit is clear in valid_actions.
// Hoare-logic Verification Line 2: is_legal flag equals the single extracted bit, with no branch.
