// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (action_rate_bounded)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: ActionRateBounded
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Authority: legality spec — the number of actions issued in a single tick is admissible
//! iff it does not exceed the per-tick budget; exceeding the budget is an action-spam
//! (macro) cheat and is refused. Lowered onto [`bcinr_logic::mask::lt_mask_u32`].

use bcinr_logic::mask::lt_mask_u32;

/// ActionRateBounded kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = actions issued this tick.
/// - `input`: bits[0..16] = per-tick action budget.
///
/// Returns a verdict bitmask: `0` = ADMITTED (legal), nonzero = refusal.
/// - bit0 = rate_over_budget (`actions > budget`).
#[inline]
#[must_use]
pub fn action_rate_bounded(state: u64, input: u64) -> u64 {
    let actions = (state & 0xFFFF) as u32;
    let budget = (input & 0xFFFF) as u32;
    u64::from(lt_mask_u32(budget, actions)) & 1
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn action_rate_bounded_reference(state: u64, input: u64) -> u64 {
        let actions = (state & 0xFFFF) as u32;
        let budget = (input & 0xFFFF) as u32;
        if actions > budget {
            1
        } else {
            0
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !action_rate_bounded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        action_rate_bounded_reference(s, i) ^ 0xFFFF
    }

    // --- Two-sided breed battery: legality corpus + weakened detector ---
    fn must_admit() -> &'static [(u64, u64)] {
        // (actions_this_tick, tick_budget)
        &[
            (0, 8), // idle tick
            (8, 8), // exactly at the budget
            (3, 8), // comfortably under budget
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (9, 8),    // one over the budget
            (1000, 8), // burst spam
            (1, 0),    // any action against a zero budget
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Deliberately broken: uses `<` (strict) instead of `>`, so action counts at or
        // above the budget are admitted — spam slips through.
        let actions = (s & 0xFFFF) as u32;
        let budget = (i & 0xFFFF) as u32;
        if actions < budget {
            1
        } else {
            0
        }
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                action_rate_bounded_reference(s, i),
                action_rate_bounded(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = action_rate_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = action_rate_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            action_rate_bounded(0, 0),
            action_rate_bounded_reference(0, 0)
        );
        assert_eq!(
            action_rate_bounded(0xFFFF, 0xFFFF),
            action_rate_bounded_reference(0xFFFF, 0xFFFF)
        );
        // Actions equal to budget is legal; one above is over-budget.
        assert_eq!(action_rate_bounded(8, 8), 0);
        assert_eq!(action_rate_bounded(9, 8), 1);
    }

    #[test]
    fn two_sided_admit() {
        for &(s, i) in must_admit() {
            assert_eq!(action_rate_bounded(s, i), 0, "legal case must be admitted");
        }
    }
    #[test]
    fn two_sided_refuse() {
        for &(s, i) in must_refuse() {
            assert_ne!(action_rate_bounded(s, i), 0, "cheat case must be refused");
        }
    }
    #[test]
    fn weakened_fails_corpus() {
        assert!(
            must_refuse().iter().any(|&(s, i)| weakened(s, i) == 0),
            "a weakened detector must admit >=1 cheat from the corpus"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_action_rate_bounded(c: &mut Criterion) {
        c.bench_function("action_rate_bounded", |b| {
            b.iter(|| black_box(action_rate_bounded(black_box(8), black_box(8))))
        });
    }
}

// Hoare-logic Verification Line 1: verdict bit0 is set iff actions strictly exceed the tick budget.
// Hoare-logic Verification Line 2: an action count equal to the budget is admitted (boundary inclusive).
