// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (adapter_priority_ranked)
// Regenerate: `ggen sync`. Lowering: Network.

//! Pattern: AdapterPriorityRanked
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Rank 4 adapter priorities using a branchless bitonic sort network via
//! [`bcinr_logic::network::bitonic_sort_8u32`] on 8 slots (4 real + 4 zero pads).
//! Returns priorities sorted descending so the highest-priority adapter is in bits[0..16].

use bcinr_logic::network::bitonic_sort_8u32;

/// AdapterPriorityRanked kernel. Packed-u64 ABI:
/// - `state`: bits[0..16]=p0, bits[16..32]=p1, bits[32..48]=p2, bits[48..64]=p3.
/// - `input`: unused.
///
/// Returns: bits[0..16] = highest priority; bits[16..32] = second;
///          bits[32..48] = third; bits[48..64] = fourth (sorted descending).
#[inline]
#[must_use]
pub fn adapter_priority_ranked(state: u64, input: u64) -> u64 {
    let _ = input;
    let p0 = (state & 0xFFFF) as u32;
    let p1 = ((state >> 16) & 0xFFFF) as u32;
    let p2 = ((state >> 32) & 0xFFFF) as u32;
    let p3 = ((state >> 48) & 0xFFFF) as u32;
    // Pad to 8 slots with zeros; bitonic_sort_8u32 sorts ascending.
    // Zeros sort to indices [0..4], real values to [4..8] (ascending).
    let mut arr = [p0, p1, p2, p3, 0, 0, 0, 0];
    bitonic_sort_8u32(&mut arr);
    // arr[7] = max, arr[6] = second, arr[5] = third, arr[4] = fourth (lowest of the 4).
    let hi = arr[7] as u64;
    let s2 = arr[6] as u64;
    let s3 = arr[5] as u64;
    let lo = arr[4] as u64;
    hi | (s2 << 16) | (s3 << 32) | (lo << 48)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn adapter_priority_ranked_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let p0 = (state & 0xFFFF) as u32;
        let p1 = ((state >> 16) & 0xFFFF) as u32;
        let p2 = ((state >> 32) & 0xFFFF) as u32;
        let p3 = ((state >> 48) & 0xFFFF) as u32;
        let mut ps = [p0, p1, p2, p3];
        ps.sort_unstable_by(|a, b| b.cmp(a)); // descending
        (ps[0] as u64) | ((ps[1] as u64) << 16) | ((ps[2] as u64) << 32) | ((ps[3] as u64) << 48)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !adapter_priority_ranked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        adapter_priority_ranked_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(adapter_priority_ranked_reference(s, i), adapter_priority_ranked(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = adapter_priority_ranked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = adapter_priority_ranked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // [5,9,3,1] -> sorted descending [9,5,3,1].
        let s = 5u64 | (9u64 << 16) | (3u64 << 32) | (1u64 << 48);
        let out = adapter_priority_ranked(s, 0);
        assert_eq!(out & 0xFFFF, 9);
        assert_eq!((out >> 16) & 0xFFFF, 5);
        assert_eq!((out >> 32) & 0xFFFF, 3);
        assert_eq!((out >> 48) & 0xFFFF, 1);
        // [10,10,10,10] -> all equal, descending [10,10,10,10].
        let s2 = 10u64 | (10u64 << 16) | (10u64 << 32) | (10u64 << 48);
        let out2 = adapter_priority_ranked(s2, 0);
        assert_eq!(out2 & 0xFFFF, 10);
        assert_eq!((out2 >> 48) & 0xFFFF, 10);
        // [0,0,0,255] -> sorted descending [255,0,0,0].
        let s3 = 255u64 << 48;
        let out3 = adapter_priority_ranked(s3, 0);
        assert_eq!(out3 & 0xFFFF, 255);
        assert_eq!((out3 >> 16) & 0xFFFF, 0);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: inputs already sorted descending, or all-equal (sort is a no-op).
        &[
            (9u64 | (5u64 << 16) | (3u64 << 32) | (1u64 << 48), 0),
            (10u64 | (10u64 << 16) | (10u64 << 32) | (10u64 << 48), 0),
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-order: the network must reorder these into descending priority.
        &[
            (5u64 | (9u64 << 16) | (3u64 << 32) | (1u64 << 48), 0),
            (255u64 << 48, 0),
        ]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: skips the sort, returning the priorities in their original order.
        let p0 = s & 0xFFFF;
        let p1 = (s >> 16) & 0xFFFF;
        let p2 = (s >> 32) & 0xFFFF;
        let p3 = (s >> 48) & 0xFFFF;
        p0 | (p1 << 16) | (p2 << 32) | (p3 << 48)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                adapter_priority_ranked(s, i),
                adapter_priority_ranked_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                adapter_priority_ranked(s, i),
                adapter_priority_ranked_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != adapter_priority_ranked_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 5u64 | (9u64 << 16) | (3u64 << 32) | (1u64 << 48);
    const I: u64 = 0;
    pub fn bench_adapter_priority_ranked(c: &mut Criterion) {
        c.bench_function("adapter_priority_ranked", |b| {
            b.iter(|| black_box(adapter_priority_ranked(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: bitonic_sort_8u32 produces a fully sorted ascending sequence; slots [4..8] hold the 4 real priorities in ascending order.
// Hoare-logic Verification Line 2: zero-padding in slots [4..7] of the input ensures real values are never displaced below index 4 when all priorities are non-zero.
