// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (ai_action_selected)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: AiActionSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select an AI action by utility argmax over four candidate scores. The running best score
//! and index are updated with branchless [`bcinr_logic::mask::max_u32`] /
//! [`bcinr_logic::mask::select_u32`] (first index wins ties).

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// AiActionSelected kernel. Packed-u64 ABI:
/// - `state`: unused (reserved for an agent id).
/// - `input`: four u16 utility scores in lanes 0..4 (actions 0..3).
///
/// Returns: bits[0..8] = chosen action index, bits[8..24] = its utility score.
#[inline]
#[must_use]
pub fn ai_action_selected(state: u64, input: u64) -> u64 {
    let _ = state;
    let u0 = (input & 0xFFFF) as u32;
    let u1 = ((input >> 16) & 0xFFFF) as u32;
    let u2 = ((input >> 32) & 0xFFFF) as u32;
    let u3 = ((input >> 48) & 0xFFFF) as u32;

    let mut best_val = u0;
    let mut best_idx = 0u32;

    // Candidate i wins when best_val < u_i (strictly), keeping the first max on ties.
    let m1 = lt_mask_u32(best_val, u1);
    best_idx = select_u32(m1, 1, best_idx);
    best_val = select_u32(m1, u1, best_val);

    let m2 = lt_mask_u32(best_val, u2);
    best_idx = select_u32(m2, 2, best_idx);
    best_val = select_u32(m2, u2, best_val);

    let m3 = lt_mask_u32(best_val, u3);
    best_idx = select_u32(m3, 3, best_idx);
    best_val = select_u32(m3, u3, best_val);

    (best_idx as u64) | ((best_val as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn ai_action_selected_reference(_state: u64, input: u64) -> u64 {
        let u = [
            (input & 0xFFFF) as u32,
            ((input >> 16) & 0xFFFF) as u32,
            ((input >> 32) & 0xFFFF) as u32,
            ((input >> 48) & 0xFFFF) as u32,
        ];
        let mut best_val = u[0];
        let mut best_idx = 0u32;
        for (i, &v) in u.iter().enumerate().skip(1) {
            if v > best_val {
                best_val = v;
                best_idx = i as u32;
            }
        }
        (best_idx as u64) | ((best_val as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !ai_action_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        ai_action_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(ai_action_selected_reference(s, i), ai_action_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = ai_action_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = ai_action_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // utilities [5, 9, 3, 9] -> first max is index 1.
        let input = 5u64 | (9u64 << 16) | (3u64 << 32) | (9u64 << 48);
        let out = ai_action_selected(0, input);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFFFF, 9);
        // all-zero utilities -> index 0.
        assert_eq!(ai_action_selected(0, 0) & 0xFF, 0);
    }

    // Two-sided breed-rigor battery.
    // Legal: a single, unambiguous maximum (no tie to break).
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (0, 5 | (9 << 16) | (3 << 32) | (2 << 48)),
            (0, 1 | (2 << 16) | (4 << 32) | (8 << 48)),
        ]
    }
    // Extreme: tied maxima where the kernel must deterministically keep the first index.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (0, 9 | (9 << 16) | (3 << 32) | (9 << 48)),
            (0, 5 | (9 << 16) | (3 << 32) | (9 << 48)),
        ]
    }
    // Weakened: uses `>=` (last-wins) instead of strict `>`, so ties resolve to the wrong index.
    fn weakened(s: u64, i: u64) -> u64 {
        let _ = s;
        let u = [
            (i & 0xFFFF) as u32,
            ((i >> 16) & 0xFFFF) as u32,
            ((i >> 32) & 0xFFFF) as u32,
            ((i >> 48) & 0xFFFF) as u32,
        ];
        let mut best_val = u[0];
        let mut best_idx = 0u32;
        for (idx, &v) in u.iter().enumerate().skip(1) {
            if v >= best_val {
                best_val = v;
                best_idx = idx as u32;
            }
        }
        (best_idx as u64) | ((best_val as u64) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(ai_action_selected(s, i), ai_action_selected_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(ai_action_selected(s, i), ai_action_selected_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != ai_action_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_ai_action_selected(c: &mut Criterion) {
        let input = 5u64 | (9u64 << 16) | (3u64 << 32) | (9u64 << 48);
        c.bench_function("ai_action_selected", |b| {
            b.iter(|| black_box(ai_action_selected(black_box(0), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: the chosen score equals the max of all candidates.
// Hoare-logic Verification Line 2: ties resolve to the lowest-index action (strict <).
