// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (audio_distance_attenuated)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: AudioDistanceAttenuated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Compute attenuated volume based on distance. Volume = max(0, max_vol - distance * attenuation_factor). Clamp to [0, max_vol].

use bcinr_logic::fix::clamp_u32;

/// AudioDistanceAttenuated kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = max_volume (0..255), bits[8..16] = attenuation_factor (volume per distance unit).
/// - `input`: bits[0..16] = distance (u16).
///
/// Returns bits[0..8] = attenuated volume.
#[inline]
#[must_use]
pub fn audio_distance_attenuated(state: u64, input: u64) -> u64 {
    let max_vol = (state & 0xFF) as u32;
    let atten = ((state >> 8) & 0xFF) as u32;
    let dist = (input & 0xFFFF) as u32;
    let reduction = atten.saturating_mul(dist);
    let vol = max_vol.saturating_sub(reduction);
    (clamp_u32(vol, 0, max_vol) as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn audio_distance_attenuated_reference(state: u64, input: u64) -> u64 {
        let max_vol = (state & 0xFF) as u32;
        let atten = ((state >> 8) & 0xFF) as u32;
        let dist = (input & 0xFFFF) as u32;
        max_vol
            .saturating_sub(atten.saturating_mul(dist))
            .min(max_vol) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !audio_distance_attenuated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        audio_distance_attenuated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(audio_distance_attenuated_reference(s, i), audio_distance_attenuated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_distance_attenuated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_distance_attenuated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // max=200/atten=2/dist=10 -> 180
        assert_eq!(
            audio_distance_attenuated(200 | (2 << 8), 10),
            audio_distance_attenuated_reference(200 | (2 << 8), 10)
        );
        // max=200/atten=2/dist=200 -> 0
        assert_eq!(
            audio_distance_attenuated(200 | (2 << 8), 200),
            audio_distance_attenuated_reference(200 | (2 << 8), 200)
        );
        // max=100/atten=0/dist=999 -> 100
        assert_eq!(
            audio_distance_attenuated(100, 999),
            audio_distance_attenuated_reference(100, 999)
        );
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: reduction < max_vol, the [0, max_vol] floor does not fire.
        &[
            (200 | (2 << 8), 10), // 200 - 20 -> 180
            (100, 999),           // atten=0 -> 100 unchanged
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: reduction >= max_vol, the floor clamps the volume to 0.
        &[
            (200 | (2 << 8), 200),   // 200 - 400 -> 0
            (50 | (255 << 8), 1000), // huge reduction -> 0
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the saturating-sub floor and clamp; underflow wraps.
        let max_vol = (s & 0xFF) as u32;
        let atten = ((s >> 8) & 0xFF) as u32;
        let dist = (i & 0xFFFF) as u32;
        let reduction = atten.saturating_mul(dist);
        (max_vol.wrapping_sub(reduction) as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                audio_distance_attenuated(s, i),
                audio_distance_attenuated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                audio_distance_attenuated(s, i),
                audio_distance_attenuated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != audio_distance_attenuated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 200 | (2 << 8);
    const I: u64 = 10;
    pub fn bench_audio_distance_attenuated(c: &mut Criterion) {
        c.bench_function("audio_distance_attenuated", |b| {
            b.iter(|| black_box(audio_distance_attenuated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: saturating_mul prevents overflow of atten * dist for any u32 inputs before subtraction.
// Hoare-logic Verification Line 2: saturating_sub floors the result at 0; clamp_u32 then caps at max_vol, guaranteeing result in [0, max_vol].
