// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (audio_priority_selected)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: AudioPrioritySelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select the higher-priority of two competing audio channels. Higher priority wins; tie goes to channel 0.

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// AudioPrioritySelected kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = channel_0 priority, bits[8..16] = channel_0 id.
/// - `input`: bits[0..8] = channel_1 priority, bits[8..16] = channel_1 id.
///
/// Returns bits[0..8] = selected channel id; bits[8..16] = winning priority.
#[inline]
#[must_use]
pub fn audio_priority_selected(state: u64, input: u64) -> u64 {
    let p0 = (state & 0xFF) as u32;
    let id0 = ((state >> 8) & 0xFF) as u32;
    let p1 = (input & 0xFF) as u32;
    let id1 = ((input >> 8) & 0xFF) as u32;
    // ch1 wins only when strictly greater
    let ch1_wins = lt_mask_u32(p0, p1);
    let sel_id = select_u32(ch1_wins, id1, id0);
    let sel_p = select_u32(ch1_wins, p1, p0);
    (sel_id as u64) | ((sel_p as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn audio_priority_selected_reference(state: u64, input: u64) -> u64 {
        let p0 = (state & 0xFF) as u32;
        let id0 = ((state >> 8) & 0xFF) as u32;
        let p1 = (input & 0xFF) as u32;
        let id1 = ((input >> 8) & 0xFF) as u32;
        if p1 > p0 {
            (id1 as u64) | ((p1 as u64) << 8)
        } else {
            (id0 as u64) | ((p0 as u64) << 8)
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !audio_priority_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        audio_priority_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(audio_priority_selected_reference(s, i), audio_priority_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_priority_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_priority_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // p0=5/p1=3 -> id0 wins (state: p0=5,id0=1; input: p1=3,id1=2)
        assert_eq!(
            audio_priority_selected(5 | (1 << 8), 3 | (2 << 8)),
            audio_priority_selected_reference(5 | (1 << 8), 3 | (2 << 8))
        );
        // p0=3/p1=5 -> id1 wins
        assert_eq!(
            audio_priority_selected(3 | (1 << 8), 5 | (2 << 8)),
            audio_priority_selected_reference(3 | (1 << 8), 5 | (2 << 8))
        );
        // p0=5/p1=5 -> tie goes to id0
        assert_eq!(
            audio_priority_selected(5 | (1 << 8), 5 | (2 << 8)),
            audio_priority_selected_reference(5 | (1 << 8), 5 | (2 << 8))
        );
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // Channel 0 already wins (>=): the selector keeps channel 0.
        &[
            (5 | (1 << 8), 3 | (2 << 8)), // p0=5 > p1=3 -> ch0
            (5 | (1 << 8), 5 | (2 << 8)), // tie -> ch0
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Channel 1 strictly higher: the selector must switch away from channel 0.
        &[
            (3 | (1 << 8), 5 | (2 << 8)), // p1=5 > p0=3 -> ch1
            (7 << 8, 255 | (9 << 8)),     // p0=0, p1=255 dominates -> ch1
        ]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: always keeps channel 0, omitting the priority selection.
        let p0 = (s & 0xFF) as u32;
        let id0 = ((s >> 8) & 0xFF) as u32;
        (id0 as u64) | ((p0 as u64) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                audio_priority_selected(s, i),
                audio_priority_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                audio_priority_selected(s, i),
                audio_priority_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != audio_priority_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 5 | (1 << 8);
    const I: u64 = 3 | (2 << 8);
    pub fn bench_audio_priority_selected(c: &mut Criterion) {
        c.bench_function("audio_priority_selected", |b| {
            b.iter(|| black_box(audio_priority_selected(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: ch1_wins is all-ones iff p1 > p0, all-zeros otherwise (strict inequality, tie to channel 0).
// Hoare-logic Verification Line 2: select_u32 on ch1_wins produces the winning id and priority with no conditional branches.
