// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (audio_fade_applied)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: AudioFadeApplied
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Apply a fade step — reduce volume by fade_rate per tick, floor at 0. Return new volume and a silent flag.

use bcinr_logic::int::saturating_sub_i64;
use bcinr_logic::mask::eq_mask_u32;

/// AudioFadeApplied kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current volume (0..255).
/// - `input`: bits[0..8] = fade_rate per tick.
///
/// Returns bits[0..8] = new volume; bits[8..16] = 1 if now silent (volume==0).
#[inline]
#[must_use]
pub fn audio_fade_applied(state: u64, input: u64) -> u64 {
    let vol = (state & 0xFF) as i64;
    let rate = (input & 0xFF) as i64;
    let new_vol = saturating_sub_i64(vol, rate).max(0);
    let silent = (eq_mask_u32(new_vol as u32, 0) >> 31) as u64;
    (new_vol as u64 & 0xFF) | (silent << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn audio_fade_applied_reference(state: u64, input: u64) -> u64 {
        let vol = (state & 0xFF) as i64;
        let rate = (input & 0xFF) as i64;
        let nv = (vol - rate).max(0);
        (nv as u64) | (((nv == 0) as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !audio_fade_applied_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        audio_fade_applied_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(audio_fade_applied_reference(s, i), audio_fade_applied(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_fade_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_fade_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // vol=100/rate=20 -> 80, silent=0
        assert_eq!(
            audio_fade_applied(100, 20),
            audio_fade_applied_reference(100, 20)
        );
        // vol=10/rate=20 -> 0, silent=1
        assert_eq!(
            audio_fade_applied(10, 20),
            audio_fade_applied_reference(10, 20)
        );
        // vol=0/rate=5 -> 0, silent=1
        assert_eq!(audio_fade_applied(0, 5), audio_fade_applied_reference(0, 5));
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: rate < vol, result stays positive, floor does not fire.
        &[
            (100, 20), // 80, not silent
            (255, 1),  // 254, not silent
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: rate >= vol, the floor clamps to 0 and silent flag fires.
        &[
            (10, 20), // -> 0, silent
            (0, 5),   // -> 0, silent
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the .max(0) floor; underflow leaks into the low byte.
        let vol = (s & 0xFF) as i64;
        let rate = (i & 0xFF) as i64;
        let new_vol = vol - rate;
        let silent = ((new_vol == 0) as u64) << 8;
        ((new_vol as u64) & 0xFF) | silent
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(audio_fade_applied(s, i), audio_fade_applied_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(audio_fade_applied(s, i), audio_fade_applied_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != audio_fade_applied_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 100;
    const I: u64 = 20;
    pub fn bench_audio_fade_applied(c: &mut Criterion) {
        c.bench_function("audio_fade_applied", |b| {
            b.iter(|| black_box(audio_fade_applied(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: saturating_sub_i64 followed by max(0) floors the result at zero without conditional branches.
// Hoare-logic Verification Line 2: eq_mask_u32 >> 31 branchlessly extracts the silent flag (1 iff new_vol == 0).
