// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (audio_trigger_evaluated)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: AudioTriggerEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance an audio playback FSM. States: STOPPED=0, PLAYING=1, PAUSED=2, FADING=3.
//! Symbols: PLAY=0, STOP=1, PAUSE=2, RESUME=3, FADE=4.

use bcinr_logic::dfa::dfa_advance;

// Transition table: 4 states × 5 symbols = 20 entries (row-major: state * 5 + symbol).
// STOPPED: PLAY->PLAYING(1), STOP->STOPPED(0), PAUSE->STOPPED(0), RESUME->STOPPED(0), FADE->STOPPED(0)
// PLAYING: PLAY->PLAYING(1), STOP->STOPPED(0), PAUSE->PAUSED(2),  RESUME->PLAYING(1), FADE->FADING(3)
// PAUSED:  PLAY->PLAYING(1), STOP->STOPPED(0), PAUSE->PAUSED(2),  RESUME->PLAYING(1), FADE->FADING(3)
// FADING:  PLAY->PLAYING(1), STOP->STOPPED(0), PAUSE->PAUSED(2),  RESUME->PLAYING(1), FADE->FADING(3)
const TABLE: [usize; 20] = [
    1, 0, 0, 0, 0, // STOPPED
    1, 0, 2, 1, 3, // PLAYING
    1, 0, 2, 1, 3, // PAUSED
    1, 0, 2, 1, 3, // FADING
];
const ALPHABET_SIZE: usize = 5;
const NUM_STATES: usize = 4;

/// AudioTriggerEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current playback state (0..3).
/// - `input`: bits[0..8] = trigger symbol (0..4).
///
/// Returns bits[0..8] = next playback state.
#[inline]
#[must_use]
pub fn audio_trigger_evaluated(state: u64, input: u64) -> u64 {
    let state_idx = (state & 0xFF) as usize % NUM_STATES;
    let sym_idx = (input & 0xFF) as u8 % (ALPHABET_SIZE as u8);
    dfa_advance(state_idx, sym_idx, &TABLE, ALPHABET_SIZE) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn audio_trigger_evaluated_reference(state: u64, input: u64) -> u64 {
        let s = (state & 0xFF) as usize % 4;
        let sym = (input & 0xFF) as usize % 5;
        // STOPPED=0, PLAYING=1, PAUSED=2, FADING=3
        // PLAY=0, STOP=1, PAUSE=2, RESUME=3, FADE=4
        let next = match (s, sym) {
            (0, 0) => 1, // STOPPED + PLAY -> PLAYING
            (0, _) => 0, // STOPPED + anything else -> STOPPED
            (_, 0) => 1, // * + PLAY -> PLAYING
            (_, 1) => 0, // * + STOP -> STOPPED
            (_, 2) => 2, // * + PAUSE -> PAUSED
            (_, 3) => 1, // * + RESUME -> PLAYING
            (_, 4) => 3, // * + FADE -> FADING
            _ => 0,
        };
        next as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !audio_trigger_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        audio_trigger_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(audio_trigger_evaluated_reference(s, i), audio_trigger_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_trigger_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = audio_trigger_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // STOPPED(0) + PLAY(0) -> PLAYING(1)
        assert_eq!(audio_trigger_evaluated(0, 0), 1);
        // PLAYING(1) + PAUSE(2) -> PAUSED(2)
        assert_eq!(audio_trigger_evaluated(1, 2), 2);
        // PAUSED(2) + RESUME(3) -> PLAYING(1)
        assert_eq!(audio_trigger_evaluated(2, 3), 1);
    }

    // Two-sided breed-rigor battery. The bound here is index reduction (state % 4,
    // symbol % 5) keeping table access in range; admit = already-in-range indices,
    // refuse = out-of-range state ids that wrap onto the distinct STOPPED row.
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (0, 0), // STOPPED + PLAY -> PLAYING(1)
            (1, 2), // PLAYING + PAUSE -> PAUSED(2)
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-range state ids: modulo maps them back onto row 0 (STOPPED).
        &[
            (4, 2), // 4 % 4 = 0 (STOPPED) + PAUSE -> STOPPED(0)
            (8, 4), // 8 % 4 = 0 (STOPPED) + FADE  -> STOPPED(0)
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: clamps the state index instead of reducing it modulo NUM_STATES,
        // so out-of-range ids land on the last row rather than wrapping to STOPPED.
        let state_idx = ((s & 0xFF) as usize).min(NUM_STATES - 1);
        let sym_idx = (i & 0xFF) as u8 % (ALPHABET_SIZE as u8);
        dfa_advance(state_idx, sym_idx, &TABLE, ALPHABET_SIZE) as u64
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                audio_trigger_evaluated(s, i),
                audio_trigger_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                audio_trigger_evaluated(s, i),
                audio_trigger_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != audio_trigger_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 1; // PLAYING
    const I: u64 = 2; // PAUSE
    pub fn bench_audio_trigger_evaluated(c: &mut Criterion) {
        c.bench_function("audio_trigger_evaluated", |b| {
            b.iter(|| black_box(audio_trigger_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: TABLE encodes all 20 transitions (4 states x 5 symbols) as a flat array; dfa_advance performs a branchless table lookup with bounds-safe index masking.
// Hoare-logic Verification Line 2: state_idx and sym_idx are clamped via modulo before table access, ensuring no out-of-bounds access for arbitrary u64 inputs.
