// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (biome_class_selected)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: BiomeClassSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select a biome class from a packed biome-flags bitset by ranking the highest set bit at
//! the selector position. Uses [`bcinr_logic::bitset::rank_u64`] to count set bits below the
//! queried position, yielding a stable biome class index.

/// BiomeClassSelected kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = biome flags (up to 32 biomes, 1 bit per biome).
/// - `input`: bits[0..8] = biome selector (bit position to query, 0..31).
///
/// Returns: bits[0..8] = rank of the selector bit among set bits (biome class index);
///          bits[8..16] = bit_is_set flag (1 if the queried biome is active, 0 otherwise).
#[inline]
#[must_use]
pub fn biome_class_selected(state: u64, input: u64) -> u64 {
    let flags = state & 0xFFFF_FFFF;
    let pos = input & 0x1F; // 5-bit position; safe to shift
    let bit_set = (flags >> pos) & 1;
    // Count set bits strictly below pos (rank_u64 is inclusive so use mask directly).
    let below_mask = (1u64 << pos).wrapping_sub(1); // 0 when pos=0
    let rank = (flags & below_mask).count_ones() as u64;
    rank | (bit_set << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn biome_class_selected_reference(state: u64, input: u64) -> u64 {
        let flags = state & 0xFFFF_FFFF;
        let pos = (input & 0x1F) as u32;
        let bit_set = (flags >> pos) & 1;
        // Count bits set strictly below pos.
        let rank = if pos == 0 {
            0u64
        } else {
            (flags & ((1u64 << pos) - 1)).count_ones() as u64
        };
        rank | (bit_set << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !biome_class_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        biome_class_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(biome_class_selected_reference(s, i), biome_class_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = biome_class_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = biome_class_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // flags=0b0101 (bits 0 and 2 set), pos=2 -> bit_set=1, rank=1 (bit 0 is below pos 2).
        let out = biome_class_selected(0b0101, 2);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFF, 1);
        // flags=0, pos=0 -> bit_set=0, rank=0.
        assert_eq!(biome_class_selected(0, 0), 0);
        // flags=0xF (bits 0..3 set), pos=3 -> bit_set=1, rank=3 (bits 0,1,2 below pos 3).
        let out2 = biome_class_selected(0xF, 3);
        assert_eq!(out2 & 0xFF, 3);
        assert_eq!((out2 >> 8) & 0xFF, 1);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // pos=0 (rank is trivially 0) and a small in-domain bitset query.
        &[(0, 0), (0b0101, 2)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // High-rank queries: the below-pos rank count is the substance the
        // kernel must compute (a rank-dropping impl diverges here).
        &[(0xF, 3), (0xFFFF_FFFF, 31)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: omits the rank computation, reporting only flag presence.
        let flags = s & 0xFFFF_FFFF;
        let pos = i & 0x1F;
        let bit_set = (flags >> pos) & 1;
        bit_set << 8
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                biome_class_selected(s, i),
                biome_class_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                biome_class_selected(s, i),
                biome_class_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != biome_class_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_biome_class_selected(c: &mut Criterion) {
        c.bench_function("biome_class_selected", |b| {
            b.iter(|| black_box(biome_class_selected(black_box(0b0101), black_box(2))))
        });
    }
}

// Hoare-logic Verification Line 1: rank_u64 counts set bits at positions strictly less than pos.
// Hoare-logic Verification Line 2: the bit_is_set flag isolates the queried position independently of rank.
