// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (bridge_state_transitioned)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: BridgeStateTransitioned
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a platform bridge adapter FSM one transition using
//! [`bcinr_logic::dfa::dfa_advance`] over a flat 5×5 transition table.
//! States: DISCONNECTED=0, CONNECTING=1, CONNECTED=2, ERROR=3, RECOVERING=4.
//! Symbols: CONNECT=0, ACK=1, DISCONNECT=2, ERROR_EVT=3, RETRY=4.

use bcinr_logic::dfa::dfa_advance;

const ALPHABET: usize = 5;

/// Flat transition table [state * ALPHABET + symbol] = next_state.
///
/// ```text
///               CONNECT  ACK  DISCONNECT  ERROR_EVT  RETRY
/// DISCONNECTED:       1    0           0          3      1
/// CONNECTING:         1    2           0          3      1
/// CONNECTED:          2    2           0          3      2
/// ERROR:              3    3           0          3      4
/// RECOVERING:         4    2           0          3      4
/// ```
#[rustfmt::skip]
const TABLE: [usize; 25] = [
    // DISCONNECTED
    1, 0, 0, 3, 1,
    // CONNECTING
    1, 2, 0, 3, 1,
    // CONNECTED
    2, 2, 0, 3, 2,
    // ERROR
    3, 3, 0, 3, 4,
    // RECOVERING
    4, 2, 0, 3, 4,
];

/// BridgeStateTransitioned kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current bridge state (0..4; clamped branchlessly).
/// - `input`: bits[0..8] = event symbol (0..4; clamped branchlessly).
///
/// Returns: bits[0..8] = next bridge state.
#[inline]
#[must_use]
pub fn bridge_state_transitioned(state: u64, input: u64) -> u64 {
    let st = (state as usize) % ALPHABET; // branchless clamp into [0, 5)
    let sym = ((input & 0xFF) as usize) % ALPHABET; // branchless clamp into [0, 5)
    let next = dfa_advance(st, sym as u8, &TABLE, ALPHABET);
    (next as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn bridge_state_transitioned_reference(state: u64, input: u64) -> u64 {
        let st = (state as usize) % ALPHABET;
        let sym = ((input & 0xFF) as usize) % ALPHABET;
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !bridge_state_transitioned_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        bridge_state_transitioned_reference(s, i) ^ 0xFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(bridge_state_transitioned_reference(s, i), bridge_state_transitioned(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = bridge_state_transitioned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = bridge_state_transitioned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // DISCONNECTED(0) + CONNECT(0) -> CONNECTING(1).
        assert_eq!(bridge_state_transitioned(0, 0), 1);
        // CONNECTING(1) + ACK(1) -> CONNECTED(2).
        assert_eq!(bridge_state_transitioned(1, 1), 2);
        // ERROR(3) + RETRY(4) -> RECOVERING(4).
        assert_eq!(bridge_state_transitioned(3, 4), 4);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: state and symbol both within [0, ALPHABET).
        &[(0, 0), (1, 1), (3, 4)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: state/symbol beyond the alphabet; kernel reduces them mod ALPHABET.
        &[(7, 0), (10, 1)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: saturating-clamps the index instead of reducing modulo ALPHABET.
        let st = (s as usize).min(ALPHABET - 1);
        let sym = ((i & 0xFF) as usize).min(ALPHABET - 1);
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                bridge_state_transitioned(s, i),
                bridge_state_transitioned_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                bridge_state_transitioned(s, i),
                bridge_state_transitioned_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != bridge_state_transitioned_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 1; // CONNECTING
    const I: u64 = 1; // ACK
    pub fn bench_bridge_state_transitioned(c: &mut Criterion) {
        c.bench_function("bridge_state_transitioned", |b| {
            b.iter(|| black_box(bridge_state_transitioned(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: state and symbol are clamped via modulo into valid table bounds before the lookup.
// Hoare-logic Verification Line 2: the flat table encodes all 25 transitions deterministically; dfa_advance performs a single branchless index read.
