// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (camera_distance_clamped)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: CameraDistanceClamped
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp camera distance to [min_dist, max_dist] using [`bcinr_logic::fix::clamp_u32`],
//! producing a bounded 16-bit distance value.

use bcinr_logic::fix::clamp_u32;

/// CameraDistanceClamped kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current distance (u16, fixed-point).
/// - `input`: bits[0..16] = min_dist, bits[16..32] = max_dist.
///
/// Returns: bits[0..16] = clamped distance in [min_dist, max_dist].
#[inline]
#[must_use]
pub fn camera_distance_clamped(state: u64, input: u64) -> u64 {
    let dist = (state & 0xFFFF) as u32;
    let min_d = (input & 0xFFFF) as u32;
    let max_d = ((input >> 16) & 0xFFFF) as u32;
    clamp_u32(dist, min_d, max_d) as u64 & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn camera_distance_clamped_reference(state: u64, input: u64) -> u64 {
        let dist = (state & 0xFFFF) as u32;
        let min_d = (input & 0xFFFF) as u32;
        let max_d = ((input >> 16) & 0xFFFF) as u32;
        dist.clamp(min_d, max_d) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !camera_distance_clamped_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        camera_distance_clamped_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(
            dist in 0u64..=0xFFFF,
            min_d in 0u64..=0xFFFF,
            max_d in 0u64..=0xFFFF,
        ) {
            let input = min_d | (max_d << 16);
            if min_d <= max_d {
                prop_assert_eq!(
                    camera_distance_clamped_reference(dist, input),
                    camera_distance_clamped(dist, input)
                );
            }
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let min_d = (i & 0xFFFF) as u32;
            let max_d = ((i >> 16) & 0xFFFF) as u32;
            prop_assume!(min_d <= max_d);
            let r = camera_distance_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let min_d = (i & 0xFFFF) as u32;
            let max_d = ((i >> 16) & 0xFFFF) as u32;
            prop_assume!(min_d <= max_d);
            let r = camera_distance_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // dist=5, min=10, max=20 -> clamped to 10 (below floor).
        assert_eq!(camera_distance_clamped(5, 10 | (20 << 16)), 10);
        // dist=15, min=10, max=20 -> unchanged at 15.
        assert_eq!(camera_distance_clamped(15, 10 | (20 << 16)), 15);
        // dist=25, min=10, max=20 -> clamped to 20 (above ceiling).
        assert_eq!(camera_distance_clamped(25, 10 | (20 << 16)), 20);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // In-range distance (min <= max): clamp is a no-op.
        &[(15, 10 | (20 << 16)), (10, 10 | (20 << 16))]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-range distance (min <= max): floor and ceiling must fire.
        &[(5, 10 | (20 << 16)), (25, 10 | (20 << 16))]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: returns the raw distance, omitting the [min, max] clamp.
        let _ = i;
        s & 0xFFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                camera_distance_clamped(s, i),
                camera_distance_clamped_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                camera_distance_clamped(s, i),
                camera_distance_clamped_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != camera_distance_clamped_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_camera_distance_clamped(c: &mut Criterion) {
        c.bench_function("camera_distance_clamped", |b| {
            b.iter(|| {
                black_box(camera_distance_clamped(
                    black_box(15),
                    black_box(10 | (20 << 16)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: clamp_u32 guarantees result ∈ [min_dist, max_dist] for min_dist <= max_dist.
// Hoare-logic Verification Line 2: masking by 0xFFFF constrains the result to a valid u16 range.
