// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (camera_shake_applied)
// Regenerate: `ggen sync`. Lowering: Receipt.

//! Pattern: CameraShakeApplied
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Deterministic camera shake offset computed from a receipt hash of (frame_tick, intensity, seed).
//! Returns x,y offset in [-max_amp, max_amp] packed as two u8 values (interpret as i8) in u16.

use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;

/// CameraShakeApplied kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = frame tick, bits[16..32] = seed.
/// - `input`: bits[0..8] = max_amplitude (u8), bits[8..16] = intensity (u8, 0..255).
///
/// Returns: bits[0..8] = x offset as u8 (interpret as i8), bits[8..16] = y offset as u8
/// (interpret as i8). Offsets are in [-max_amp, max_amp].
#[inline]
#[must_use]
pub fn camera_shake_applied(state: u64, input: u64) -> u64 {
    let tick = state & 0xFFFF;
    let seed = (state >> 16) & 0xFFFF;
    let max_amp = input & 0xFF;
    let intensity = (input >> 8) & 0xFF;
    let mut r = DeterministicSubstrateReceipt::new();
    r.record(tick, seed, intensity);
    let hash = r.finalize();
    // scale hash bytes to [-max_amp, max_amp] range via modulo max_amp*2+1, then offset
    let range = max_amp * 2 + 1;
    let x_raw = (hash & 0xFF) % range.max(1);
    let y_raw = ((hash >> 8) & 0xFF) % range.max(1);
    // shift to [-max_amp, max_amp]: x = x_raw - max_amp (as i8, stored as u8)
    let x = (x_raw.wrapping_sub(max_amp)) as u8 as u64;
    let y = (y_raw.wrapping_sub(max_amp)) as u8 as u64;
    (x & 0xFF) | ((y & 0xFF) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn camera_shake_applied_reference(state: u64, input: u64) -> u64 {
        let tick = state & 0xFFFF;
        let seed = (state >> 16) & 0xFFFF;
        let max_amp = input & 0xFF;
        let intensity = (input >> 8) & 0xFF;
        let mut r = DeterministicSubstrateReceipt::new();
        r.record(tick, seed, intensity);
        let hash = r.finalize();
        let range = max_amp * 2 + 1;
        let x_raw = (hash & 0xFF) % range.max(1);
        let y_raw = ((hash >> 8) & 0xFF) % range.max(1);
        let x = (x_raw.wrapping_sub(max_amp)) as u8 as u64;
        let y = (y_raw.wrapping_sub(max_amp)) as u8 as u64;
        (x & 0xFF) | ((y & 0xFF) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !camera_shake_applied_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        camera_shake_applied_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(camera_shake_applied_reference(s, i), camera_shake_applied(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = camera_shake_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = camera_shake_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Determinism: (tick=0, seed=0, max_amp=0, intensity=0) -> deterministic zero offset.
        let out0 = camera_shake_applied(0, 0);
        assert_eq!(out0, camera_shake_applied_reference(0, 0));
        // Sensitivity: different tick -> potentially different output (at least reference matches).
        let s1 = 0u64; // tick=0, seed=0
        let s2 = 1u64; // tick=1, seed=0
        let inp = 10u64 | (128u64 << 8); // max_amp=10, intensity=128
        assert_eq!(
            camera_shake_applied(s1, inp),
            camera_shake_applied_reference(s1, inp)
        );
        assert_ne!(camera_shake_applied(s1, inp), camera_shake_applied(s2, inp));
        // Idempotency: same inputs twice -> same output.
        assert_eq!(camera_shake_applied(s2, inp), camera_shake_applied(s2, inp));
    }

    // Two-sided breed-rigor battery. The bound is `% (2*max_amp+1)`, mapping the hash
    // bytes into [-max_amp, max_amp]. admit: max_amp=128 -> range 257 > 255, so the
    // modulo is the identity on every byte (in-domain, bound is a no-op). refuse:
    // max_amp=0 -> range 1, so the modulo collapses every byte to 0 (bound fires hard).
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (0, 128),              // tick=0, max_amp=128 (range 257, no reduction)
            (42 | (7 << 16), 128), // tick=42, seed=7, max_amp=128
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // max_amp=0 forces every offset to 0; raw (un-reduced) hash bytes are nonzero.
        &[
            (0, 0), // hash low byte 0xf5, high 0x13 -> must be reduced to 0
            (1, 0), // hash low byte 0x4a -> must be reduced to 0
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the `% range` reduction; raw hash bytes leak through.
        let max_amp = i & 0xFF;
        let intensity = (i >> 8) & 0xFF;
        let mut r = DeterministicSubstrateReceipt::new();
        r.record(s & 0xFFFF, (s >> 16) & 0xFFFF, intensity);
        let hash = r.finalize();
        let x = ((hash & 0xFF).wrapping_sub(max_amp)) as u8 as u64;
        let y = (((hash >> 8) & 0xFF).wrapping_sub(max_amp)) as u8 as u64;
        (x & 0xFF) | ((y & 0xFF) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                camera_shake_applied(s, i),
                camera_shake_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                camera_shake_applied(s, i),
                camera_shake_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != camera_shake_applied_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_camera_shake_applied(c: &mut Criterion) {
        let s = 42u64 | (7u64 << 16); // tick=42, seed=7
        let i = 10u64 | (128u64 << 8); // max_amp=10, intensity=128
        c.bench_function("camera_shake_applied", |b| {
            b.iter(|| black_box(camera_shake_applied(black_box(s), black_box(i))))
        });
    }
}

// Hoare-logic Verification Line 1: DeterministicSubstrateReceipt yields a pure function of (tick, seed, intensity).
// Hoare-logic Verification Line 2: modulo range + wrapping_sub maps hash bytes to [-max_amp, max_amp] without branches.
