// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (capability_flag_evaluated)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: CapabilityFlagEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Test whether a given capability bit is set in a 64-bit capability flags word, and return
//! its rank (count of set bits at positions 0..=idx) using [`bcinr_logic::bitset::rank_u64`].
//! Useful for branchless capability gating in engine bridge adapters.

use bcinr_logic::bitset::rank_u64;

/// CapabilityFlagEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..64] = capability flags word (u64).
/// - `input`: bits[0..8] = capability index to test (0..63).
///
/// Returns: bits[0..8] = 1 if capability is set, 0 otherwise;
///          bits[8..16] = rank (count of set bits at positions 0..=idx, saturated to 8 bits).
#[inline]
#[must_use]
pub fn capability_flag_evaluated(state: u64, input: u64) -> u64 {
    let flags = state;
    let idx = (input & 0x3F) as u32;
    let bit_set = (flags >> idx) & 1;
    let rank = (rank_u64(flags, idx as usize) as u64) & 0xFF;
    bit_set | (rank << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use bcinr_logic::bitset::rank_u64;
    use proptest::prelude::*;

    fn capability_flag_evaluated_reference(state: u64, input: u64) -> u64 {
        let flags = state;
        let idx = (input & 0x3F) as u32;
        let b = (flags >> idx) & 1;
        // rank_u64 counts set bits at positions 0..=idx (inclusive); mask lower 8 bits.
        let r = (rank_u64(flags, idx as usize) as u64) & 0xFF;
        b | (r << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !capability_flag_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        capability_flag_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(capability_flag_evaluated_reference(s, i), capability_flag_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = capability_flag_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = capability_flag_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // flags=0b1100 (bits 2 and 3 set), idx=2 -> bit=1;
        // rank_u64(0b1100, 2) = count_ones(0b1100 & ((1<<3)-1)) = count_ones(0b0100) = 1.
        let out = capability_flag_evaluated(0b1100, 2);
        assert_eq!(out & 0xFF, 1); // bit 2 is set
        assert_eq!(
            (out >> 8) & 0xFF,
            capability_flag_evaluated_reference(0b1100, 2) >> 8 & 0xFF
        );
        // flags=0b1100, idx=0 -> bit=0; rank_u64(0b1100,0)=count_ones(0b1100 & 0b1)=0.
        let out2 = capability_flag_evaluated(0b1100, 0);
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFF, 0);
        // flags=u64::MAX, idx=63 -> bit=1; rank_u64(u64::MAX,63)=64 -> masked to 0x40=64 & 0xFF=64.
        let out3 = capability_flag_evaluated(u64::MAX, 63);
        assert_eq!(out3 & 0xFF, 1);
        assert_eq!(
            (out3 >> 8) & 0xFF,
            capability_flag_evaluated_reference(u64::MAX, 63) >> 8 & 0xFF
        );
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: query bit clear, so inclusive and exclusive rank coincide.
        &[(0b1100, 0), (0b1100, 1)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Query bit set: inclusive rank counts it, exclusive rank does not — they diverge.
        &[(0b1100, 2), (u64::MAX, 63)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: uses EXCLUSIVE rank (positions 0..idx) instead of inclusive (0..=idx).
        let flags = s;
        let idx = (i & 0x3F) as u32;
        let b = (flags >> idx) & 1;
        let r = (flags & ((1u64 << idx) - 1)).count_ones() as u64 & 0xFF;
        b | (r << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                capability_flag_evaluated(s, i),
                capability_flag_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                capability_flag_evaluated(s, i),
                capability_flag_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != capability_flag_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 0b1100;
    const I: u64 = 2;
    pub fn bench_capability_flag_evaluated(c: &mut Criterion) {
        c.bench_function("capability_flag_evaluated", |b| {
            b.iter(|| black_box(capability_flag_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: rank_u64 counts set bits at positions 0..=idx via a branchless prefix mask (inclusive of idx).
// Hoare-logic Verification Line 2: idx is clamped to 0..63 via bitmask before shift, and rank is truncated to 8 bits.
