// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (choice_weight_selected)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: ChoiceWeightSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select a dialogue choice by bucketing a roll against 3 cumulative weight boundaries.
//! Given a random roll (0..255) and three boundaries b0, b1, b2, returns the chosen option
//! (0 if roll < b0, 1 if b0 <= roll < b1, 2 if b1 <= roll < b2, 3 if roll >= b2).
//! Uses branchless [`bcinr_logic::mask::lt_mask_u32`] + [`bcinr_logic::mask::select_u32`].

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// ChoiceWeightSelected kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = roll (0..255).
/// - `input`: bits[0..8] = b0, bits[8..16] = b1, bits[16..24] = b2 — three bucket boundaries.
///
/// Returns: bits[0..8] = choice index (0 if roll < b0, 1 if b0<=roll<b1, 2 if b1<=roll<b2, 3 if roll>=b2).
#[inline]
#[must_use]
pub fn choice_weight_selected(state: u64, input: u64) -> u64 {
    let roll = (state & 0xFF) as u32;
    let b0 = (input & 0xFF) as u32;
    let b1 = ((input >> 8) & 0xFF) as u32;
    let b2 = ((input >> 16) & 0xFF) as u32;

    // Start with bucket 3 (roll >= b2), then override downward via branchless select.
    // m_lt_b2: all-ones if roll < b2, else 0
    let m_lt_b2 = lt_mask_u32(roll, b2);
    // m_lt_b1: all-ones if roll < b1, else 0
    let m_lt_b1 = lt_mask_u32(roll, b1);
    // m_lt_b0: all-ones if roll < b0, else 0
    let m_lt_b0 = lt_mask_u32(roll, b0);

    // Build result bottom-up: 3 is default; select 2 if roll<b2; select 1 if roll<b1; select 0 if roll<b0.
    let choice = select_u32(m_lt_b2, 2, 3);
    let choice = select_u32(m_lt_b1, 1, choice);
    let choice = select_u32(m_lt_b0, 0, choice);

    choice as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn choice_weight_selected_reference(state: u64, input: u64) -> u64 {
        let roll = (state & 0xFF) as u32;
        let b0 = (input & 0xFF) as u32;
        let b1 = ((input >> 8) & 0xFF) as u32;
        let b2 = ((input >> 16) & 0xFF) as u32;
        if roll < b0 {
            0
        } else if roll < b1 {
            1
        } else if roll < b2 {
            2
        } else {
            3
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !choice_weight_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        choice_weight_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(choice_weight_selected_reference(s, i), choice_weight_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = choice_weight_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = choice_weight_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // roll=10, b=[64,128,192] -> 10 < 64 -> choice 0
        let input = 64u64 | (128u64 << 8) | (192u64 << 16);
        assert_eq!(choice_weight_selected(10, input), 0);
        // roll=100, b=[64,128,192] -> 64<=100<128 -> choice 1
        assert_eq!(choice_weight_selected(100, input), 1);
        // roll=200, b=[64,128,192] -> 200>=192 -> choice 3
        assert_eq!(choice_weight_selected(200, input), 3);
    }

    const BOUNDS: u64 = 64u64 | (128u64 << 8) | (192u64 << 16);

    fn must_admit() -> &'static [(u64, u64)] {
        // Interior buckets: roll < b0 -> 0; b0 <= roll < b1 -> 1.
        &[(10, BOUNDS), (100, BOUNDS)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // roll >= b2: the top bucket (choice 3) must be selected.
        &[(200, BOUNDS), (192, BOUNDS)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: caps the default at bucket 2, dropping the roll >= b2 boundary.
        let roll = (s & 0xFF) as u32;
        let b0 = (i & 0xFF) as u32;
        let b1 = ((i >> 8) & 0xFF) as u32;
        let choice = 2u32;
        let choice = select_u32(lt_mask_u32(roll, b1), 1, choice);
        let choice = select_u32(lt_mask_u32(roll, b0), 0, choice);
        choice as u64
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                choice_weight_selected(s, i),
                choice_weight_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                choice_weight_selected(s, i),
                choice_weight_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != choice_weight_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 100;
    const I: u64 = 64u64 | (128u64 << 8) | (192u64 << 16);
    pub fn bench_choice_weight_selected(c: &mut Criterion) {
        c.bench_function("choice_weight_selected", |b| {
            b.iter(|| black_box(choice_weight_selected(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: three lt_mask_u32 comparisons partition [0,255] into four disjoint bucket intervals without conditional branches.
// Hoare-logic Verification Line 2: cascaded select_u32 from bucket 3 downward ensures the lowest-boundary match wins, preserving ordered bucket semantics.
