// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (command_opcode_encoded)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: CommandOpcodeEncoded
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Encode a semantic command type (0..=127) into a platform opcode class via branchless
//! boundary comparison. Four command families defined by thresholds [32, 64, 96] map
//! to opcode classes 0/1/2/3. The original command type is packed into the upper byte.

use bcinr_logic::mask::lt_mask_u32;

/// CommandOpcodeEncoded kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = semantic command type (0..=127).
/// - `input`: unused.
///
/// Returns: bits[0..8] = platform opcode class (0..3); bits[8..16] = original command type.
#[inline]
#[must_use]
pub fn command_opcode_encoded(state: u64, input: u64) -> u64 {
    let _ = input;
    let cmd = (state & 0x7F) as u32;
    // Branchless boundary classification: count how many thresholds cmd >= threshold.
    // lt_mask_u32(cmd, boundary) = 0xFFFFFFFF when cmd < boundary, else 0.
    // Negate and shift to get 1 when cmd >= boundary.
    let ge32 = (!lt_mask_u32(cmd, 32) >> 31) as u32; // 1 if cmd >= 32
    let ge64 = (!lt_mask_u32(cmd, 64) >> 31) as u32; // 1 if cmd >= 64
    let ge96 = (!lt_mask_u32(cmd, 96) >> 31) as u32; // 1 if cmd >= 96
                                                     // opcode_class = number of thresholds crossed = 0, 1, 2, or 3.
    let opcode_class = ge32 + ge64 + ge96;
    (opcode_class as u64) | ((cmd as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn command_opcode_encoded_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let c = state & 0x7F;
        let o = if c < 32 {
            0u64
        } else if c < 64 {
            1u64
        } else if c < 96 {
            2u64
        } else {
            3u64
        };
        o | (c << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !command_opcode_encoded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        command_opcode_encoded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(command_opcode_encoded_reference(s, i), command_opcode_encoded(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = command_opcode_encoded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = command_opcode_encoded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // cmd=10 -> class=0, packed cmd=10.
        let out = command_opcode_encoded(10, 0);
        assert_eq!(out & 0xFF, 0);
        assert_eq!((out >> 8) & 0xFF, 10);
        // cmd=50 -> class=1, packed cmd=50.
        let out2 = command_opcode_encoded(50, 0);
        assert_eq!(out2 & 0xFF, 1);
        assert_eq!((out2 >> 8) & 0xFF, 50);
        // cmd=100 -> class=3, packed cmd=100.
        let out3 = command_opcode_encoded(100, 0);
        assert_eq!(out3 & 0xFF, 3);
        assert_eq!((out3 >> 8) & 0xFF, 100);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: command in the lower opcode classes (below the top threshold).
        &[(10, 0), (50, 0), (70, 0)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain for a 3-threshold ladder: commands at/above 96 land in class 3.
        &[(100, 0), (127, 0)]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: drops the highest threshold (96), so class saturates at 2.
        let cmd = s & 0x7F;
        let o = (cmd >= 32) as u64 + (cmd >= 64) as u64;
        o | (cmd << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                command_opcode_encoded(s, i),
                command_opcode_encoded_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                command_opcode_encoded(s, i),
                command_opcode_encoded_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != command_opcode_encoded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 50;
    const I: u64 = 0;
    pub fn bench_command_opcode_encoded(c: &mut Criterion) {
        c.bench_function("command_opcode_encoded", |b| {
            b.iter(|| black_box(command_opcode_encoded(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: opcode_class equals the count of thresholds [32,64,96] that cmd crosses, branchlessly summed.
// Hoare-logic Verification Line 2: cmd is masked to 7 bits (0..=127) before classification, preserving original type in bits[8..16].
