// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (cooldown_legality_checked)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: CooldownLegalityChecked
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Authority: legality spec — an ability use is admissible iff the remaining cooldown is
//! non-negative; a negative cooldown (encoded with the i16 sign bit set) signals a
//! fast-fire cheat and is refused. Lowered onto a direct sign-bit extraction.

/// CooldownLegalityChecked kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = remaining cooldown as `i16` (bit15 = sign; negative = illegal).
///
/// Returns a verdict bitmask: `0` = ADMITTED (legal), nonzero = refusal.
/// - bit0 = cooldown_negative (the encoded value's sign bit is set).
#[inline]
#[must_use]
pub fn cooldown_legality_checked(state: u64, input: u64) -> u64 {
    let _ = input;
    (state >> 15) & 1
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn cooldown_legality_checked_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let c = (state & 0xFFFF) as i16;
        if c < 0 {
            1
        } else {
            0
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !cooldown_legality_checked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        cooldown_legality_checked_reference(s, i) ^ 0xFFFF
    }

    // --- Two-sided breed battery: legality corpus + weakened detector ---
    fn must_admit() -> &'static [(u64, u64)] {
        // (cooldown encoded as u16, unused)
        &[
            (0, 0),      // ready (zero)
            (1, 0),      // small positive
            (0x7FFF, 0), // i16::MAX, still non-negative
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            ((-1_i16 as u16) as u64, 0),   // -1 cooldown
            (0x8000, 0),                   // i16::MIN
            ((-100_i16 as u16) as u64, 0), // deeply negative fast-fire
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Deliberately broken: the sign check is deleted, so negative (cheating)
        // cooldowns are admitted just like ready ones.
        let _ = (s, i);
        0
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                cooldown_legality_checked_reference(s, i),
                cooldown_legality_checked(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = cooldown_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = cooldown_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            cooldown_legality_checked(0, 0),
            cooldown_legality_checked_reference(0, 0)
        );
        // i16::MAX is non-negative -> legal.
        assert_eq!(cooldown_legality_checked(0x7FFF, 0), 0);
        // i16::MIN (bit15 set) -> illegal.
        assert_eq!(cooldown_legality_checked(0x8000, 0), 1);
    }

    #[test]
    fn two_sided_admit() {
        for &(s, i) in must_admit() {
            assert_eq!(
                cooldown_legality_checked(s, i),
                0,
                "legal case must be admitted"
            );
        }
    }
    #[test]
    fn two_sided_refuse() {
        for &(s, i) in must_refuse() {
            assert_ne!(
                cooldown_legality_checked(s, i),
                0,
                "cheat case must be refused"
            );
        }
    }
    #[test]
    fn weakened_fails_corpus() {
        assert!(
            must_refuse().iter().any(|&(s, i)| weakened(s, i) == 0),
            "a weakened detector must admit >=1 cheat from the corpus"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_cooldown_legality_checked(c: &mut Criterion) {
        c.bench_function("cooldown_legality_checked", |b| {
            b.iter(|| black_box(cooldown_legality_checked(black_box(0x7FFF), black_box(0))))
        });
    }
}

// Hoare-logic Verification Line 1: verdict bit0 mirrors the i16 sign bit (bit15) of the cooldown.
// Hoare-logic Verification Line 2: every non-negative cooldown (bit15 clear) is admitted.
