// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (ctq_threshold_evaluated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: CtqThresholdEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Evaluate a Critical-to-Quality (CTQ) characteristic — return whether a measured value is
//! within spec [LSL, USL] and, when out of spec, which direction the violation is.

use bcinr_logic::mask::lt_mask_u32;

/// CtqThresholdEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = measured value (u16).
/// - `input`: bits[0..16] = LSL (lower spec limit), bits[16..32] = USL (upper spec limit).
///
/// Returns: bits[0..8] = in_spec (1 if LSL <= value <= USL, else 0);
///          bits[8..16] = direction (0=below LSL or in-spec, 1=above USL).
#[inline]
#[must_use]
pub fn ctq_threshold_evaluated(state: u64, input: u64) -> u64 {
    let value = (state & 0xFFFF) as u32;
    let lsl = (input & 0xFFFF) as u32;
    let usl = ((input >> 16) & 0xFFFF) as u32;

    // above_lsl: all-ones when value >= lsl (i.e., NOT value < lsl)
    let below_lsl = lt_mask_u32(value, lsl);
    let above_lsl = !below_lsl;
    // below_usl: all-ones when value <= usl (i.e., NOT usl < value)
    let above_usl_mask = lt_mask_u32(usl, value);
    let below_usl = !above_usl_mask;

    // in_spec: 1 iff value >= lsl AND value <= usl
    let in_spec = ((above_lsl & below_usl) >> 31) as u64;
    // direction: 1 iff value > usl (above upper spec limit)
    let above_usl = (above_usl_mask >> 31) as u64;

    (in_spec & 0xFF) | ((above_usl & 0xFF) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn ctq_threshold_evaluated_reference(state: u64, input: u64) -> u64 {
        let value = (state & 0xFFFF) as u32;
        let lsl = (input & 0xFFFF) as u32;
        let usl = ((input >> 16) & 0xFFFF) as u32;
        let in_spec = (value >= lsl && value <= usl) as u64;
        let dir = (value > usl) as u64;
        (in_spec & 0xFF) | ((dir & 0xFF) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !ctq_threshold_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        ctq_threshold_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(ctq_threshold_evaluated_reference(s, i), ctq_threshold_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = ctq_threshold_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = ctq_threshold_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // value=50, lsl=30, usl=70 -> in_spec=1, dir=0
        let out = ctq_threshold_evaluated(50, 30 | (70 << 16));
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFF, 0);
        // value=20, lsl=30, usl=70 -> below LSL: in_spec=0, dir=0
        let out2 = ctq_threshold_evaluated(20, 30 | (70 << 16));
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFF, 0);
        // value=80, lsl=30, usl=70 -> above USL: in_spec=0, dir=1
        let out3 = ctq_threshold_evaluated(80, 30 | (70 << 16));
        assert_eq!(out3 & 0xFF, 0);
        assert_eq!((out3 >> 8) & 0xFF, 1);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: value sits inside or below the spec window [LSL, USL].
        &[(50, 30 | (70 << 16)), (20, 30 | (70 << 16))]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: value strictly above USL, where the upper-bound check matters.
        &[(80, 30 | (70 << 16)), (100, 30 | (70 << 16))]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: drops the USL upper-bound clamp from in_spec.
        let value = (s & 0xFFFF) as u32;
        let lsl = (i & 0xFFFF) as u32;
        let usl = ((i >> 16) & 0xFFFF) as u32;
        let in_spec = (value >= lsl) as u64;
        let dir = (value > usl) as u64;
        (in_spec & 0xFF) | ((dir & 0xFF) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                ctq_threshold_evaluated(s, i),
                ctq_threshold_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                ctq_threshold_evaluated(s, i),
                ctq_threshold_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != ctq_threshold_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const S: u64 = 50;
    const I: u64 = 30 | (70 << 16);

    pub fn bench_ctq_threshold_evaluated(c: &mut Criterion) {
        c.bench_function("ctq_threshold_evaluated", |b| {
            b.iter(|| black_box(ctq_threshold_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: in_spec is 1 iff value is in [LSL, USL], verified by mask conjunction.
// Hoare-logic Verification Line 2: direction bit is 1 only when value strictly exceeds USL (above_usl_mask >> 31).
