// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (defect_rate_quantized)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: DefectRateQuantized
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp a measured defect rate (parts per million, fixed-point) to [0, 1_000_000] for
//! normalization. Computes (defects * 1_000_000) / sample_size clamped to [0, 1_000_000].

use bcinr_logic::fix::clamp_u32;

/// DefectRateQuantized kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = raw defect count (u32).
/// - `input`: bits[0..32] = sample size (u32, treated as >= 1).
///
/// Returns: bits[0..32] = defect rate per million (0..=1_000_000).
#[inline]
#[must_use]
pub fn defect_rate_quantized(state: u64, input: u64) -> u64 {
    let defects = state & 0xFFFF_FFFF;
    // Ensure sample >= 1 branchlessly: (sample | (sample == 0) as u64) gives 1 when 0.
    let raw_sample = input & 0xFFFF_FFFF;
    let is_zero = ((raw_sample == 0) as u64).wrapping_neg(); // all-ones if zero
    let sample = raw_sample | (is_zero & 1u64); // substitute 1 when zero
    let rate = (defects.saturating_mul(1_000_000)) / sample;
    let clamped = clamp_u32(rate.min(1_000_000) as u32, 0, 1_000_000);
    (clamped as u64) & 0xFFFF_FFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn defect_rate_quantized_reference(state: u64, input: u64) -> u64 {
        let defects = state & 0xFFFF_FFFF;
        let raw_sample = input & 0xFFFF_FFFF;
        let sample = if raw_sample == 0 { 1u64 } else { raw_sample };
        let rate = (defects * 1_000_000) / sample;
        rate.min(1_000_000) & 0xFFFF_FFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !defect_rate_quantized_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        defect_rate_quantized_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(defect_rate_quantized_reference(s, i), defect_rate_quantized(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = defect_rate_quantized_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = defect_rate_quantized_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // defects=5, sample=1000 -> rate = 5000
        assert_eq!(defect_rate_quantized(5, 1000), 5000);
        // defects=0, sample=100 -> rate = 0
        assert_eq!(defect_rate_quantized(0, 100), 0);
        // defects=1000, sample=1 -> rate = 1_000_000_000 clamped to 1_000_000
        assert_eq!(defect_rate_quantized(1000, 1), 1_000_000);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: rate stays below the 1_000_000 PPM ceiling (no clamp needed).
        &[(5, 1000), (0, 100), (50, 1000)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: raw rate explodes far past 1_000_000 and must be clamped.
        &[(1000, 1), (2000, 1)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the [0, 1_000_000] ceiling clamp.
        let defects = s & 0xFFFF_FFFF;
        let raw_sample = i & 0xFFFF_FFFF;
        let sample = raw_sample.max(1);
        (defects.saturating_mul(1_000_000) / sample) & 0xFFFF_FFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                defect_rate_quantized(s, i),
                defect_rate_quantized_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                defect_rate_quantized(s, i),
                defect_rate_quantized_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != defect_rate_quantized_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const S: u64 = 5;
    const I: u64 = 1000;

    pub fn bench_defect_rate_quantized(c: &mut Criterion) {
        c.bench_function("defect_rate_quantized", |b| {
            b.iter(|| black_box(defect_rate_quantized(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: result is always in [0, 1_000_000], satisfying the PPM normalization invariant.
// Hoare-logic Verification Line 2: sample size is clamped to >= 1 branchlessly, preventing division by zero.
