// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (dialogue_node_advanced)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: DialogueNodeAdvanced
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a 6-state linear dialogue tree FSM via branchless DFA table lookup.
//! States: START=0, NODE_A=1, NODE_B=2, NODE_C=3, END=4, LOCKED=5.
//! Symbols: NEXT=0, BACK=1, CHOICE_A=2, CHOICE_B=3, LOCK=4, UNLOCK=5.

use bcinr_logic::dfa::dfa_advance;

// Dialogue FSM states
const START: usize = 0;
const NODE_A: usize = 1;
const NODE_B: usize = 2;
const NODE_C: usize = 3;
const END: usize = 4;
const LOCKED: usize = 5;

// Transition table: TABLE[state * 6 + symbol] = next_state
// Rows: START=0, NODE_A=1, NODE_B=2, NODE_C=3, END=4, LOCKED=5
// Cols: NEXT=0, BACK=1, CHOICE_A=2, CHOICE_B=3, LOCK=4, UNLOCK=5
#[rustfmt::skip]
static DIALOGUE_TABLE: [usize; 36] = [
    // START:  NEXT->NODE_A, BACK->START,  CHOICE_A->NODE_A, CHOICE_B->NODE_B, LOCK->LOCKED, UNLOCK->START
    NODE_A, START,  NODE_A, NODE_B, LOCKED, START,
    // NODE_A: NEXT->NODE_B, BACK->START,  CHOICE_A->NODE_A, CHOICE_B->NODE_B, LOCK->LOCKED, UNLOCK->NODE_A
    NODE_B, START,  NODE_A, NODE_B, LOCKED, NODE_A,
    // NODE_B: NEXT->NODE_C, BACK->NODE_A, CHOICE_A->NODE_A, CHOICE_B->NODE_B, LOCK->LOCKED, UNLOCK->NODE_B
    NODE_C, NODE_A, NODE_A, NODE_B, LOCKED, NODE_B,
    // NODE_C: NEXT->END,    BACK->NODE_B, CHOICE_A->NODE_C, CHOICE_B->NODE_C, LOCK->LOCKED, UNLOCK->NODE_C
    END,    NODE_B, NODE_C, NODE_C, LOCKED, NODE_C,
    // END:    NEXT->END,    BACK->NODE_C, CHOICE_A->END,    CHOICE_B->END,    LOCK->LOCKED, UNLOCK->END
    END,    NODE_C, END,    END,    LOCKED, END,
    // LOCKED: NEXT->LOCKED, BACK->LOCKED, CHOICE_A->LOCKED, CHOICE_B->LOCKED, LOCK->LOCKED, UNLOCK->START
    LOCKED, LOCKED, LOCKED, LOCKED, LOCKED, START,
];

/// DialogueNodeAdvanced kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current dialogue state (0=START, 1=NODE_A, 2=NODE_B, 3=NODE_C, 4=END, 5=LOCKED)
/// - `input`: bits[0..8] = symbol (0=NEXT, 1=BACK, 2=CHOICE_A, 3=CHOICE_B, 4=LOCK, 5=UNLOCK)
///
/// Returns bits[0..8] = next dialogue state.
#[inline]
#[must_use]
pub fn dialogue_node_advanced(state: u64, input: u64) -> u64 {
    let current = (state & 0xFF) as usize;
    let symbol = (input & 0xFF) as u8;
    dfa_advance(current, symbol, &DIALOGUE_TABLE, 6) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn dialogue_node_advanced_reference(state: u64, input: u64) -> u64 {
        let s = ((state & 0xFF) as usize).min(5);
        let sym = ((input & 0xFF) as usize).min(5);
        let next = match (s, sym) {
            // START
            (0, 0) => 1, // NEXT -> NODE_A
            (0, 1) => 0, // BACK -> START
            (0, 2) => 1, // CHOICE_A -> NODE_A
            (0, 3) => 2, // CHOICE_B -> NODE_B
            (0, 4) => 5, // LOCK -> LOCKED
            (0, 5) => 0, // UNLOCK -> START
            // NODE_A
            (1, 0) => 2, // NEXT -> NODE_B
            (1, 1) => 0, // BACK -> START
            (1, 2) => 1, // CHOICE_A -> NODE_A
            (1, 3) => 2, // CHOICE_B -> NODE_B
            (1, 4) => 5, // LOCK -> LOCKED
            (1, 5) => 1, // UNLOCK -> NODE_A
            // NODE_B
            (2, 0) => 3, // NEXT -> NODE_C
            (2, 1) => 1, // BACK -> NODE_A
            (2, 2) => 1, // CHOICE_A -> NODE_A
            (2, 3) => 2, // CHOICE_B -> NODE_B
            (2, 4) => 5, // LOCK -> LOCKED
            (2, 5) => 2, // UNLOCK -> NODE_B
            // NODE_C
            (3, 0) => 4, // NEXT -> END
            (3, 1) => 2, // BACK -> NODE_B
            (3, 2) => 3, // CHOICE_A -> NODE_C
            (3, 3) => 3, // CHOICE_B -> NODE_C
            (3, 4) => 5, // LOCK -> LOCKED
            (3, 5) => 3, // UNLOCK -> NODE_C
            // END
            (4, 0) => 4, // NEXT -> END
            (4, 1) => 3, // BACK -> NODE_C
            (4, 2) => 4, // CHOICE_A -> END
            (4, 3) => 4, // CHOICE_B -> END
            (4, 4) => 5, // LOCK -> LOCKED
            (4, 5) => 4, // UNLOCK -> END
            // LOCKED
            (5, 0) => 5, // NEXT -> LOCKED
            (5, 1) => 5, // BACK -> LOCKED
            (5, 2) => 5, // CHOICE_A -> LOCKED
            (5, 3) => 5, // CHOICE_B -> LOCKED
            (5, 4) => 5, // LOCK -> LOCKED
            (5, 5) => 0, // UNLOCK -> START
            _ => s,
        };
        next as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !dialogue_node_advanced_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        dialogue_node_advanced_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in 0u64..6, i in 0u64..6) {
            prop_assert_eq!(dialogue_node_advanced_reference(s, i), dialogue_node_advanced(s, i));
        }
        #[test]
        fn cf1(s in 0u64..6, i in 0u64..6) {
            let r = dialogue_node_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in 0u64..6, i in 0u64..6) {
            let r = dialogue_node_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // START + NEXT -> NODE_A
        assert_eq!(dialogue_node_advanced(0, 0), 1);
        // NODE_C + NEXT -> END
        assert_eq!(dialogue_node_advanced(3, 0), 4);
        // LOCKED + UNLOCK -> START
        assert_eq!(dialogue_node_advanced(5, 5), 0);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain advancing transitions.
        &[(0, 0), (3, 0)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // LOCKED is an absorbing trap: every symbol except UNLOCK stays LOCKED.
        &[(5, 0), (5, 2)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: drops the LOCKED absorbing trap, letting it escape on any symbol.
        let st = ((s & 0xFF) as usize).min(5);
        let r = dialogue_node_advanced_reference(s, i);
        if st == 5 {
            0
        } else {
            r
        }
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                dialogue_node_advanced(s, i),
                dialogue_node_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                dialogue_node_advanced(s, i),
                dialogue_node_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != dialogue_node_advanced_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 0;
    const I: u64 = 0;
    pub fn bench_dialogue_node_advanced(c: &mut Criterion) {
        c.bench_function("dialogue_node_advanced", |b| {
            b.iter(|| black_box(dialogue_node_advanced(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: dfa_advance indexes DIALOGUE_TABLE at state*6+symbol with bounds-safe masking — no branch.
// Hoare-logic Verification Line 2: transition table encodes all 36 (state, symbol) pairs; LOCKED state absorbs all inputs except UNLOCK.
