// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (dialogue_cooldown_bounded)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: DialogueCooldownBounded
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Decrement a dialogue cooldown counter by a tick delta, clamping to 0. Returns the new
//! cooldown and a ready flag (1 when cooldown reaches 0). Uses branchless saturating
//! subtraction and equality masking to avoid conditional branches.

use bcinr_logic::mask::eq_mask_u32;

/// DialogueCooldownBounded kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current cooldown ticks.
/// - `input`: bits[0..16] = tick delta to subtract.
///
/// Returns: bits[0..16] = new cooldown (clamped to 0); bits[16..24] = ready flag (1 if cooldown is now 0).
#[inline]
#[must_use]
pub fn dialogue_cooldown_bounded(state: u64, input: u64) -> u64 {
    let cooldown = (state & 0xFFFF) as u32;
    let delta = (input & 0xFFFF) as u32;
    let new_cd = cooldown.saturating_sub(delta);
    // ready when new_cd == 0: eq_mask_u32(new_cd, 0) >> 31
    let ready = (eq_mask_u32(new_cd, 0) >> 31) as u64;
    (new_cd as u64) | (ready << 16)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn dialogue_cooldown_bounded_reference(state: u64, input: u64) -> u64 {
        let cooldown = (state & 0xFFFF) as u32;
        let delta = (input & 0xFFFF) as u32;
        let nc = cooldown.saturating_sub(delta);
        nc as u64 | (((nc == 0) as u64) << 16)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !dialogue_cooldown_bounded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        dialogue_cooldown_bounded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(dialogue_cooldown_bounded_reference(s, i), dialogue_cooldown_bounded(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = dialogue_cooldown_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = dialogue_cooldown_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // cooldown=10, delta=3 -> new_cd=7, ready=0
        assert_eq!(dialogue_cooldown_bounded(10, 3), 7u64);
        // cooldown=3, delta=10 -> new_cd=0, ready=1
        assert_eq!(dialogue_cooldown_bounded(3, 10), (1u64 << 16));
        // cooldown=0, delta=5 -> new_cd=0, ready=1
        assert_eq!(dialogue_cooldown_bounded(0, 5), (1u64 << 16));
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // delta < cooldown: counter decrements without underflow, not ready.
        &[(10, 3), (100, 1)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // delta >= cooldown: the saturating floor must clamp to 0 and set ready.
        &[(3, 10), (0, 5)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: wrapping subtraction with no floor, so underflow escapes the clamp.
        let cooldown = (s & 0xFFFF) as u32;
        let delta = (i & 0xFFFF) as u32;
        let nc = cooldown.wrapping_sub(delta) & 0xFFFF;
        let ready = (nc == 0) as u64;
        (nc as u64) | (ready << 16)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                dialogue_cooldown_bounded(s, i),
                dialogue_cooldown_bounded_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                dialogue_cooldown_bounded(s, i),
                dialogue_cooldown_bounded_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != dialogue_cooldown_bounded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 10;
    const I: u64 = 3;
    pub fn bench_dialogue_cooldown_bounded(c: &mut Criterion) {
        c.bench_function("dialogue_cooldown_bounded", |b| {
            b.iter(|| black_box(dialogue_cooldown_bounded(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: saturating_sub ensures new_cd >= 0 and clamps at zero without branching.
// Hoare-logic Verification Line 2: eq_mask_u32(new_cd, 0) >> 31 produces a branchless ready flag: 1 iff new_cd == 0.
