// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (entity_state_transitioned)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: EntityStateTransitioned
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance an entity lifecycle DFA (Idle -> Active -> Hurt -> Dead) one transition with
//! [`bcinr_logic::dfa::dfa_advance`] over a flat transition table.

use bcinr_logic::dfa::dfa_advance;

/// States: 0=Idle, 1=Active, 2=Hurt, 3=Dead. Alphabet: 0=spawn, 1=hit, 2=heal, 3=kill.
const ALPHABET: usize = 4;
#[rustfmt::skip]
const TABLE: [usize; 16] = [
    // input: spawn active  hit    heal   kill
    /* Idle   */ 1, 0, 0, 3,
    /* Active */ 1, 2, 1, 3,
    /* Hurt   */ 1, 2, 1, 3,
    /* Dead   */ 3, 3, 3, 3,
];

/// EntityStateTransitioned kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current state index (clamped to `[0, 4)`).
/// - `input`: bits[0..8] = event symbol (clamped to `[0, 4)`).
///
/// Returns the next state index in bits[0..8].
#[inline]
#[must_use]
pub fn entity_state_transitioned(state: u64, input: u64) -> u64 {
    let st = (state as usize) & 0x3;
    let sym = (input & 0xFF) as u8;
    let sym = sym & 0x3; // clamp into alphabet branchlessly
    let next = dfa_advance(st, sym, &TABLE, ALPHABET);
    (next as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn entity_state_transitioned_reference(state: u64, input: u64) -> u64 {
        let st = (state as usize) & 0x3;
        let sym = ((input & 0xFF) as usize) & 0x3;
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !entity_state_transitioned_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        entity_state_transitioned_reference(s, i) ^ 0xFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                entity_state_transitioned_reference(s, i),
                entity_state_transitioned(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = entity_state_transitioned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = entity_state_transitioned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Idle + spawn -> Active.
        assert_eq!(entity_state_transitioned(0, 0), 1);
        // Active + kill -> Dead.
        assert_eq!(entity_state_transitioned(1, 3), 3);
        // Dead is absorbing.
        assert_eq!(entity_state_transitioned(3, 0), 3);
    }

    // Two-sided breed-rigor battery.
    // Legal lifecycle transitions out of live states.
    fn must_admit() -> &'static [(u64, u64)] {
        &[(0, 0), (1, 3), (1, 1)]
    }
    // Extreme: the absorbing Dead state must stay Dead for every event symbol.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(3, 0), (3, 2)]
    }
    // Weakened: drops the absorbing-Dead rule by collapsing Dead onto Hurt (wrong branch).
    fn weakened(s: u64, i: u64) -> u64 {
        let st = ((s as usize) & 0x3).min(2);
        let sym = ((i & 0xFF) as usize) & 0x3;
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                entity_state_transitioned(s, i),
                entity_state_transitioned_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                entity_state_transitioned(s, i),
                entity_state_transitioned_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != entity_state_transitioned_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_entity_state_transitioned(c: &mut Criterion) {
        c.bench_function("entity_state_transitioned", |b| {
            b.iter(|| black_box(entity_state_transitioned(black_box(1), black_box(1))))
        });
    }
}

// Hoare-logic Verification Line 1: the Dead state is absorbing for every input symbol.
// Hoare-logic Verification Line 2: state/symbol clamping keeps the table index in bounds.
