// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (fixed_tick_advanced)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: FixedTickAdvanced
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a fixed-step accumulator: saturating-add elapsed micros to the leftover
//! remainder, then snap the total down to a whole multiple of the step with
//! [`bcinr_logic::fix::bucketize_u32`].

use bcinr_logic::fix::bucketize_u32;
use bcinr_logic::int::saturating_add_i64;

/// FixedTickAdvanced kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = leftover accumulator (sub-step micros carried in).
/// - `input`: bits[0..32] = elapsed micros, bits[32..48] = step size (micros/tick),
///   defaulting to `1` when zero.
///
/// Returns: bits[0..32] = whole micros consumed this advance (a multiple of step).
#[inline]
#[must_use]
pub fn fixed_tick_advanced(state: u64, input: u64) -> u64 {
    let acc = (state & 0xFFFF_FFFF) as i64;
    let elapsed = (input & 0xFFFF_FFFF) as i64;
    let step = (input >> 32) & 0xFFFF;
    let step = step | ((step == 0) as u64); // step >= 1, branchlessly
    let total = saturating_add_i64(acc, elapsed);
    let total = (total & 0xFFFF_FFFF) as u32;
    let whole = bucketize_u32(total, step as u32);
    (whole as u64) & 0xFFFF_FFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn fixed_tick_advanced_reference(state: u64, input: u64) -> u64 {
        let acc = (state & 0xFFFF_FFFF) as i64;
        let elapsed = (input & 0xFFFF_FFFF) as i64;
        let mut step = (input >> 32) & 0xFFFF;
        if step == 0 {
            step = 1;
        }
        let total = (acc.saturating_add(elapsed) & 0xFFFF_FFFF) as u64;
        let whole = (total / step) * step;
        whole & 0xFFFF_FFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !fixed_tick_advanced_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        fixed_tick_advanced_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(fixed_tick_advanced_reference(s, i), fixed_tick_advanced(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = fixed_tick_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = fixed_tick_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(fixed_tick_advanced(0, 0), 0);
        // step=10, acc=3, elapsed=29 -> total 32 -> whole 30.
        let input = 3u64 | (10u64 << 32);
        assert_eq!(fixed_tick_advanced(29, input), 30);
        assert_eq!(
            fixed_tick_advanced(0xFFFF_FFFF, 0xFFFF_FFFF),
            fixed_tick_advanced_reference(0xFFFF_FFFF, 0xFFFF_FFFF)
        );
    }

    // Two-sided breed-rigor battery.
    // Legal: totals already aligned to the step (snap-down is a no-op).
    fn must_admit() -> &'static [(u64, u64)] {
        &[(0, 0), (30, 10 << 32), (10, 10 | (10 << 32))]
    }
    // Extreme: totals that are NOT a step multiple, so the kernel must snap down.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (29, 3 | (10 << 32)),
            (0xFFFF_FFFF, 0xFFFF_FFFF | (10 << 32)),
        ]
    }
    // Weakened: omits the bucketize snap-down, returning the raw (unaligned) total.
    fn weakened(s: u64, i: u64) -> u64 {
        let acc = (s & 0xFFFF_FFFF) as i64;
        let elapsed = (i & 0xFFFF_FFFF) as i64;
        let total = (acc.saturating_add(elapsed) & 0xFFFF_FFFF) as u64;
        total & 0xFFFF_FFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                fixed_tick_advanced(s, i),
                fixed_tick_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                fixed_tick_advanced(s, i),
                fixed_tick_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != fixed_tick_advanced_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_fixed_tick_advanced(c: &mut Criterion) {
        c.bench_function("fixed_tick_advanced", |b| {
            b.iter(|| {
                black_box(fixed_tick_advanced(
                    black_box(29),
                    black_box(3 | (10 << 32)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: output is always a whole multiple of the (>=1) step.
// Hoare-logic Verification Line 2: accumulation saturates rather than wrapping past i64::MAX.
