// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (fov_adjusted)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: FovAdjusted
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Adjust field-of-view by a signed delta, clamping to [min_fov, max_fov] using
//! [`bcinr_logic::int::saturating_add_i64`] and i64 intrinsic min/max.

use bcinr_logic::int::saturating_add_i64;

/// FovAdjusted kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current FOV (u16, e.g. 0..180 degrees ×10 fixed-point).
/// - `input`: bits[0..16] = delta as signed-encoded u16 (bit15=sign, bits[0..15]=magnitude);
///   bits[16..24] = min_fov; bits[24..32] = max_fov.
///
/// Returns: bits[0..16] = new clamped FOV.
#[inline]
#[must_use]
pub fn fov_adjusted(state: u64, input: u64) -> u64 {
    let fov = (state & 0xFFFF) as i64;
    let raw_delta = (input & 0xFFFF) as i64;
    let bit15 = raw_delta >> 15; // 0 if positive, 1 if bit-15 set (sign bit)
    let mag = raw_delta & 0x7FFF;
    let delta = (1 - 2 * bit15) * mag; // branchless: +mag if bit15=0, -mag if bit15=1
    let min_fov = ((input >> 16) & 0xFF) as i64;
    let max_fov = ((input >> 24) & 0xFF) as i64;
    let new_fov = saturating_add_i64(fov, delta).max(min_fov).min(max_fov);
    (new_fov as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn fov_adjusted_reference(state: u64, input: u64) -> u64 {
        let fov = (state & 0xFFFF) as i64;
        let raw_delta = (input & 0xFFFF) as i64;
        let d = if (raw_delta >> 15) != 0 {
            -(raw_delta & 0x7FFF)
        } else {
            raw_delta & 0x7FFF
        };
        let min_fov = ((input >> 16) & 0xFF) as i64;
        let max_fov = ((input >> 24) & 0xFF) as i64;
        ((fov + d).clamp(min_fov, max_fov) as u64) & 0xFFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !fov_adjusted_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        fov_adjusted_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            // Only test when min_fov <= max_fov to match reference behaviour.
            let min_fov = ((i >> 16) & 0xFF) as i64;
            let max_fov = ((i >> 24) & 0xFF) as i64;
            if min_fov <= max_fov {
                prop_assert_eq!(fov_adjusted_reference(s, i), fov_adjusted(s, i));
            }
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let min_fov = ((i >> 16) & 0xFF) as i64;
            let max_fov = ((i >> 24) & 0xFF) as i64;
            prop_assume!(min_fov <= max_fov);
            let r = fov_adjusted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let min_fov = ((i >> 16) & 0xFF) as i64;
            let max_fov = ((i >> 24) & 0xFF) as i64;
            prop_assume!(min_fov <= max_fov);
            let r = fov_adjusted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Pack: min_fov=30 (bits 16..24), max_fov=120 (bits 24..32)
        // input upper 16 bits = 30 | (120 << 8) = 30 + 30720 = 30750
        let upper: u64 = 30750 << 16; // 30 | (120 << 8) packed into bits [16..32]
                                      // fov=90, delta=+10, min=30, max=120 -> 100
        let s1 = 90u64;
        let i1 = 10u64 | upper; // delta=10 (positive, bit15=0)
        assert_eq!(fov_adjusted(s1, i1), 100);
        // fov=90, delta=-100, min=30, max=120 -> 30 (clamped at floor)
        // -100 encoded: bit15=1, magnitude=100 -> 0x8000 | 100 = 32868
        let i2 = (0x8000u64 | 100u64) | upper;
        assert_eq!(fov_adjusted(s1, i2), 30);
        // fov=90, delta=+100, min=30, max=120 -> 120 (clamped at ceiling)
        let i3 = 100u64 | upper;
        assert_eq!(fov_adjusted(s1, i3), 120);
    }

    // Two-sided breed-rigor battery. Packing helper: min=30, max=120 in bits[16..32].
    const FOV_BOUNDS: u64 = 30750 << 16; // 30 | (120 << 8)
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: fov+delta lands inside [30, 120], clamp does not fire.
        &[
            (90, 10 | FOV_BOUNDS),         // +10 -> 100
            (50, 0x8000 | 5 | FOV_BOUNDS), // -5  -> 45
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: delta drives result past a bound, clamp fires.
        &[
            (90, 100 | FOV_BOUNDS),          // +100 -> 190 -> clamp 120
            (90, 0x8000 | 100 | FOV_BOUNDS), // -100 -> -10 -> clamp 30
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the [min, max] clamp.
        let fov = (s & 0xFFFF) as i64;
        let raw_delta = (i & 0xFFFF) as i64;
        let d = if (raw_delta >> 15) != 0 {
            -(raw_delta & 0x7FFF)
        } else {
            raw_delta & 0x7FFF
        };
        ((fov + d) as u64) & 0xFFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(fov_adjusted(s, i), fov_adjusted_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(fov_adjusted(s, i), fov_adjusted_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != fov_adjusted_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_fov_adjusted(c: &mut Criterion) {
        let upper: u64 = 30750u64 << 16;
        let s = 90u64;
        let i = 10u64 | upper;
        c.bench_function("fov_adjusted", |b| {
            b.iter(|| black_box(fov_adjusted(black_box(s), black_box(i))))
        });
    }
}

// Hoare-logic Verification Line 1: sign-magnitude decode is branchless via arithmetic shift and multiply.
// Hoare-logic Verification Line 2: saturating_add_i64 + i64 min/max clamp result to [min_fov, max_fov].
