// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (heuristic_distance_estimated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: HeuristicDistanceEstimated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Branchless Chebyshev distance (max of |dx|, |dy|) for A* heuristic using signed i16 deltas.

use bcinr_logic::mask::max_u32;

/// HeuristicDistanceEstimated kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = dx as u16 (two's complement i16)
/// - `input`: bits[0..16] = dy as u16 (two's complement i16)
///
/// Returns bits[0..16] = Chebyshev distance = max(|dx|, |dy|).
#[inline]
#[must_use]
pub fn heuristic_distance_estimated(state: u64, input: u64) -> u64 {
    let dx_raw = (state & 0xFFFF) as i32;
    let dy_raw = (input & 0xFFFF) as i32;
    // Sign-extend from 16-bit to 32-bit
    let dx = (dx_raw << 16) >> 16;
    let dy = (dy_raw << 16) >> 16;
    // Branchless abs: (v ^ (v >> 31)) - (v >> 31)
    let abs_dx = (dx ^ (dx >> 31)).wrapping_sub(dx >> 31) as u32;
    let abs_dy = (dy ^ (dy >> 31)).wrapping_sub(dy >> 31) as u32;
    (max_u32(abs_dx, abs_dy) as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn heuristic_distance_estimated_reference(state: u64, input: u64) -> u64 {
        let dx = (state & 0xFFFF) as u16 as i16;
        let dy = (input & 0xFFFF) as u16 as i16;
        dx.unsigned_abs().max(dy.unsigned_abs()) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !heuristic_distance_estimated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        heuristic_distance_estimated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test] fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(heuristic_distance_estimated_reference(s, i), heuristic_distance_estimated(s, i));
        }
        #[test] fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = heuristic_distance_estimated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test] fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = heuristic_distance_estimated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // dx=3, dy=-4 (packed as i16 two's complement) -> Chebyshev = 4
        let dy_neg4 = ((-4i16) as u16) as u64;
        assert_eq!(
            heuristic_distance_estimated(3, dy_neg4),
            heuristic_distance_estimated_reference(3, dy_neg4)
        );
        // dx=0, dy=0 -> 0
        assert_eq!(heuristic_distance_estimated(0, 0), 0);
        // dx=-5, dy=-5 -> 5
        let dx_neg5 = ((-5i16) as u16) as u64;
        let dy_neg5 = ((-5i16) as u16) as u64;
        assert_eq!(
            heuristic_distance_estimated(dx_neg5, dy_neg5),
            heuristic_distance_estimated_reference(dx_neg5, dy_neg5)
        );
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Both non-negative: plain max.
            (3, 4),
            // Origin: zero distance.
            (0, 0),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Negative dy: abs must rectify the sign before the max.
            (3, ((-4i16) as u16) as u64),
            // Both negative and large: abs is load-bearing on each axis.
            (((-5i16) as u16) as u64, ((-5i16) as u16) as u64),
        ]
    }

    // Weakened: drop the branchless abs and treat the sign-extended deltas as
    // unsigned, so negative components blow up instead of folding to magnitude.
    fn weakened(s: u64, i: u64) -> u64 {
        let dx_raw = (s & 0xFFFF) as i32;
        let dy_raw = (i & 0xFFFF) as i32;
        let dx = (dx_raw << 16) >> 16;
        let dy = (dy_raw << 16) >> 16;
        // BUG: no abs — negative i32 reinterpreted as a huge u32.
        let abs_dx = dx as u32;
        let abs_dy = dy as u32;
        (max_u32(abs_dx, abs_dy) as u64) & 0xFFFF
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                heuristic_distance_estimated(s, i),
                heuristic_distance_estimated_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                heuristic_distance_estimated(s, i),
                heuristic_distance_estimated_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != heuristic_distance_estimated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_heuristic_distance_estimated(c: &mut Criterion) {
        c.bench_function("heuristic_distance_estimated", |b| {
            b.iter(|| {
                black_box(heuristic_distance_estimated(
                    black_box(3),
                    black_box(0xFFFC_u64),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: branchless abs via arithmetic shift right preserves sign-magnitude invariant for all i16 inputs.
// Hoare-logic Verification Line 2: max_u32(abs_dx, abs_dy) yields Chebyshev norm without conditional branching.
