// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (inventory_item_changed)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: InventoryItemChanged
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Change an inventory: on add, find the first free slot in the occupancy bitset with
//! [`bcinr_logic::bitset::select_bit_u64`] over the inverted mask and occupy it; on remove,
//! clear a given slot. A full inventory reports the all-ones sentinel slot `0xFF`.

use bcinr_logic::bitset::{clear_bit_u64, select_bit_u64, set_bit_u64};

/// Sentinel returned in the slot field when no free slot exists.
pub const NO_SLOT: u64 = 0xFF;

/// InventoryItemChanged kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = occupancy bitset (32 slots; 1 = occupied).
/// - `input`: bit[0] = add(1)/remove(0), bits[8..16] = slot to remove (remove only).
///
/// Returns: bits[0..32] = new occupancy, bits[32..40] = affected slot (or `NO_SLOT`).
#[inline]
#[must_use]
pub fn inventory_item_changed(state: u64, input: u64) -> u64 {
    let occ = state & 0xFFFF_FFFF;
    let add = (input & 1) == 1;
    let rem_slot = ((input >> 8) & 0x1F) as usize;

    // First free slot = first set bit of the inverted, masked-to-32 occupancy.
    let free_bits = (!occ) & 0xFFFF_FFFF;
    let first_free = select_bit_u64(free_bits, 0);

    let (new_occ, slot) = match (add, first_free) {
        (true, Some(s)) => (set_bit_u64(occ, s) & 0xFFFF_FFFF, s as u64),
        (true, None) => (occ, NO_SLOT),
        (false, _) => (clear_bit_u64(occ, rem_slot) & 0xFFFF_FFFF, rem_slot as u64),
    };
    new_occ | (slot << 32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn inventory_item_changed_reference(state: u64, input: u64) -> u64 {
        let occ = state & 0xFFFF_FFFF;
        let add = (input & 1) == 1;
        let rem_slot = ((input >> 8) & 0x1F) as u32;
        if add {
            // First zero bit in the low 32 bits.
            let mut found: Option<u32> = None;
            for s in 0..32u32 {
                if (occ >> s) & 1 == 0 {
                    found = Some(s);
                    break;
                }
            }
            match found {
                Some(s) => ((occ | (1u64 << s)) & 0xFFFF_FFFF) | ((s as u64) << 32),
                None => occ | (NO_SLOT << 32),
            }
        } else {
            let new_occ = (occ & !(1u64 << rem_slot)) & 0xFFFF_FFFF;
            new_occ | ((rem_slot as u64) << 32)
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !inventory_item_changed_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        inventory_item_changed_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(inventory_item_changed_reference(s, i), inventory_item_changed(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = inventory_item_changed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = inventory_item_changed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // occ 0b0011 -> add to first free slot (2).
        let out = inventory_item_changed(0b0011, 1);
        assert_eq!(out & 0xFFFF_FFFF, 0b0111);
        assert_eq!((out >> 32) & 0xFF, 2);
        // Full low-32 occupancy -> NO_SLOT on add.
        let full = inventory_item_changed(0xFFFF_FFFF, 1);
        assert_eq!((full >> 32) & 0xFF, NO_SLOT);
        // Remove slot 1.
        let rem = inventory_item_changed(0b0011, 1u64 << 8);
        assert_eq!(rem & 0xFFFF_FFFF, 0b0001);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Add into a partly-free inventory: lowest free slot is 2.
            (0b0011, 1),
            // Remove slot 1 from an occupied inventory.
            (0b0011, 1u64 << 8),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Full low-32 occupancy + add: no free slot, must emit NO_SLOT sentinel.
            (0xFFFF_FFFF, 1),
            // Full inventory ignoring high bits: still no free slot.
            (0xFFFF_FFFF_FFFF_FFFF, 1),
        ]
    }

    // Weakened: drop the NO_SLOT sentinel, falling back to slot 0 when the
    // inventory is full instead of signalling overflow.
    fn weakened(s: u64, i: u64) -> u64 {
        let occ = s & 0xFFFF_FFFF;
        let add = (i & 1) == 1;
        let rem_slot = ((i >> 8) & 0x1F) as usize;
        let free_bits = (!occ) & 0xFFFF_FFFF;
        let first_free = select_bit_u64(free_bits, 0);
        let (new_occ, slot) = match (add, first_free) {
            (true, Some(s)) => (set_bit_u64(occ, s) & 0xFFFF_FFFF, s as u64),
            // BUG: full inventory reports slot 0 instead of NO_SLOT.
            (true, None) => (occ, 0),
            (false, _) => (clear_bit_u64(occ, rem_slot) & 0xFFFF_FFFF, rem_slot as u64),
        };
        new_occ | (slot << 32)
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                inventory_item_changed(s, i),
                inventory_item_changed_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                inventory_item_changed(s, i),
                inventory_item_changed_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != inventory_item_changed_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_inventory_item_changed(c: &mut Criterion) {
        c.bench_function("inventory_item_changed", |b| {
            b.iter(|| black_box(inventory_item_changed(black_box(0b0011), black_box(1))))
        });
    }
}

// Hoare-logic Verification Line 1: an add occupies the lowest free slot, else signals NO_SLOT.
// Hoare-logic Verification Line 2: occupancy is masked to 32 slots on every transition.
