// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (lag_compensation_applied)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: LagCompensationApplied
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Rewind a server-authoritative position by lag*velocity to estimate where the client was at a past tick.

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::int::saturating_sub_i64;

/// LagCompensationApplied kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = server_position (u16), bits[16..32] = velocity (i16 as u16, two's complement).
/// - `input`: bits[0..8] = lag_ticks (u8, number of ticks to rewind).
///
/// Returns: bits[0..16] = compensated position (clamped to [0, 0xFFFF]).
#[inline]
#[must_use]
pub fn lag_compensation_applied(state: u64, input: u64) -> u64 {
    let server_pos = (state & 0xFFFF) as i64;
    let vel_raw = ((state >> 16) & 0xFFFF) as i64;
    let velocity = (vel_raw as i16) as i64;
    let lag = (input & 0xFF) as i64;
    let rewind = saturating_sub_i64(server_pos, velocity * lag);
    let clamped = clamp_u32(rewind.max(0) as u32, 0, 0xFFFF);
    (clamped as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn lag_compensation_applied_reference(state: u64, input: u64) -> u64 {
        let server_pos = (state & 0xFFFF) as i64;
        let vel_raw = ((state >> 16) & 0xFFFF) as i64;
        let velocity = (vel_raw as i16) as i64;
        let lag = (input & 0xFF) as i64;
        let r = server_pos - velocity * lag;
        r.clamp(0, 0xFFFF) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !lag_compensation_applied_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        lag_compensation_applied_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(lag_compensation_applied_reference(s, i), lag_compensation_applied(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = lag_compensation_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = lag_compensation_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // pos=1000, vel=10, lag=5 -> 1000 - 10*5 = 950
        let s = 1000u64 | (10u64 << 16);
        let i = 5u64;
        assert_eq!(lag_compensation_applied(s, i), 950);

        // pos=100, vel=50, lag=5 -> 100 - 50*5 = -150 -> clamped to 0
        let s2 = 100u64 | (50u64 << 16);
        let i2 = 5u64;
        assert_eq!(lag_compensation_applied(s2, i2), 0);

        // pos=200, vel=0, lag=99 -> 200 - 0*99 = 200
        let s3 = 200u64;
        let i3 = 99u64;
        assert_eq!(lag_compensation_applied(s3, i3), 200);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: rewind lands inside [0, 0xFFFF], the clamp does not fire.
        &[
            (1000 | (10 << 16), 5), // 1000 - 50 -> 950
            (200, 99),              // vel=0 -> 200 unchanged
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: rewind underflows below 0, the clamp floors it.
        &[
            (100 | (50 << 16), 5),  // 100 - 250 -> -150 -> clamp 0
            (10 | (200 << 16), 99), // large rewind -> negative -> clamp 0
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the .max(0) / clamp; underflow leaks into the low word.
        let server_pos = (s & 0xFFFF) as i64;
        let vel_raw = ((s >> 16) & 0xFFFF) as i64;
        let velocity = (vel_raw as i16) as i64;
        let lag = (i & 0xFF) as i64;
        ((server_pos - velocity * lag) as u64) & 0xFFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                lag_compensation_applied(s, i),
                lag_compensation_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                lag_compensation_applied(s, i),
                lag_compensation_applied_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != lag_compensation_applied_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 1000 | (10 << 16);
    const I: u64 = 5;
    pub fn bench_lag_compensation_applied(c: &mut Criterion) {
        c.bench_function("lag_compensation_applied", |b| {
            b.iter(|| black_box(lag_compensation_applied(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: saturating_sub_i64(server_pos, velocity*lag) prevents i64 overflow wrap; .max(0) floors negative rewinds branchlessly.
// Hoare-logic Verification Line 2: clamp_u32 enforces compensated position in [0, 0xFFFF] with no conditional jumps.
