// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (level_gate_evaluated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: LevelGateEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Gate an ability or item unlock: if banned the result is REFUSED; if the player level
//! meets the requirement it is ADMITTED; otherwise BLOCKED. The priority ordering is
//! composed from [`bcinr_logic::mask::select_u32`] calls without any conditional branches.

use crate::class::status;
use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// LevelGateEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = player level, bits[8..16] = ban flag (1 = banned).
/// - `input`: bits[0..8] = required level.
///
/// Returns a [`crate::class::status`] code in bits[0..8]:
/// `ADMITTED` (4) if level met and not banned; `BLOCKED` (1) if level not met;
/// `REFUSED` (7) if banned (overrides level check).
#[inline]
#[must_use]
pub fn level_gate_evaluated(state: u64, input: u64) -> u64 {
    let player_level = (state & 0xFF) as u32;
    let banned = ((state >> 8) & 1) as u32;
    let required = (input & 0xFF) as u32;
    // meets_req is 0xFFFF_FFFF when player_level >= required, else 0.
    let meets_req = !lt_mask_u32(player_level, required);
    // Base: ADMITTED if meets requirement, BLOCKED otherwise.
    let base = select_u32(meets_req, status::ADMITTED as u32, status::BLOCKED as u32);
    // Ban mask: 0xFFFF_FFFF if banned, 0 if not.
    let ban_mask = 0u32.wrapping_sub(banned);
    // Ban overrides base: if banned, REFUSED.
    let result = select_u32(ban_mask, status::REFUSED as u32, base);
    (result as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn level_gate_evaluated_reference(state: u64, input: u64) -> u64 {
        let player_level = (state & 0xFF) as u32;
        let banned = ((state >> 8) & 1) as u32;
        let required = (input & 0xFF) as u32;
        let code = if banned == 1 {
            status::REFUSED
        } else if player_level >= required {
            status::ADMITTED
        } else {
            status::BLOCKED
        };
        (code as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !level_gate_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        level_gate_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(level_gate_evaluated_reference(s, i), level_gate_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = level_gate_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = level_gate_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // level=10, required=5, ban=0 -> ADMITTED.
        assert_eq!(level_gate_evaluated(10, 5), status::ADMITTED as u64);
        // level=3, required=5, ban=0 -> BLOCKED.
        assert_eq!(level_gate_evaluated(3, 5), status::BLOCKED as u64);
        // level=10, required=5, ban=1 -> REFUSED.
        assert_eq!(
            level_gate_evaluated(10 | (1u64 << 8), 5),
            status::REFUSED as u64
        );
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // Not banned, level met -> ADMITTED.
        &[(10, 5), (5, 5)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Banned (REFUSED, overrides level) and level-not-met (BLOCKED).
        &[(10 | (1u64 << 8), 5), (3, 5)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: ignores the ban flag, so banned-but-eligible escapes refusal.
        let player_level = (s & 0xFF) as u32;
        let required = (i & 0xFF) as u32;
        let code = if player_level >= required {
            status::ADMITTED
        } else {
            status::BLOCKED
        };
        (code as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                level_gate_evaluated(s, i),
                level_gate_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                level_gate_evaluated(s, i),
                level_gate_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != level_gate_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const STATE: u64 = 10;
    const INPUT: u64 = 5;

    pub fn bench_level_gate_evaluated(c: &mut Criterion) {
        c.bench_function("level_gate_evaluated", |b| {
            b.iter(|| black_box(level_gate_evaluated(black_box(STATE), black_box(INPUT))))
        });
    }
}

// Hoare-logic Verification Line 1: ban overrides level check via select_u32 priority ordering.
// Hoare-logic Verification Line 2: result is always a valid status code drawn from the vocabulary.
