// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (mastery_moment_detected)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: MasteryMomentDetected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Detect a mastery moment: shift a new success bit into a rolling streak window, count the
//! successes in the window with [`bcinr_logic::bitset::rank_u64`], and fire when the count
//! meets a threshold (branchless [`bcinr_logic::mask::lt_mask_u32`] comparison).

use bcinr_logic::bitset::rank_u64;
use bcinr_logic::mask::lt_mask_u32;

/// MasteryMomentDetected kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = rolling streak window (1 bit per recent attempt).
/// - `input`: bit[0] = new success flag, bits[8..16] = success threshold.
///
/// Returns: bits[0..32] = updated window, bits[32..40] = success count,
/// bit[40] = mastery-detected flag.
#[inline]
#[must_use]
pub fn mastery_moment_detected(state: u64, input: u64) -> u64 {
    let window = state & 0xFFFF_FFFF;
    let success = input & 1;
    let threshold = ((input >> 8) & 0xFF) as u32;

    let new_window = ((window << 1) | success) & 0xFFFF_FFFF;
    let count = rank_u64(new_window, 31) as u32;
    // Fire when count >= threshold, i.e. NOT (count < threshold).
    let detected = (!lt_mask_u32(count, threshold) & 1) as u64;

    new_window | ((count as u64) << 32) | (detected << 40)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn mastery_moment_detected_reference(state: u64, input: u64) -> u64 {
        let window = state & 0xFFFF_FFFF;
        let success = input & 1;
        let threshold = ((input >> 8) & 0xFF) as u32;
        let new_window = ((window << 1) | success) & 0xFFFF_FFFF;
        let count = new_window.count_ones();
        let detected = (count >= threshold) as u64;
        new_window | ((count as u64) << 32) | (detected << 40)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !mastery_moment_detected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        mastery_moment_detected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(mastery_moment_detected_reference(s, i), mastery_moment_detected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = mastery_moment_detected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = mastery_moment_detected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Window 0b0111 (3 successes), push success, threshold 4 -> detect.
        let input = 1u64 | (4u64 << 8);
        let out = mastery_moment_detected(0b0111, input);
        assert_eq!((out >> 32) & 0xFF, 4);
        assert_eq!((out >> 40) & 1, 1);
        // Threshold 5 -> no detect.
        let out2 = mastery_moment_detected(0b0111, 1 | (5u64 << 8));
        assert_eq!((out2 >> 40) & 1, 0);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Clearly below threshold: window 0b0001, push success -> count 2 < 5.
            (0b0001, 1u64 | (5u64 << 8)),
            // Clearly above threshold: window 0b0111, push success -> count 4 >= 2.
            (0b0111, 1u64 | (2u64 << 8)),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Exact equality edge: count 4 == threshold 4 must FIRE (>=, not >).
            (0b0111, 1u64 | (4u64 << 8)),
            // Threshold 0 with empty push (success=0, threshold=0): count 0 == 0 must FIRE.
            (0, 0),
        ]
    }

    // Weakened: fire on strict greater-than, dropping the >= equality boundary.
    fn weakened(s: u64, i: u64) -> u64 {
        let window = s & 0xFFFF_FFFF;
        let success = i & 1;
        let threshold = ((i >> 8) & 0xFF) as u32;
        let new_window = ((window << 1) | success) & 0xFFFF_FFFF;
        let count = rank_u64(new_window, 31) as u32;
        // BUG: strict > instead of >=, missing count == threshold.
        let detected = (lt_mask_u32(threshold, count) & 1) as u64;
        new_window | ((count as u64) << 32) | (detected << 40)
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                mastery_moment_detected(s, i),
                mastery_moment_detected_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                mastery_moment_detected(s, i),
                mastery_moment_detected_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != mastery_moment_detected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_mastery_moment_detected(c: &mut Criterion) {
        let input = 1u64 | (4u64 << 8);
        c.bench_function("mastery_moment_detected", |b| {
            b.iter(|| black_box(mastery_moment_detected(black_box(0b0111), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: detection fires iff window popcount >= threshold.
// Hoare-logic Verification Line 2: the streak window is bounded to 32 attempts.
