// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl + ggen/queries/pattern_index.rq.
// Regenerate: `ggen sync`.

//! Generated branchless pattern kernels — the wasm4games pattern registry.
//!
//! GENERATED SURFACE: produced by `ggen sync` and committed for offline builds.
//!
//! This module is the single entry point for all 75 branchless pattern kernels.
//! Each sub-module corresponds to one row in `ggen/schema/patterns.ttl` and exposes a
//! pure `fn(state: u64, input: u64) -> u64` kernel with the following guarantees:
//!
//! - **Branchless:** No conditional jumps; execution time is data-independent.
//! - **Deterministic:** Identical inputs always produce identical outputs.
//! - **Oracle-verified:** Each kernel is property-tested against a branchful reference.
//! - **No unsafe:** All generated kernels carry `#![forbid(unsafe_code)]`.
//!
//! The [`PATTERN_REGISTRY`] static slice contains the full catalog as structured data,
//! iterated by [`crate::verify`] for admission-contract verification.
//!
//! To add a new pattern, edit `ggen/schema/patterns.ttl` and run `ggen sync`.
//! See `docs/diataxis/tutorials/wasm4games-add-a-pattern.md` for the full workflow.
//!
//! Pattern count: 75

use crate::class::status;
use crate::ir::{AdmissionRule, EventKind, LoweringKind, ObjectKind, PatternId, PatternSpec};

// --- Kernel modules (ordered by pattern id) ---

/// [5] AabbCollisionResolved — Mask
pub mod aabb_collision_resolved;
/// [69] ActionMaskApplied — Mask
pub mod action_mask_applied;
/// [74] ActionRateBounded — Mask
pub mod action_rate_bounded;
/// [65] AdapterPriorityRanked — Network
pub mod adapter_priority_ranked;
/// [13] AiActionSelected — Mask
pub mod ai_action_selected;
/// [50] AudioDistanceAttenuated — Lut
pub mod audio_distance_attenuated;
/// [48] AudioFadeApplied — Saturating
pub mod audio_fade_applied;
/// [46] AudioPrioritySelected — Mask
pub mod audio_priority_selected;
/// [49] AudioTriggerEvaluated — Dfa
pub mod audio_trigger_evaluated;
/// [30] BiomeClassSelected — Bitset
pub mod biome_class_selected;
/// [63] BridgeStateTransitioned — Dfa
pub mod bridge_state_transitioned;
/// [41] CameraDistanceClamped — Lut
pub mod camera_distance_clamped;
/// [45] CameraFollowLerped — Lut
pub mod camera_follow_lerped;
/// [44] CameraShakeApplied — Receipt
pub mod camera_shake_applied;
/// [62] CapabilityFlagEvaluated — Bitset
pub mod capability_flag_evaluated;
/// [40] ChoiceWeightSelected — Mask
pub mod choice_weight_selected;
/// [61] CommandOpcodeEncoded — Mask
pub mod command_opcode_encoded;
/// [37] ConditionFlagEvaluated — Bitset
pub mod condition_flag_evaluated;
/// [73] CooldownLegalityChecked — Bitset
pub mod cooldown_legality_checked;
/// [58] CtqThresholdEvaluated — Mask
pub mod ctq_threshold_evaluated;
/// [31] CurrencyDeltaApplied — Saturating
pub mod currency_delta_applied;
/// [14] DamageApplied — Saturating
pub mod damage_applied;
/// [57] DefectRateQuantized — Lut
pub mod defect_rate_quantized;
/// [39] DialogueCooldownBounded — Mask
pub mod dialogue_cooldown_bounded;
/// [36] DialogueNodeAdvanced — Dfa
pub mod dialogue_node_advanced;
/// [3] EntityStateTransitioned — Dfa
pub mod entity_state_transitioned;
/// [70] EpisodeReturnBounded — Saturating
pub mod episode_return_bounded;
/// [2] FixedTickAdvanced — Saturating
pub mod fixed_tick_advanced;
/// [43] FovAdjusted — Saturating
pub mod fov_adjusted;
/// [23] HeuristicDistanceEstimated — Mask
pub mod heuristic_distance_estimated;
/// [1] InputAdmitted — Mask
pub mod input_admitted;
/// [16] InventoryItemChanged — Bitset
pub mod inventory_item_changed;
/// [52] LagCompensationApplied — Saturating
pub mod lag_compensation_applied;
/// [33] LevelGateEvaluated — Mask
pub mod level_gate_evaluated;
/// [42] LookTargetWeighted — Mask
pub mod look_target_weighted;
/// [18] MasteryMomentDetected — Bitset
pub mod mastery_moment_detected;
/// [71] MovementLegalityChecked — Mask
pub mod movement_legality_checked;
/// [38] NarrativeBranchSelected — Mask
pub mod narrative_branch_selected;
/// [25] NavStateAdvanced — Dfa
pub mod nav_state_advanced;
/// [26] NoiseValueSampled — Receipt
pub mod noise_value_sampled;
/// [20] NpsPromptGated — Mask
pub mod nps_prompt_gated;
/// [59] NpsScoreBounded — Lut
pub mod nps_score_bounded;
/// [4] ObjectSpawned — Lut
pub mod object_spawned;
/// [68] ObservationClassSelected — Lut
pub mod observation_class_selected;
/// [6] OcelEventLinked — Mask
pub mod ocel_event_linked;
/// [7] OtelSpanEmitted — Lut
pub mod otel_span_emitted;
/// [53] PacketPriorityEvaluated — Mask
pub mod packet_priority_evaluated;
/// [24] PathCostBounded — Lut
pub mod path_cost_bounded;
/// [21] PathNodeExpanded — Mask
pub mod path_node_expanded;
/// [64] PayloadSizeBounded — Mask
pub mod payload_size_bounded;
/// [10] PhysicsValueRendered — Lut
pub mod physics_value_rendered;
/// [67] PolicyActionSelected — Mask
pub mod policy_action_selected;
/// [54] PredictionErrorBounded — Lut
pub mod prediction_error_bounded;
/// [12] ProjectileAdvanced — Saturating
pub mod projectile_advanced;
/// [34] PurchaseAdmitted — Dfa
pub mod purchase_admitted;
/// [60] QualityGateEvaluated — Dfa
pub mod quality_gate_evaluated;
/// [17] QuestStepAdvanced — Dfa
pub mod quest_step_advanced;
/// [9] ReceiptAppended — Receipt
pub mod receipt_appended;
/// [8] ReplayFrameRecorded — Receipt
pub mod replay_frame_recorded;
/// [72] ResourceBoundChecked — Mask
pub mod resource_bound_checked;
/// [66] RewardSignalClamped — Saturating
pub mod reward_signal_clamped;
/// [35] RewardTierSelected — Bitset
pub mod reward_tier_selected;
/// [11] SemanticLodSelected — Lut
pub mod semantic_lod_selected;
/// [19] ShareArtifactGenerated — Receipt
pub mod share_artifact_generated;
/// [56] SigmaLevelComputed — Mask
pub mod sigma_level_computed;
/// [29] SpawnWeightEvaluated — Mask
pub mod spawn_weight_evaluated;
/// [15] StatusEffectTicked — Bitset
pub mod status_effect_ticked;
/// [55] SyncStateAdmitted — Dfa
pub mod sync_state_admitted;
/// [28] TerrainHeightQuantized — Lut
pub mod terrain_height_quantized;
/// [51] TickDeltaBounded — Lut
pub mod tick_delta_bounded;
/// [27] TileVariantSelected — Lut
pub mod tile_variant_selected;
/// [75] TransitionLegalityChecked — Dfa
pub mod transition_legality_checked;
/// [47] VolumeClamped — Lut
pub mod volume_clamped;
/// [22] WaypointReached — Saturating
pub mod waypoint_reached;
/// [32] XpThresholdCrossed — Mask
pub mod xp_threshold_crossed;

// --- Kernel re-exports ---

pub use aabb_collision_resolved::aabb_collision_resolved;
pub use action_mask_applied::action_mask_applied;
pub use action_rate_bounded::action_rate_bounded;
pub use adapter_priority_ranked::adapter_priority_ranked;
pub use ai_action_selected::ai_action_selected;
pub use audio_distance_attenuated::audio_distance_attenuated;
pub use audio_fade_applied::audio_fade_applied;
pub use audio_priority_selected::audio_priority_selected;
pub use audio_trigger_evaluated::audio_trigger_evaluated;
pub use biome_class_selected::biome_class_selected;
pub use bridge_state_transitioned::bridge_state_transitioned;
pub use camera_distance_clamped::camera_distance_clamped;
pub use camera_follow_lerped::camera_follow_lerped;
pub use camera_shake_applied::camera_shake_applied;
pub use capability_flag_evaluated::capability_flag_evaluated;
pub use choice_weight_selected::choice_weight_selected;
pub use command_opcode_encoded::command_opcode_encoded;
pub use condition_flag_evaluated::condition_flag_evaluated;
pub use cooldown_legality_checked::cooldown_legality_checked;
pub use ctq_threshold_evaluated::ctq_threshold_evaluated;
pub use currency_delta_applied::currency_delta_applied;
pub use damage_applied::damage_applied;
pub use defect_rate_quantized::defect_rate_quantized;
pub use dialogue_cooldown_bounded::dialogue_cooldown_bounded;
pub use dialogue_node_advanced::dialogue_node_advanced;
pub use entity_state_transitioned::entity_state_transitioned;
pub use episode_return_bounded::episode_return_bounded;
pub use fixed_tick_advanced::fixed_tick_advanced;
pub use fov_adjusted::fov_adjusted;
pub use heuristic_distance_estimated::heuristic_distance_estimated;
pub use input_admitted::input_admitted;
pub use inventory_item_changed::inventory_item_changed;
pub use lag_compensation_applied::lag_compensation_applied;
pub use level_gate_evaluated::level_gate_evaluated;
pub use look_target_weighted::look_target_weighted;
pub use mastery_moment_detected::mastery_moment_detected;
pub use movement_legality_checked::movement_legality_checked;
pub use narrative_branch_selected::narrative_branch_selected;
pub use nav_state_advanced::nav_state_advanced;
pub use noise_value_sampled::noise_value_sampled;
pub use nps_prompt_gated::nps_prompt_gated;
pub use nps_score_bounded::nps_score_bounded;
pub use object_spawned::object_spawned;
pub use observation_class_selected::observation_class_selected;
pub use ocel_event_linked::ocel_event_linked;
pub use otel_span_emitted::otel_span_emitted;
pub use packet_priority_evaluated::packet_priority_evaluated;
pub use path_cost_bounded::path_cost_bounded;
pub use path_node_expanded::path_node_expanded;
pub use payload_size_bounded::payload_size_bounded;
pub use physics_value_rendered::physics_value_rendered;
pub use policy_action_selected::policy_action_selected;
pub use prediction_error_bounded::prediction_error_bounded;
pub use projectile_advanced::projectile_advanced;
pub use purchase_admitted::purchase_admitted;
pub use quality_gate_evaluated::quality_gate_evaluated;
pub use quest_step_advanced::quest_step_advanced;
pub use receipt_appended::receipt_appended;
pub use replay_frame_recorded::replay_frame_recorded;
pub use resource_bound_checked::resource_bound_checked;
pub use reward_signal_clamped::reward_signal_clamped;
pub use reward_tier_selected::reward_tier_selected;
pub use semantic_lod_selected::semantic_lod_selected;
pub use share_artifact_generated::share_artifact_generated;
pub use sigma_level_computed::sigma_level_computed;
pub use spawn_weight_evaluated::spawn_weight_evaluated;
pub use status_effect_ticked::status_effect_ticked;
pub use sync_state_admitted::sync_state_admitted;
pub use terrain_height_quantized::terrain_height_quantized;
pub use tick_delta_bounded::tick_delta_bounded;
pub use tile_variant_selected::tile_variant_selected;
pub use transition_legality_checked::transition_legality_checked;
pub use volume_clamped::volume_clamped;
pub use waypoint_reached::waypoint_reached;
pub use xp_threshold_crossed::xp_threshold_crossed;

/// The standard admission contract used by every pattern.
const STD_ADMISSION: AdmissionRule = AdmissionRule {
    required_status: status::ADMITTED,
    refusal_status: status::REFUSED,
};

/// The catalog of all generated patterns as data. Iterated by [`crate::verify`].
pub static PATTERN_REGISTRY: &[PatternSpec] = &[
    PatternSpec {
        id: PatternId(1),
        name: "input_admitted",
        lowering: LoweringKind::Mask,
        state_card: 9,
        event: EventKind {
            code: 2,
            name: "InputAdmitted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 2,
    },
    PatternSpec {
        id: PatternId(2),
        name: "fixed_tick_advanced",
        lowering: LoweringKind::Saturating,
        state_card: 64,
        event: EventKind {
            code: 1,
            name: "FixedTickAdvanced",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 1,
    },
    PatternSpec {
        id: PatternId(3),
        name: "entity_state_transitioned",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 16,
            name: "EntityStateTransitioned",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 16,
    },
    PatternSpec {
        id: PatternId(4),
        name: "object_spawned",
        lowering: LoweringKind::Lut,
        state_card: 6,
        event: EventKind {
            code: 18,
            name: "ObjectSpawned",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 18,
    },
    PatternSpec {
        id: PatternId(5),
        name: "aabb_collision_resolved",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 17,
            name: "AabbCollisionResolved",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 17,
    },
    PatternSpec {
        id: PatternId(6),
        name: "ocel_event_linked",
        lowering: LoweringKind::Mask,
        state_card: 32,
        event: EventKind {
            code: 33,
            name: "OcelEventLinked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 33,
    },
    PatternSpec {
        id: PatternId(7),
        name: "otel_span_emitted",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 34,
            name: "OtelSpanEmitted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 34,
    },
    PatternSpec {
        id: PatternId(8),
        name: "replay_frame_recorded",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 35,
            name: "ReplayFrameRecorded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 35,
    },
    PatternSpec {
        id: PatternId(9),
        name: "receipt_appended",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 32,
            name: "ReceiptAppended",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 3,
    },
    PatternSpec {
        id: PatternId(10),
        name: "physics_value_rendered",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 48,
            name: "PhysicsValueRendered",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 48,
    },
    PatternSpec {
        id: PatternId(11),
        name: "semantic_lod_selected",
        lowering: LoweringKind::Lut,
        state_card: 7,
        event: EventKind {
            code: 49,
            name: "SemanticLodSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 49,
    },
    PatternSpec {
        id: PatternId(12),
        name: "projectile_advanced",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 50,
            name: "ProjectileAdvanced",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 50,
    },
    PatternSpec {
        id: PatternId(13),
        name: "ai_action_selected",
        lowering: LoweringKind::Mask,
        state_card: 4,
        event: EventKind {
            code: 64,
            name: "AiActionSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 64,
    },
    PatternSpec {
        id: PatternId(14),
        name: "damage_applied",
        lowering: LoweringKind::Saturating,
        state_card: 16,
        event: EventKind {
            code: 66,
            name: "DamageApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 66,
    },
    PatternSpec {
        id: PatternId(15),
        name: "status_effect_ticked",
        lowering: LoweringKind::Bitset,
        state_card: 16,
        event: EventKind {
            code: 67,
            name: "StatusEffectTicked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 67,
    },
    PatternSpec {
        id: PatternId(16),
        name: "inventory_item_changed",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 68,
            name: "InventoryItemChanged",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 68,
    },
    PatternSpec {
        id: PatternId(17),
        name: "quest_step_advanced",
        lowering: LoweringKind::Dfa,
        state_card: 5,
        event: EventKind {
            code: 69,
            name: "QuestStepAdvanced",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 69,
    },
    PatternSpec {
        id: PatternId(18),
        name: "mastery_moment_detected",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 80,
            name: "MasteryMomentDetected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 80,
    },
    PatternSpec {
        id: PatternId(19),
        name: "share_artifact_generated",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 81,
            name: "ShareArtifactGenerated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 81,
    },
    PatternSpec {
        id: PatternId(20),
        name: "nps_prompt_gated",
        lowering: LoweringKind::Mask,
        state_card: 9,
        event: EventKind {
            code: 82,
            name: "NpsPromptGated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 82,
    },
    PatternSpec {
        id: PatternId(21),
        name: "path_node_expanded",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 83,
            name: "PathNodeExpanded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 83,
    },
    PatternSpec {
        id: PatternId(22),
        name: "waypoint_reached",
        lowering: LoweringKind::Saturating,
        state_card: 16,
        event: EventKind {
            code: 84,
            name: "WaypointReached",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 84,
    },
    PatternSpec {
        id: PatternId(23),
        name: "heuristic_distance_estimated",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 85,
            name: "HeuristicDistanceEstimated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 85,
    },
    PatternSpec {
        id: PatternId(24),
        name: "path_cost_bounded",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 86,
            name: "PathCostBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 86,
    },
    PatternSpec {
        id: PatternId(25),
        name: "nav_state_advanced",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 87,
            name: "NavStateAdvanced",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 87,
    },
    PatternSpec {
        id: PatternId(26),
        name: "noise_value_sampled",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 88,
            name: "NoiseValueSampled",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 88,
    },
    PatternSpec {
        id: PatternId(27),
        name: "tile_variant_selected",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 89,
            name: "TileVariantSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 89,
    },
    PatternSpec {
        id: PatternId(28),
        name: "terrain_height_quantized",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 90,
            name: "TerrainHeightQuantized",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 90,
    },
    PatternSpec {
        id: PatternId(29),
        name: "spawn_weight_evaluated",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 91,
            name: "SpawnWeightEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 91,
    },
    PatternSpec {
        id: PatternId(30),
        name: "biome_class_selected",
        lowering: LoweringKind::Bitset,
        state_card: 16,
        event: EventKind {
            code: 92,
            name: "BiomeClassSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 92,
    },
    PatternSpec {
        id: PatternId(31),
        name: "currency_delta_applied",
        lowering: LoweringKind::Saturating,
        state_card: 64,
        event: EventKind {
            code: 93,
            name: "CurrencyDeltaApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 93,
    },
    PatternSpec {
        id: PatternId(32),
        name: "xp_threshold_crossed",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 94,
            name: "XpThresholdCrossed",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 94,
    },
    PatternSpec {
        id: PatternId(33),
        name: "level_gate_evaluated",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 95,
            name: "LevelGateEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 95,
    },
    PatternSpec {
        id: PatternId(34),
        name: "purchase_admitted",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 96,
            name: "PurchaseAdmitted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 96,
    },
    PatternSpec {
        id: PatternId(35),
        name: "reward_tier_selected",
        lowering: LoweringKind::Bitset,
        state_card: 16,
        event: EventKind {
            code: 97,
            name: "RewardTierSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 97,
    },
    PatternSpec {
        id: PatternId(36),
        name: "dialogue_node_advanced",
        lowering: LoweringKind::Dfa,
        state_card: 5,
        event: EventKind {
            code: 98,
            name: "DialogueNodeAdvanced",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 98,
    },
    PatternSpec {
        id: PatternId(37),
        name: "condition_flag_evaluated",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 99,
            name: "ConditionFlagEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 99,
    },
    PatternSpec {
        id: PatternId(38),
        name: "narrative_branch_selected",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 100,
            name: "NarrativeBranchSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 100,
    },
    PatternSpec {
        id: PatternId(39),
        name: "dialogue_cooldown_bounded",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 101,
            name: "DialogueCooldownBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 101,
    },
    PatternSpec {
        id: PatternId(40),
        name: "choice_weight_selected",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 102,
            name: "ChoiceWeightSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 102,
    },
    PatternSpec {
        id: PatternId(41),
        name: "camera_distance_clamped",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 103,
            name: "CameraDistanceClamped",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 103,
    },
    PatternSpec {
        id: PatternId(42),
        name: "look_target_weighted",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 104,
            name: "LookTargetWeighted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 104,
    },
    PatternSpec {
        id: PatternId(43),
        name: "fov_adjusted",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 105,
            name: "FovAdjusted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 105,
    },
    PatternSpec {
        id: PatternId(44),
        name: "camera_shake_applied",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 106,
            name: "CameraShakeApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 106,
    },
    PatternSpec {
        id: PatternId(45),
        name: "camera_follow_lerped",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 107,
            name: "CameraFollowLerped",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 107,
    },
    PatternSpec {
        id: PatternId(46),
        name: "audio_priority_selected",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 108,
            name: "AudioPrioritySelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 108,
    },
    PatternSpec {
        id: PatternId(47),
        name: "volume_clamped",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 109,
            name: "VolumeClamped",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 109,
    },
    PatternSpec {
        id: PatternId(48),
        name: "audio_fade_applied",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 110,
            name: "AudioFadeApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 110,
    },
    PatternSpec {
        id: PatternId(49),
        name: "audio_trigger_evaluated",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 111,
            name: "AudioTriggerEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 111,
    },
    PatternSpec {
        id: PatternId(50),
        name: "audio_distance_attenuated",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 112,
            name: "AudioDistanceAttenuated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 112,
    },
    PatternSpec {
        id: PatternId(51),
        name: "tick_delta_bounded",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 113,
            name: "TickDeltaBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 113,
    },
    PatternSpec {
        id: PatternId(52),
        name: "lag_compensation_applied",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 114,
            name: "LagCompensationApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 114,
    },
    PatternSpec {
        id: PatternId(53),
        name: "packet_priority_evaluated",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 115,
            name: "PacketPriorityEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 115,
    },
    PatternSpec {
        id: PatternId(54),
        name: "prediction_error_bounded",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 116,
            name: "PredictionErrorBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 116,
    },
    PatternSpec {
        id: PatternId(55),
        name: "sync_state_admitted",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 117,
            name: "SyncStateAdmitted",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 117,
    },
    PatternSpec {
        id: PatternId(56),
        name: "sigma_level_computed",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 118,
            name: "SigmaLevelComputed",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 118,
    },
    PatternSpec {
        id: PatternId(57),
        name: "defect_rate_quantized",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 119,
            name: "DefectRateQuantized",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 119,
    },
    PatternSpec {
        id: PatternId(58),
        name: "ctq_threshold_evaluated",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 120,
            name: "CtqThresholdEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 120,
    },
    PatternSpec {
        id: PatternId(59),
        name: "nps_score_bounded",
        lowering: LoweringKind::Lut,
        state_card: 11,
        event: EventKind {
            code: 121,
            name: "NpsScoreBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 121,
    },
    PatternSpec {
        id: PatternId(60),
        name: "quality_gate_evaluated",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 122,
            name: "QualityGateEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 122,
    },
    PatternSpec {
        id: PatternId(61),
        name: "command_opcode_encoded",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 123,
            name: "CommandOpcodeEncoded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 123,
    },
    PatternSpec {
        id: PatternId(62),
        name: "capability_flag_evaluated",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 124,
            name: "CapabilityFlagEvaluated",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 124,
    },
    PatternSpec {
        id: PatternId(63),
        name: "bridge_state_transitioned",
        lowering: LoweringKind::Dfa,
        state_card: 5,
        event: EventKind {
            code: 125,
            name: "BridgeStateTransitioned",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 125,
    },
    PatternSpec {
        id: PatternId(64),
        name: "payload_size_bounded",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 126,
            name: "PayloadSizeBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 126,
    },
    PatternSpec {
        id: PatternId(65),
        name: "adapter_priority_ranked",
        lowering: LoweringKind::Network,
        state_card: 8,
        event: EventKind {
            code: 127,
            name: "AdapterPriorityRanked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 127,
    },
    PatternSpec {
        id: PatternId(66),
        name: "reward_signal_clamped",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 128,
            name: "RewardSignalClamped",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 128,
    },
    PatternSpec {
        id: PatternId(67),
        name: "policy_action_selected",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 129,
            name: "PolicyActionSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 129,
    },
    PatternSpec {
        id: PatternId(68),
        name: "observation_class_selected",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 130,
            name: "ObservationClassSelected",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 130,
    },
    PatternSpec {
        id: PatternId(69),
        name: "action_mask_applied",
        lowering: LoweringKind::Mask,
        state_card: 32,
        event: EventKind {
            code: 131,
            name: "ActionMaskApplied",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 131,
    },
    PatternSpec {
        id: PatternId(70),
        name: "episode_return_bounded",
        lowering: LoweringKind::Saturating,
        state_card: 64,
        event: EventKind {
            code: 132,
            name: "EpisodeReturnBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 132,
    },
    PatternSpec {
        id: PatternId(71),
        name: "movement_legality_checked",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 133,
            name: "MovementLegalityChecked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 133,
    },
    PatternSpec {
        id: PatternId(72),
        name: "resource_bound_checked",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 134,
            name: "ResourceBoundChecked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 134,
    },
    PatternSpec {
        id: PatternId(73),
        name: "cooldown_legality_checked",
        lowering: LoweringKind::Bitset,
        state_card: 2,
        event: EventKind {
            code: 135,
            name: "CooldownLegalityChecked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 135,
    },
    PatternSpec {
        id: PatternId(74),
        name: "action_rate_bounded",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 136,
            name: "ActionRateBounded",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 136,
    },
    PatternSpec {
        id: PatternId(75),
        name: "transition_legality_checked",
        lowering: LoweringKind::Dfa,
        state_card: 5,
        event: EventKind {
            code: 137,
            name: "TransitionLegalityChecked",
        },
        objects: &[],
        admission: STD_ADMISSION,
        otel_span: 137,
    },
];
