// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (movement_legality_checked)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: MovementLegalityChecked
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Authority: legality spec — a move is admissible iff the displacement from the current
//! position to the proposed position does not exceed the actor's max speed; larger jumps
//! are teleport cheats and are refused. Lowered onto [`bcinr_logic::mask::lt_mask_u32`].

use bcinr_logic::mask::{abs_i32, lt_mask_u32};

/// MovementLegalityChecked kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current position.
/// - `input`: bits[0..16] = proposed position, bits[16..32] = max speed.
///
/// Returns a verdict bitmask: `0` = ADMITTED (legal move), nonzero = refusal.
/// - bit0 = teleport (`|proposed - current| > max_speed`).
#[inline]
#[must_use]
pub fn movement_legality_checked(state: u64, input: u64) -> u64 {
    let cur = (state & 0xFFFF) as i32;
    let prop = (input & 0xFFFF) as i32;
    let max = ((input >> 16) & 0xFFFF) as u32;
    let delta = abs_i32(prop - cur) as u32;
    u64::from(lt_mask_u32(max, delta)) & 1
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn movement_legality_checked_reference(state: u64, input: u64) -> u64 {
        let cur = (state & 0xFFFF) as i32;
        let prop = (input & 0xFFFF) as i32;
        let max = ((input >> 16) & 0xFFFF) as u32;
        if (prop - cur).unsigned_abs() > max {
            1
        } else {
            0
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !movement_legality_checked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        movement_legality_checked_reference(s, i) ^ 0xFFFF
    }

    // --- Two-sided breed battery: legality corpus + weakened detector ---
    fn must_admit() -> &'static [(u64, u64)] {
        // (current_pos, proposed_pos | max_speed << 16)
        &[
            (100, 100 | (5 << 16)),  // no movement, slack budget
            (100, 105 | (5 << 16)),  // exactly at the speed limit
            (200, 195 | (10 << 16)), // backward move within budget
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (100, 200 | (5 << 16)), // forward teleport
            (200, 100 | (5 << 16)), // backward teleport
            (0, 5000 | (10 << 16)), // long-range blink
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Deliberately broken: the teleport check is deleted, so every move is admitted.
        let _ = (s, i);
        0
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                movement_legality_checked_reference(s, i),
                movement_legality_checked(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = movement_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = movement_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            movement_legality_checked(0, 0),
            movement_legality_checked_reference(0, 0)
        );
        assert_eq!(
            movement_legality_checked(0xFFFF, 0xFFFF_FFFF),
            movement_legality_checked_reference(0xFFFF, 0xFFFF_FFFF)
        );
        // Displacement exactly equal to the budget is legal.
        assert_eq!(movement_legality_checked(100, 105 | (5 << 16)), 0);
        // One beyond the budget is a teleport.
        assert_eq!(movement_legality_checked(100, 106 | (5 << 16)), 1);
    }

    #[test]
    fn two_sided_admit() {
        for &(s, i) in must_admit() {
            assert_eq!(
                movement_legality_checked(s, i),
                0,
                "legal case must be admitted"
            );
        }
    }
    #[test]
    fn two_sided_refuse() {
        for &(s, i) in must_refuse() {
            assert_ne!(
                movement_legality_checked(s, i),
                0,
                "cheat case must be refused"
            );
        }
    }
    #[test]
    fn weakened_fails_corpus() {
        assert!(
            must_refuse().iter().any(|&(s, i)| weakened(s, i) == 0),
            "a weakened detector must admit >=1 cheat from the corpus"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_movement_legality_checked(c: &mut Criterion) {
        c.bench_function("movement_legality_checked", |b| {
            b.iter(|| {
                black_box(movement_legality_checked(
                    black_box(100),
                    black_box(105 | (5 << 16)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: verdict bit0 is set iff |proposed - current| exceeds max_speed.
// Hoare-logic Verification Line 2: a displacement equal to max_speed is admitted (boundary inclusive).
