// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (narrative_branch_selected)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: NarrativeBranchSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select one of three narrative branches (0, 1, 2) based on which of three weighted
//! conditions has the highest weight. Weights are 16-bit values packed in input.
//! Ties resolve to the lowest-index branch (strict `<` for replacement).

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// NarrativeBranchSelected kernel. Packed-u64 ABI:
/// - `state`: unused (reserved).
/// - `input`: bits[0..16] = weight_a, bits[16..32] = weight_b, bits[32..48] = weight_c.
///
/// Returns: bits[0..8] = selected branch (0, 1, or 2); bits[8..24] = winning weight.
#[inline]
#[must_use]
pub fn narrative_branch_selected(state: u64, input: u64) -> u64 {
    let _ = state;
    let w_a = (input & 0xFFFF) as u32;
    let w_b = ((input >> 16) & 0xFFFF) as u32;
    let w_c = ((input >> 32) & 0xFFFF) as u32;

    let mut best_val = w_a;
    let mut best_idx = 0u32;

    // Branch 1 wins when best_val < w_b (strictly), keeping the first max on ties.
    let m1 = lt_mask_u32(best_val, w_b);
    best_idx = select_u32(m1, 1, best_idx);
    best_val = select_u32(m1, w_b, best_val);

    // Branch 2 wins when best_val < w_c (strictly), keeping the first max on ties.
    let m2 = lt_mask_u32(best_val, w_c);
    best_idx = select_u32(m2, 2, best_idx);
    best_val = select_u32(m2, w_c, best_val);

    (best_idx as u64) | ((best_val as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn narrative_branch_selected_reference(_state: u64, input: u64) -> u64 {
        let w_a = (input & 0xFFFF) as u32;
        let w_b = ((input >> 16) & 0xFFFF) as u32;
        let w_c = ((input >> 32) & 0xFFFF) as u32;
        let weights = [w_a, w_b, w_c];
        let mut best_idx = 0u32;
        let mut best_val = weights[0];
        for (i, &v) in weights.iter().enumerate().skip(1) {
            if v > best_val {
                best_val = v;
                best_idx = i as u32;
            }
        }
        (best_idx as u64) | ((best_val as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !narrative_branch_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        narrative_branch_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(narrative_branch_selected_reference(s, i), narrative_branch_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = narrative_branch_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = narrative_branch_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // (5, 9, 3) -> branch=1, weight=9
        let i1 = 5u64 | (9u64 << 16) | (3u64 << 32);
        let out1 = narrative_branch_selected(0, i1);
        assert_eq!(out1 & 0xFF, 1);
        assert_eq!((out1 >> 8) & 0xFFFF, 9);
        // (9, 5, 3) -> branch=0, weight=9
        let i2 = 9u64 | (5u64 << 16) | (3u64 << 32);
        let out2 = narrative_branch_selected(0, i2);
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFFFF, 9);
        // (3, 3, 9) -> branch=2, weight=9
        let i3 = 3u64 | (3u64 << 16) | (9u64 << 32);
        let out3 = narrative_branch_selected(0, i3);
        assert_eq!(out3 & 0xFF, 2);
        assert_eq!((out3 >> 8) & 0xFFFF, 9);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // Distinct maxima: (5,9,3) -> branch 1; (9,5,3) -> branch 0.
        &[
            (0, 5u64 | (9u64 << 16) | (3u64 << 32)),
            (0, 9u64 | (5u64 << 16) | (3u64 << 32)),
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Ties: the strict-`<` rule must keep the lowest-index branch.
        &[
            (0, 9u64 | (9u64 << 16) | (3u64 << 32)),
            (0, 4u64 | (4u64 << 16) | (4u64 << 32)),
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: replaces on `>=`, so ties drift to the highest index.
        let _ = s;
        let w_a = (i & 0xFFFF) as u32;
        let w_b = ((i >> 16) & 0xFFFF) as u32;
        let w_c = ((i >> 32) & 0xFFFF) as u32;
        let mut best_val = w_a;
        let mut best_idx = 0u32;
        if w_b >= best_val {
            best_val = w_b;
            best_idx = 1;
        }
        if w_c >= best_val {
            best_val = w_c;
            best_idx = 2;
        }
        (best_idx as u64) | ((best_val as u64) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                narrative_branch_selected(s, i),
                narrative_branch_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                narrative_branch_selected(s, i),
                narrative_branch_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != narrative_branch_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 0;
    const I: u64 = 5u64 | (9u64 << 16) | (3u64 << 32);
    pub fn bench_narrative_branch_selected(c: &mut Criterion) {
        c.bench_function("narrative_branch_selected", |b| {
            b.iter(|| black_box(narrative_branch_selected(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: the chosen weight equals the strict maximum of the three candidates.
// Hoare-logic Verification Line 2: ties resolve to the lowest-index branch (strict < for replacement preserves first maximum).
