// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (nav_state_advanced)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: NavStateAdvanced
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a 4-state navigation FSM (IDLE/MOVING/ARRIVED/BLOCKED) via branchless DFA table lookup.

use bcinr_logic::dfa::dfa_advance;

// Nav FSM states
const IDLE: usize = 0;
const MOVING: usize = 1;
const ARRIVED: usize = 2;
const BLOCKED: usize = 3;

// Nav FSM symbols (used as doc aliases; suppress dead_code for standalone file)
#[allow(dead_code)]
const STOP: u8 = 0;
#[allow(dead_code)]
const MOVE: u8 = 1;
#[allow(dead_code)]
const ARRIVE: u8 = 2;
#[allow(dead_code)]
const OBSTACLE: u8 = 3;

// Transition table: TABLE[state * 4 + symbol] = next_state
// Rows: IDLE=0, MOVING=1, ARRIVED=2, BLOCKED=3
// Cols: STOP=0, MOVE=1, ARRIVE=2, OBSTACLE=3
#[rustfmt::skip]
static NAV_TABLE: [usize; 16] = [
    // IDLE:    STOP->IDLE, MOVE->MOVING, ARRIVE->IDLE,    OBSTACLE->IDLE
    IDLE,    MOVING,  IDLE,    IDLE,
    // MOVING:  STOP->IDLE, MOVE->MOVING, ARRIVE->ARRIVED, OBSTACLE->BLOCKED
    IDLE,    MOVING,  ARRIVED, BLOCKED,
    // ARRIVED: STOP->ARRIVED, MOVE->MOVING, ARRIVE->ARRIVED, OBSTACLE->ARRIVED
    ARRIVED, MOVING,  ARRIVED, ARRIVED,
    // BLOCKED: STOP->IDLE,  MOVE->MOVING, ARRIVE->IDLE,   OBSTACLE->IDLE
    IDLE,    MOVING,  IDLE,    IDLE,
];

/// NavStateAdvanced kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current nav state (0=IDLE, 1=MOVING, 2=ARRIVED, 3=BLOCKED)
/// - `input`: bits[0..8] = event symbol (0=STOP, 1=MOVE, 2=ARRIVE, 3=OBSTACLE)
///
/// Returns bits[0..8] = next nav state.
#[inline]
#[must_use]
pub fn nav_state_advanced(state: u64, input: u64) -> u64 {
    let current = (state & 0xFF) as usize;
    let symbol = (input & 0xFF) as u8;
    dfa_advance(current, symbol, &NAV_TABLE, 4) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn nav_state_advanced_reference(state: u64, input: u64) -> u64 {
        let current = (state & 0xFF) as usize;
        let symbol = (input & 0xFF) as usize;
        // Clamp to valid state/symbol range
        let s = current.min(3);
        let sym = symbol.min(3);
        let next = match (s, sym) {
            (0, 0) => 0, // IDLE + STOP -> IDLE
            (0, 1) => 1, // IDLE + MOVE -> MOVING
            (0, 2) => 0, // IDLE + ARRIVE -> IDLE
            (0, 3) => 0, // IDLE + OBSTACLE -> IDLE
            (1, 0) => 0, // MOVING + STOP -> IDLE
            (1, 1) => 1, // MOVING + MOVE -> MOVING
            (1, 2) => 2, // MOVING + ARRIVE -> ARRIVED
            (1, 3) => 3, // MOVING + OBSTACLE -> BLOCKED
            (2, 0) => 2, // ARRIVED + STOP -> ARRIVED
            (2, 1) => 1, // ARRIVED + MOVE -> MOVING
            (2, 2) => 2, // ARRIVED + ARRIVE -> ARRIVED
            (2, 3) => 2, // ARRIVED + OBSTACLE -> ARRIVED
            (3, 0) => 0, // BLOCKED + STOP -> IDLE
            (3, 1) => 1, // BLOCKED + MOVE -> MOVING
            (3, 2) => 0, // BLOCKED + ARRIVE -> IDLE
            (3, 3) => 0, // BLOCKED + OBSTACLE -> IDLE
            _ => s,
        };
        next as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !nav_state_advanced_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        nav_state_advanced_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        // Test only valid state/symbol ranges (0..3 each) for equivalence
        #[test] fn equivalence(s in 0u64..4, i in 0u64..4) {
            prop_assert_eq!(nav_state_advanced_reference(s, i), nav_state_advanced(s, i));
        }
        #[test] fn cf1(s in 0u64..4, i in 0u64..4) {
            let r = nav_state_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test] fn cf3(s in 0u64..4, i in 0u64..4) {
            let r = nav_state_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // IDLE + MOVE -> MOVING (0+1=1)
        assert_eq!(nav_state_advanced(0, 1), 1);
        // MOVING + ARRIVE -> ARRIVED (1+2=2)
        assert_eq!(nav_state_advanced(1, 2), 2);
        // MOVING + OBSTACLE -> BLOCKED (1+3=3)
        assert_eq!(nav_state_advanced(1, 3), 3);
        // BLOCKED + MOVE -> MOVING (3+1=1)
        assert_eq!(nav_state_advanced(3, 1), 1);
    }

    // --- two-sided breed-rigor battery ---
    // DFA framing: admit = legal forward transitions; refuse = inputs that drive
    // the machine into the BLOCKED sink (or sit in it); weakened = a transition
    // table that never sinks (obstacles ignored).

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // IDLE + MOVE -> MOVING.
            (IDLE as u64, MOVE as u64),
            // MOVING + ARRIVE -> ARRIVED.
            (MOVING as u64, ARRIVE as u64),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // MOVING + OBSTACLE must route into the BLOCKED sink.
            (MOVING as u64, OBSTACLE as u64),
            // ARRIVED + OBSTACLE holds in place (no spurious sink) — sink-adjacent.
            (ARRIVED as u64, OBSTACLE as u64),
        ]
    }

    // Weakened: a table that never sinks — MOVING + OBSTACLE stays MOVING instead
    // of transitioning to BLOCKED, so the obstacle/sink bound disappears.
    fn weakened(s: u64, i: u64) -> u64 {
        #[rustfmt::skip]
        static NO_SINK_TABLE: [usize; 16] = [
            IDLE,    MOVING,  IDLE,    IDLE,
            // BUG: OBSTACLE no longer sinks to BLOCKED — it keeps MOVING.
            IDLE,    MOVING,  ARRIVED, MOVING,
            ARRIVED, MOVING,  ARRIVED, ARRIVED,
            IDLE,    MOVING,  IDLE,    IDLE,
        ];
        let current = (s & 0xFF) as usize;
        let symbol = (i & 0xFF) as u8;
        dfa_advance(current, symbol, &NO_SINK_TABLE, 4) as u64
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(nav_state_advanced(s, i), nav_state_advanced_reference(s, i));
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(nav_state_advanced(s, i), nav_state_advanced_reference(s, i));
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != nav_state_advanced_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_nav_state_advanced(c: &mut Criterion) {
        c.bench_function("nav_state_advanced", |b| {
            b.iter(|| black_box(nav_state_advanced(black_box(1), black_box(2))))
        });
    }
}

// Hoare-logic Verification Line 1: dfa_advance indexes NAV_TABLE at state*4+symbol with bounds-safe masking — no branch.
// Hoare-logic Verification Line 2: transition table encodes all 16 (state, symbol) pairs; out-of-range inputs clamp to table bounds via dfa_advance masking.
