// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (nps_score_bounded)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: NpsScoreBounded
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Normalize a raw NPS response score (0..=10) and classify as Detractor (0–6),
//! Passive (7–8), or Promoter (9–10) via branchless threshold comparisons.

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// NpsScoreBounded kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = raw NPS response score (0..=10).
/// - `input`: unused.
///
/// Returns: bits[0..8] = clamped score (0..=10);
///          bits[8..16] = category (0=Detractor 0–6, 1=Passive 7–8, 2=Promoter 9–10).
#[inline]
#[must_use]
pub fn nps_score_bounded(state: u64, input: u64) -> u64 {
    let _ = input;
    let score = (state & 0xFF) as u32;
    let clamped = clamp_u32(score, 0, 10);

    // Thresholds: Detractor <7, Passive 7..<9, Promoter >=9
    let below_7 = lt_mask_u32(clamped, 7);
    let below_9 = lt_mask_u32(clamped, 9);

    // category: 0 if <7, 1 if 7<=<9, 2 if >=9
    let cat_ge_7 = select_u32(below_9, 1, 2); // 1 if <9, else 2
    let category = select_u32(below_7, 0, cat_ge_7); // 0 if <7, else cat_ge_7

    (clamped as u64) | ((category as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn nps_score_bounded_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let score = (state & 0xFF) as u32;
        let c = score.min(10);
        let cat = if c < 7 {
            0u32
        } else if c < 9 {
            1
        } else {
            2
        };
        (c as u64) | ((cat as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !nps_score_bounded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        nps_score_bounded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(nps_score_bounded_reference(s, i), nps_score_bounded(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = nps_score_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = nps_score_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // score=3 -> clamped=3, category=0 (Detractor)
        let out = nps_score_bounded(3, 0);
        assert_eq!(out & 0xFF, 3);
        assert_eq!((out >> 8) & 0xFF, 0);
        // score=8 -> clamped=8, category=1 (Passive)
        let out2 = nps_score_bounded(8, 0);
        assert_eq!(out2 & 0xFF, 8);
        assert_eq!((out2 >> 8) & 0xFF, 1);
        // score=10 -> clamped=10, category=2 (Promoter)
        let out3 = nps_score_bounded(10, 0);
        assert_eq!(out3 & 0xFF, 10);
        assert_eq!((out3 >> 8) & 0xFF, 2);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: raw score already within [0, 10].
        &[(3, 0), (8, 0), (10, 0)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: score exceeds 10 and must be clamped before classification.
        &[(11, 0), (200, 0)]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: omits the clamp to [0, 10].
        let score = (s & 0xFF) as u32;
        let cat = if score < 7 {
            0u32
        } else if score < 9 {
            1
        } else {
            2
        };
        (score as u64) | ((cat as u64) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(nps_score_bounded(s, i), nps_score_bounded_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(nps_score_bounded(s, i), nps_score_bounded_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != nps_score_bounded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const S: u64 = 9;
    const I: u64 = 0;

    pub fn bench_nps_score_bounded(c: &mut Criterion) {
        c.bench_function("nps_score_bounded", |b| {
            b.iter(|| black_box(nps_score_bounded(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: clamped score is always in [0, 10] by clamp_u32 postcondition.
// Hoare-logic Verification Line 2: category is monotone-non-decreasing in clamped score, partitioned at 7 and 9.
