// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (nps_prompt_gated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: NpsPromptGated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Gate an NPS prompt branchlessly: if the player has hit the prompt-saturation cap, the
//! prompt is REFUSED; otherwise a readiness score below the bar is BLOCKED and a score at or
//! above it is ADMITTED. Decision is composed from ordered [`bcinr_logic::mask::select_u32`]s.

use crate::class::status;
use bcinr_logic::mask::{lt_mask_u32, nonzero_mask_u32, select_u32};

/// NpsPromptGated kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = readiness score, bits[16..24] = prompts already shown.
/// - `input`: bits[0..16] = readiness bar, bits[16..24] = saturation cap.
///
/// Returns a [`crate::class::status`] code in bits[0..8].
#[inline]
#[must_use]
pub fn nps_prompt_gated(state: u64, input: u64) -> u64 {
    let score = (state & 0xFFFF) as u32;
    let shown = ((state >> 16) & 0xFF) as u32;
    let bar = (input & 0xFFFF) as u32;
    let cap = ((input >> 16) & 0xFF) as u32;

    // Saturated when shown >= cap, i.e. NOT (shown < cap).
    let saturated = !lt_mask_u32(shown, cap);
    // Ready when score >= bar, i.e. NOT (score < bar).
    let below_bar = lt_mask_u32(score, bar);

    // Base: BLOCKED if below the bar, else ADMITTED.
    let base = select_u32(below_bar, status::BLOCKED as u32, status::ADMITTED as u32);
    // Saturation dominates -> REFUSED.
    let decision = select_u32(nonzero_mask_u32(saturated), status::REFUSED as u32, base);
    (decision as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn nps_prompt_gated_reference(state: u64, input: u64) -> u64 {
        let score = (state & 0xFFFF) as u32;
        let shown = ((state >> 16) & 0xFF) as u32;
        let bar = (input & 0xFFFF) as u32;
        let cap = ((input >> 16) & 0xFF) as u32;
        let decision = if shown >= cap {
            status::REFUSED
        } else if score < bar {
            status::BLOCKED
        } else {
            status::ADMITTED
        };
        (decision as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !nps_prompt_gated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        nps_prompt_gated_reference(s, i) ^ 0xFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(nps_prompt_gated_reference(s, i), nps_prompt_gated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = nps_prompt_gated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = nps_prompt_gated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // shown 3 >= cap 3 -> REFUSED.
        let st = 80u64 | (3u64 << 16);
        assert_eq!(
            nps_prompt_gated(st, 50 | (3u64 << 16)),
            status::REFUSED as u64
        );
        // score 80 >= bar 50, shown 0 < cap 3 -> ADMITTED.
        assert_eq!(
            nps_prompt_gated(80, 50 | (3u64 << 16)),
            status::ADMITTED as u64
        );
        // score 30 < bar 50 -> BLOCKED.
        assert_eq!(
            nps_prompt_gated(30, 50 | (3u64 << 16)),
            status::BLOCKED as u64
        );
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Below the bar, under cap -> BLOCKED.
            (30, 50 | (3u64 << 16)),
            // At/above the bar, under cap -> ADMITTED.
            (80, 50 | (3u64 << 16)),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Saturation dominates even a passing score -> REFUSED.
            (80u64 | (3u64 << 16), 50 | (3u64 << 16)),
            // Saturation dominates even a failing score -> REFUSED.
            (10u64 | (9u64 << 16), 50 | (3u64 << 16)),
        ]
    }

    // Weakened: drop the saturation-dominates-readiness rule; a saturated
    // player still falls through to the readiness decision.
    fn weakened(s: u64, i: u64) -> u64 {
        let score = (s & 0xFFFF) as u32;
        let bar = (i & 0xFFFF) as u32;
        let below_bar = lt_mask_u32(score, bar);
        // BUG: no REFUSED select on saturation — cap is ignored entirely.
        let base = select_u32(below_bar, status::BLOCKED as u32, status::ADMITTED as u32);
        (base as u64) & 0xFF
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(nps_prompt_gated(s, i), nps_prompt_gated_reference(s, i));
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(nps_prompt_gated(s, i), nps_prompt_gated_reference(s, i));
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != nps_prompt_gated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_nps_prompt_gated(c: &mut Criterion) {
        let input = 50u64 | (3u64 << 16);
        c.bench_function("nps_prompt_gated", |b| {
            b.iter(|| black_box(nps_prompt_gated(black_box(80), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: saturation refusal dominates the readiness decision.
// Hoare-logic Verification Line 2: every branch yields a valid status code (< COUNT).
