// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (object_spawned)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: ObjectSpawned
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Spawn an object: resolve a requested archetype to its initial packed state via a bounded
//! lookup table and stamp it with the next entity id (branchless table read).

use bcinr_logic::fix::clamp_u32;

/// Archetype -> initial packed state (e.g. default HP in bits[0..16]). 6 archetypes.
#[rustfmt::skip]
const ARCHETYPE_LUT: [u16; 6] = [
    0,    // 0: marker (no HP)
    10,   // 1: minion
    30,   // 2: soldier
    100,  // 3: elite
    250,  // 4: boss
    50,   // 5: turret
];

/// ObjectSpawned kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = next entity id counter.
/// - `input`: bits[0..8] = requested archetype (clamped into `[0, 6)`).
///
/// Returns: bits[0..16] = initial archetype state, bits[16..48] = assigned entity id.
#[inline]
#[must_use]
pub fn object_spawned(state: u64, input: u64) -> u64 {
    let next_id = state & 0xFFFF_FFFF;
    let arch = clamp_u32((input & 0xFF) as u32, 0, (ARCHETYPE_LUT.len() - 1) as u32) as usize;
    let init = ARCHETYPE_LUT[arch] as u64;
    init | (next_id << 16)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn object_spawned_reference(state: u64, input: u64) -> u64 {
        let next_id = state & 0xFFFF_FFFF;
        let arch = ((input & 0xFF) as usize).min(ARCHETYPE_LUT.len() - 1);
        let init = ARCHETYPE_LUT[arch] as u64;
        init | (next_id << 16)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !object_spawned_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        object_spawned_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(object_spawned_reference(s, i), object_spawned(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = object_spawned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = object_spawned_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // archetype 4 (boss) at id 7.
        let out = object_spawned(7, 4);
        assert_eq!(out & 0xFFFF, 250);
        assert_eq!((out >> 16) & 0xFFFF_FFFF, 7);
        // Out-of-range archetype clamps to last (turret).
        assert_eq!(object_spawned(0, 0xFF) & 0xFFFF, 50);
    }

    // Two-sided breed-rigor battery.
    // Legal: in-range archetype ids resolve to their table entry directly.
    fn must_admit() -> &'static [(u64, u64)] {
        &[(7, 4), (0, 1), (3, 5)]
    }
    // Extreme: out-of-range archetype ids the kernel must clamp into the table.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(0, 0xFF), (7, 8)]
    }
    // Weakened: omits the clamp, wrapping the index instead (a wrong, in-bounds branch).
    fn weakened(s: u64, i: u64) -> u64 {
        let next_id = s & 0xFFFF_FFFF;
        let arch = (i & 0xFF) as usize % ARCHETYPE_LUT.len();
        let init = ARCHETYPE_LUT[arch] as u64;
        init | (next_id << 16)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(object_spawned(s, i), object_spawned_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(object_spawned(s, i), object_spawned_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != object_spawned_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_object_spawned(c: &mut Criterion) {
        c.bench_function("object_spawned", |b| {
            b.iter(|| black_box(object_spawned(black_box(7), black_box(4))))
        });
    }
}

// Hoare-logic Verification Line 1: the archetype index is clamped before the table read.
// Hoare-logic Verification Line 2: every spawn carries the supplied entity id verbatim.
