// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (observation_class_selected)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: ObservationClassSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Discretize a continuous observation value into one of N bins. Computes
//! bin_index = observation / bin_width (integer division), then clamps to
//! [0, max_bins-1] using [`bcinr_logic::fix::clamp_u32`].

use bcinr_logic::fix::clamp_u32;

/// ObservationClassSelected kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = observation value (u16).
/// - `input`: bits[0..8] = bin_width (u8, >0), bits[8..16] = max_bins (u8, bin count cap).
///
/// Returns: bits[0..8] = bin index (clamped to [0, max_bins-1]).
#[inline]
#[must_use]
pub fn observation_class_selected(state: u64, input: u64) -> u64 {
    let obs = (state & 0xFFFF) as u32;
    let bin_width = (input & 0xFF) as u32;
    let max_bins = ((input >> 8) & 0xFF) as u32;
    // Branchless guard against zero bin_width: replace 0 with 1.
    let safe_width = bin_width + ((bin_width == 0) as u32);
    let raw_bin = obs / safe_width;
    // Clamp to [0, max_bins - 1]; guard max_bins==0 by treating cap as 0 (saturates to 0).
    let cap = max_bins.saturating_sub(1);
    let bin = clamp_u32(raw_bin, 0, cap);
    bin as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn observation_class_selected_reference(state: u64, input: u64) -> u64 {
        let obs = (state & 0xFFFF) as u32;
        let bin_width = (input & 0xFF) as u32;
        let max_bins = ((input >> 8) & 0xFF) as u32;
        let safe_width = bin_width.max(1);
        let raw_bin = obs / safe_width;
        let cap = max_bins.saturating_sub(1);
        raw_bin.min(cap) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !observation_class_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        observation_class_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(observation_class_selected_reference(s, i), observation_class_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = observation_class_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = observation_class_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // obs=50, bin_width=10, max_bins=8 -> 50/10=5, clamped to 5
        let out = observation_class_selected(50, 10 | (8 << 8));
        assert_eq!(out & 0xFF, 5);
        // obs=0, bin_width=10, max_bins=8 -> 0/10=0
        let out2 = observation_class_selected(0, 10 | (8 << 8));
        assert_eq!(out2 & 0xFF, 0);
        // obs=255, bin_width=10, max_bins=8 -> 255/10=25, clamped to 7
        let out3 = observation_class_selected(255, 10 | (8 << 8));
        assert_eq!(out3 & 0xFF, 7);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: raw bin index already inside [0, max_bins-1].
        &[(50, 10 | (8 << 8)), (0, 10 | (8 << 8))]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: raw bin index overshoots max_bins-1 and must be clamped.
        &[(255, 10 | (8 << 8)), (200, 1 | (4 << 8))]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the clamp to [0, max_bins-1].
        let obs = (s & 0xFFFF) as u32;
        let bin_width = (i & 0xFF) as u32;
        let safe_width = bin_width.max(1);
        (obs / safe_width) as u64
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                observation_class_selected(s, i),
                observation_class_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                observation_class_selected(s, i),
                observation_class_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != observation_class_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_observation_class_selected(c: &mut Criterion) {
        c.bench_function("observation_class_selected", |b| {
            b.iter(|| {
                black_box(observation_class_selected(
                    black_box(255),
                    black_box(10 | (8 << 8)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: bin index is bounded to [0, max_bins-1] for all inputs.
// Hoare-logic Verification Line 2: bin_width=0 is handled branchlessly via safe_width guard.
