// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (ocel_event_linked)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: OcelEventLinked
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Link an OCEL event to its objects: keep only the proposed object-reference bits that are
//! permitted by a validity gate (branchless [`bcinr_logic::mask::select_u64`]) and report the
//! admitted link count via [`bcinr_logic::int::popcount_u64`].

use bcinr_logic::int::popcount_u64;
use bcinr_logic::mask::select_u64;

/// OcelEventLinked kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = permitted object-reference bitmask (the gate).
/// - `input`: bits[0..32] = proposed object-reference bitmask.
///
/// Returns: bits[0..32] = admitted link bitmask, bits[32..40] = admitted link count.
#[inline]
#[must_use]
pub fn ocel_event_linked(state: u64, input: u64) -> u64 {
    let gate = state & 0xFFFF_FFFF;
    let proposed = input & 0xFFFF_FFFF;
    // Admitted links are proposed AND permitted; expressed via select to stay on the mask path.
    let admitted = select_u64(gate, proposed, 0) & 0xFFFF_FFFF;
    let count = popcount_u64(admitted) & 0xFF;
    admitted | (count << 32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn ocel_event_linked_reference(state: u64, input: u64) -> u64 {
        let gate = state & 0xFFFF_FFFF;
        let proposed = input & 0xFFFF_FFFF;
        let admitted = gate & proposed;
        let count = (admitted.count_ones() as u64) & 0xFF;
        admitted | (count << 32)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !ocel_event_linked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        ocel_event_linked_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(ocel_event_linked_reference(s, i), ocel_event_linked(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = ocel_event_linked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = ocel_event_linked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // gate permits low byte, proposed sets two of those + one outside.
        let out = ocel_event_linked(0xFF, 0b1_0000_0011);
        assert_eq!(out & 0xFFFF_FFFF, 0b11);
        assert_eq!((out >> 32) & 0xFF, 2);
        assert_eq!(ocel_event_linked(0, 0xFFFF_FFFF), 0);
    }

    // Two-sided breed-rigor battery.
    // Legal: every proposed link is already inside the permitted gate (subset).
    fn must_admit() -> &'static [(u64, u64)] {
        &[(0xFF, 0b11), (0xFFFF, 0xF0), (0xFFFF_FFFF, 0)]
    }
    // Extreme: proposals reach outside the gate, so the kernel must mask them off.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(0xFF, 0b1_0000_0011), (0, 0xFFFF_FFFF)]
    }
    // Weakened: omits the gate, admitting the raw proposal (and its inflated count).
    fn weakened(s: u64, i: u64) -> u64 {
        let _ = s;
        let proposed = i & 0xFFFF_FFFF;
        let count = (proposed.count_ones() as u64) & 0xFF;
        proposed | (count << 32)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(ocel_event_linked(s, i), ocel_event_linked_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(ocel_event_linked(s, i), ocel_event_linked_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != ocel_event_linked_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_ocel_event_linked(c: &mut Criterion) {
        c.bench_function("ocel_event_linked", |b| {
            b.iter(|| black_box(ocel_event_linked(black_box(0xFF), black_box(0b1_0000_0011))))
        });
    }
}

// Hoare-logic Verification Line 1: admitted links are a subset of the permitted gate.
// Hoare-logic Verification Line 2: reported count equals the popcount of admitted links.
