// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (packet_priority_evaluated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: PacketPriorityEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Evaluate packet send priority: select highest priority class among 3 pending packet queues.
//! Returns selected queue index and its priority. First index wins ties.

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// PacketPriorityEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = q0_priority, bits[8..16] = q1_priority, bits[16..24] = q2_priority.
/// - `input`: unused.
///
/// Returns: bits[0..8] = selected queue (0/1/2); bits[8..16] = winning priority.
#[inline]
#[must_use]
pub fn packet_priority_evaluated(state: u64, input: u64) -> u64 {
    let _ = input;
    let p0 = (state & 0xFF) as u32;
    let p1 = ((state >> 8) & 0xFF) as u32;
    let p2 = ((state >> 16) & 0xFF) as u32;
    let mut best_val = p0;
    let mut best_idx = 0u32;
    let m1 = lt_mask_u32(best_val, p1);
    best_idx = select_u32(m1, 1, best_idx);
    best_val = select_u32(m1, p1, best_val);
    let m2 = lt_mask_u32(best_val, p2);
    best_idx = select_u32(m2, 2, best_idx);
    best_val = select_u32(m2, p2, best_val);
    (best_idx as u64) | ((best_val as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn packet_priority_evaluated_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let p = [
            (state & 0xFF) as u32,
            ((state >> 8) & 0xFF) as u32,
            ((state >> 16) & 0xFF) as u32,
        ];
        let (mut bi, mut bv) = (0usize, p[0]);
        for (i, &v) in p.iter().enumerate().skip(1) {
            if v > bv {
                bi = i;
                bv = v;
            }
        }
        (bi as u64) | ((bv as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !packet_priority_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        packet_priority_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(packet_priority_evaluated_reference(s, i), packet_priority_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = packet_priority_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = packet_priority_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // p0=10, p1=30, p2=20 -> queue=1, priority=30
        let s = 10u64 | (30u64 << 8) | (20u64 << 16);
        let out = packet_priority_evaluated(s, 0);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFF, 30);

        // p0=30, p1=10, p2=20 -> queue=0, priority=30
        let s2 = 30u64 | (10u64 << 8) | (20u64 << 16);
        let out2 = packet_priority_evaluated(s2, 0);
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFF, 30);

        // p0=10, p1=10, p2=10 -> tie -> queue=0, priority=10
        let s3 = 10u64 | (10u64 << 8) | (10u64 << 16);
        let out3 = packet_priority_evaluated(s3, 0);
        assert_eq!(out3 & 0xFF, 0);
        assert_eq!((out3 >> 8) & 0xFF, 10);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // Queue 0 is already the (first) maximum: the argmax selects queue 0.
        &[
            (30 | (10 << 8) | (20 << 16), 0), // q0=30 strict max -> queue 0
            (10 | (10 << 8) | (10 << 16), 0), // all tied -> first wins -> queue 0
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // A later queue is strictly higher: the selector must move off queue 0.
        &[
            (10 | (30 << 8) | (20 << 16), 0),  // q1=30 -> queue 1
            (10 | (20 << 8) | (200 << 16), 0), // q2=200 -> queue 2
        ]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: always returns queue 0, omitting the argmax selection.
        let p0 = (s & 0xFF) as u32;
        (p0 as u64) << 8
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                packet_priority_evaluated(s, i),
                packet_priority_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                packet_priority_evaluated(s, i),
                packet_priority_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != packet_priority_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 10 | (30 << 8) | (20 << 16);
    const I: u64 = 0;
    pub fn bench_packet_priority_evaluated(c: &mut Criterion) {
        c.bench_function("packet_priority_evaluated", |b| {
            b.iter(|| black_box(packet_priority_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: lt_mask_u32(best_val, p_i) is 0xFFFFFFFF iff best_val < p_i, enabling branchless argmax with select_u32.
// Hoare-logic Verification Line 2: ties resolve to the lowest-index queue (strict < predicate keeps first maximum on equality).
