// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (path_cost_bounded)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: PathCostBounded
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp accumulated path cost to a maximum budget and flag if the budget was exceeded.

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::mask::lt_mask_u32;

/// PathCostBounded kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = accumulated path cost (u32)
/// - `input`: bits[0..32] = budget (max allowed cost)
///
/// Returns bits[0..32] = clamped cost, bits[32..40] = 1 if over budget, 0 if within.
#[inline]
#[must_use]
pub fn path_cost_bounded(state: u64, input: u64) -> u64 {
    let cost = (state & 0xFFFF_FFFF) as u32;
    let budget = (input & 0xFFFF_FFFF) as u32;
    let clamped = clamp_u32(cost, 0, budget);
    // over_budget = 1 when cost > budget, i.e. budget < cost
    let over = (lt_mask_u32(budget, cost) >> 31) & 1;
    (clamped as u64) | ((over as u64) << 32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn path_cost_bounded_reference(state: u64, input: u64) -> u64 {
        let cost = (state & 0xFFFF_FFFF) as u32;
        let budget = (input & 0xFFFF_FFFF) as u32;
        if cost > budget {
            (budget as u64) | (1u64 << 32)
        } else {
            cost as u64
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !path_cost_bounded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        path_cost_bounded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test] fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(path_cost_bounded_reference(s, i), path_cost_bounded(s, i));
        }
        #[test] fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = path_cost_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test] fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = path_cost_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // cost=50/budget=100 -> clamped=50, over=0
        assert_eq!(
            path_cost_bounded(50, 100),
            path_cost_bounded_reference(50, 100)
        );
        // cost=150/budget=100 -> clamped=100, over=1
        assert_eq!(
            path_cost_bounded(150, 100),
            path_cost_bounded_reference(150, 100)
        );
        // cost=100/budget=100 -> clamped=100, over=0
        assert_eq!(
            path_cost_bounded(100, 100),
            path_cost_bounded_reference(100, 100)
        );
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Within budget: pass through, no overflow.
            (50, 100),
            // Exactly at budget: still within, no clamp.
            (100, 100),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Over budget: cost must be CLAMPED down to budget and flagged.
            (150, 100),
            // Far over budget: clamp pins the result to the budget ceiling.
            (0xFFFF_FFFF, 100),
        ]
    }

    // Weakened: emit the raw cost with no clamp to the budget ceiling, so
    // over-budget costs leak through unbounded.
    fn weakened(s: u64, i: u64) -> u64 {
        let cost = (s & 0xFFFF_FFFF) as u32;
        let budget = (i & 0xFFFF_FFFF) as u32;
        let over = (lt_mask_u32(budget, cost) >> 31) & 1;
        // BUG: no clamp_u32 — cost passes through unbounded.
        (cost as u64) | ((over as u64) << 32)
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(path_cost_bounded(s, i), path_cost_bounded_reference(s, i));
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(path_cost_bounded(s, i), path_cost_bounded_reference(s, i));
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != path_cost_bounded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_path_cost_bounded(c: &mut Criterion) {
        c.bench_function("path_cost_bounded", |b| {
            b.iter(|| black_box(path_cost_bounded(black_box(150), black_box(100))))
        });
    }
}

// Hoare-logic Verification Line 1: clamp_u32(cost, 0, budget) guarantees result in [0, budget] without branching.
// Hoare-logic Verification Line 2: over flag = top bit of lt_mask_u32(budget, cost) >> 31, set iff cost > budget — branchless.
