// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (payload_size_bounded)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: PayloadSizeBounded
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp a payload size request to the adapter's maximum MTU via branchless
//! [`bcinr_logic::mask::min_u32`]. Returns the clamped payload size and an overflow flag
//! indicating whether the request exceeded the MTU.

use bcinr_logic::mask::{lt_mask_u32, min_u32};

/// PayloadSizeBounded kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = requested payload size (u16).
/// - `input`: bits[0..16] = max MTU (u16).
///
/// Returns: bits[0..16] = clamped payload size; bits[16..24] = overflow flag (1 if request > MTU).
#[inline]
#[must_use]
pub fn payload_size_bounded(state: u64, input: u64) -> u64 {
    let requested = (state & 0xFFFF) as u32;
    let mtu = (input & 0xFFFF) as u32;
    let clamped = min_u32(requested, mtu);
    // lt_mask_u32(mtu, requested) = 0xFFFFFFFF when mtu < requested (i.e. overflow), else 0.
    let overflow = (lt_mask_u32(mtu, requested) >> 31) as u64;
    (clamped as u64) | (overflow << 16)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn payload_size_bounded_reference(state: u64, input: u64) -> u64 {
        let requested = (state & 0xFFFF) as u32;
        let mtu = (input & 0xFFFF) as u32;
        let c = requested.min(mtu);
        let o = (requested > mtu) as u64;
        (c as u64) | (o << 16)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !payload_size_bounded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        payload_size_bounded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(payload_size_bounded_reference(s, i), payload_size_bounded(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = payload_size_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = payload_size_bounded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // req=100, mtu=200 -> clamped=100, overflow=0.
        let out = payload_size_bounded(100, 200);
        assert_eq!(out & 0xFFFF, 100);
        assert_eq!((out >> 16) & 0xFF, 0);
        // req=300, mtu=200 -> clamped=200, overflow=1.
        let out2 = payload_size_bounded(300, 200);
        assert_eq!(out2 & 0xFFFF, 200);
        assert_eq!((out2 >> 16) & 0xFF, 1);
        // req=200, mtu=200 -> clamped=200, overflow=0 (equal, no overflow).
        let out3 = payload_size_bounded(200, 200);
        assert_eq!(out3 & 0xFFFF, 200);
        assert_eq!((out3 >> 16) & 0xFF, 0);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: request fits within the MTU (no clamp, no overflow).
        &[(100, 200), (200, 200)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: request exceeds the MTU and must be clamped down.
        &[(300, 200), (65535, 1)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the min() clamp, passing the request through unbounded.
        let requested = (s & 0xFFFF) as u32;
        let mtu = (i & 0xFFFF) as u32;
        let o = (requested > mtu) as u64;
        (requested as u64) | (o << 16)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                payload_size_bounded(s, i),
                payload_size_bounded_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                payload_size_bounded(s, i),
                payload_size_bounded_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != payload_size_bounded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 300; // requested
    const I: u64 = 200; // mtu
    pub fn bench_payload_size_bounded(c: &mut Criterion) {
        c.bench_function("payload_size_bounded", |b| {
            b.iter(|| black_box(payload_size_bounded(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: min_u32 selects the smaller of requested and mtu via branchless bit manipulation.
// Hoare-logic Verification Line 2: lt_mask_u32(mtu, requested) >> 31 yields 1 exactly when mtu < requested (strict overflow).
