// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (physics_value_rendered)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: PhysicsValueRendered
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Render a raw physical quantity into a display-safe range by clamping it to `[lo, hi]`
//! with [`bcinr_logic::fix::clamp_u32`] (no conditional branches).

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::mask::min_u32;

/// PhysicsValueRendered kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = raw quantity (fixed-point).
/// - `input`: bits[0..16] = lo bound, bits[16..32] = hi bound (lo and hi are normalized so
///   `lo <= hi`).
///
/// Returns the clamped, display-ready value in bits[0..32].
#[inline]
#[must_use]
pub fn physics_value_rendered(state: u64, input: u64) -> u64 {
    let raw = (state & 0xFFFF_FFFF) as u32;
    let lo = (input & 0xFFFF) as u32;
    let hi = ((input >> 16) & 0xFFFF) as u32;
    // Normalize: clamp range so lo <= hi, branchlessly.
    let lo_n = min_u32(lo, hi);
    let rendered = clamp_u32(raw, lo_n, hi);
    (rendered as u64) & 0xFFFF_FFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn physics_value_rendered_reference(state: u64, input: u64) -> u64 {
        let raw = (state & 0xFFFF_FFFF) as u32;
        let lo = (input & 0xFFFF) as u32;
        let hi = ((input >> 16) & 0xFFFF) as u32;
        let lo_n = lo.min(hi);
        let rendered = raw.clamp(lo_n, hi);
        (rendered as u64) & 0xFFFF_FFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !physics_value_rendered_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        physics_value_rendered_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(physics_value_rendered_reference(s, i), physics_value_rendered(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = physics_value_rendered_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = physics_value_rendered_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // raw 500 clamped to [10, 100] -> 100.
        let input = 10u64 | (100u64 << 16);
        assert_eq!(physics_value_rendered(500, input), 100);
        // raw 5 clamped to [10, 100] -> 10.
        assert_eq!(physics_value_rendered(5, input), 10);
        assert_eq!(physics_value_rendered(50, input), 50);
    }

    // Two-sided breed-rigor battery.
    // Legal: raw values already inside [lo, hi] (clamp is a no-op).
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (50, 10 | (100 << 16)),
            (10, 10 | (100 << 16)),
            (100, 10 | (100 << 16)),
        ]
    }
    // Extreme: raw values outside the range, so the kernel must clamp to a bound.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(500, 10 | (100 << 16)), (5, 10 | (100 << 16))]
    }
    // Weakened: omits the clamp, returning the raw (out-of-range) value.
    fn weakened(s: u64, i: u64) -> u64 {
        let _ = i;
        s & 0xFFFF_FFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                physics_value_rendered(s, i),
                physics_value_rendered_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                physics_value_rendered(s, i),
                physics_value_rendered_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != physics_value_rendered_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_physics_value_rendered(c: &mut Criterion) {
        let input = 10u64 | (100u64 << 16);
        c.bench_function("physics_value_rendered", |b| {
            b.iter(|| black_box(physics_value_rendered(black_box(500), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: output always lies within the normalized [lo, hi] range.
// Hoare-logic Verification Line 2: an inverted (lo > hi) range is normalized before clamping.
