// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (policy_action_selected)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: PolicyActionSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select the highest-value action from a policy's four Q-values, with first-index-wins
//! tie-breaking. Uses branchless [`bcinr_logic::mask::lt_mask_u32`] /
//! [`bcinr_logic::mask::select_u32`] argmax over the four u16 Q-value lanes.

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// PolicyActionSelected kernel. Packed-u64 ABI:
/// - `state`: unused (reserved for policy/agent context id).
/// - `input`: four u16 Q-values in lanes [0..16, 16..32, 32..48, 48..64].
///
/// Returns: bits[0..8] = best action index (0..3); bits[8..24] = best Q-value.
#[inline]
#[must_use]
pub fn policy_action_selected(state: u64, input: u64) -> u64 {
    let _ = state;
    let q0 = (input & 0xFFFF) as u32;
    let q1 = ((input >> 16) & 0xFFFF) as u32;
    let q2 = ((input >> 32) & 0xFFFF) as u32;
    let q3 = ((input >> 48) & 0xFFFF) as u32;

    let mut best_val = q0;
    let mut best_idx = 0u32;

    // Candidate i wins only on strict >, preserving first-index-wins on ties.
    let m1 = lt_mask_u32(best_val, q1);
    best_idx = select_u32(m1, 1, best_idx);
    best_val = select_u32(m1, q1, best_val);

    let m2 = lt_mask_u32(best_val, q2);
    best_idx = select_u32(m2, 2, best_idx);
    best_val = select_u32(m2, q2, best_val);

    let m3 = lt_mask_u32(best_val, q3);
    best_idx = select_u32(m3, 3, best_idx);
    best_val = select_u32(m3, q3, best_val);

    (best_idx as u64) | ((best_val as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn policy_action_selected_reference(_state: u64, input: u64) -> u64 {
        let q = [
            (input & 0xFFFF) as u32,
            ((input >> 16) & 0xFFFF) as u32,
            ((input >> 32) & 0xFFFF) as u32,
            ((input >> 48) & 0xFFFF) as u32,
        ];
        let mut best_val = q[0];
        let mut best_idx = 0u32;
        for (i, &v) in q.iter().enumerate().skip(1) {
            if v > best_val {
                best_val = v;
                best_idx = i as u32;
            }
        }
        (best_idx as u64) | ((best_val as u64) << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !policy_action_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        policy_action_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(policy_action_selected_reference(s, i), policy_action_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = policy_action_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = policy_action_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Q-values [5, 9, 3, 9] -> first max is index 1, value 9.
        let input = 5u64 | (9u64 << 16) | (3u64 << 32) | (9u64 << 48);
        let out = policy_action_selected(0, input);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFFFF, 9);
        // All-zero Q-values -> index 0.
        assert_eq!(policy_action_selected(0, 0) & 0xFF, 0);
        // Q-values [0, 0, 100, 0] -> index 2, value 100.
        let input2 = 100u64 << 32;
        let out2 = policy_action_selected(0, input2);
        assert_eq!(out2 & 0xFF, 2);
        assert_eq!((out2 >> 8) & 0xFFFF, 100);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: the maximum already lives at index 0 (or all lanes tie at 0).
        &[
            (0, 9u64 | (5u64 << 16) | (3u64 << 32) | (1u64 << 48)),
            (0, 0),
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Argmax sits at a non-zero lane; the selection network must move off index 0.
        &[
            (0, 5u64 | (9u64 << 16) | (3u64 << 32) | (9u64 << 48)),
            (0, 100u64 << 32),
        ]
    }
    fn weakened(_s: u64, i: u64) -> u64 {
        // Broken variant: skips argmax, always reporting lane 0 (index 0, value q0).
        let q0 = i & 0xFFFF;
        q0 << 8
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                policy_action_selected(s, i),
                policy_action_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                policy_action_selected(s, i),
                policy_action_selected_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != policy_action_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_policy_action_selected(c: &mut Criterion) {
        let input = 5u64 | (9u64 << 16) | (3u64 << 32) | (9u64 << 48);
        c.bench_function("policy_action_selected", |b| {
            b.iter(|| black_box(policy_action_selected(black_box(0), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: the chosen Q-value equals the strict maximum of all candidates.
// Hoare-logic Verification Line 2: ties resolve to the lowest-index action (strict < comparison).
