// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (projectile_advanced)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: ProjectileAdvanced
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a 2D projectile one step: integrate position by velocity with saturating
//! arithmetic, then clamp each axis back into the play-field bounds with
//! [`bcinr_logic::fix::clamp_u32`].

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::int::saturating_add_i64;

/// ProjectileAdvanced kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = x, bits[16..32] = y (current position).
/// - `input`: bits[0..16] = vx (signed i16), bits[16..32] = vy (signed i16),
///   bits[32..48] = field_max (shared bound for both axes).
///
/// Returns: bits[0..16] = new x, bits[16..32] = new y (clamped to `[0, field_max]`).
#[inline]
#[must_use]
pub fn projectile_advanced(state: u64, input: u64) -> u64 {
    let x = (state & 0xFFFF) as i64;
    let y = ((state >> 16) & 0xFFFF) as i64;
    let vx = ((input & 0xFFFF) as u16 as i16) as i64;
    let vy = (((input >> 16) & 0xFFFF) as u16 as i16) as i64;
    let field_max = ((input >> 32) & 0xFFFF) as u32;

    let nx = saturating_add_i64(x, vx).max(0) as u32;
    let ny = saturating_add_i64(y, vy).max(0) as u32;
    let cx = clamp_u32(nx, 0, field_max) as u64;
    let cy = clamp_u32(ny, 0, field_max) as u64;
    cx | (cy << 16)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn projectile_advanced_reference(state: u64, input: u64) -> u64 {
        let x = (state & 0xFFFF) as i64;
        let y = ((state >> 16) & 0xFFFF) as i64;
        let vx = ((input & 0xFFFF) as u16 as i16) as i64;
        let vy = (((input >> 16) & 0xFFFF) as u16 as i16) as i64;
        let field_max = ((input >> 32) & 0xFFFF) as i64;
        let nx = (x + vx).max(0).min(field_max) as u64;
        let ny = (y + vy).max(0).min(field_max) as u64;
        nx | (ny << 16)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !projectile_advanced_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        projectile_advanced_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(projectile_advanced_reference(s, i), projectile_advanced(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = projectile_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = projectile_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // x=10,y=10 move +5,+5 within [0,100].
        let input = 5u64 | (5u64 << 16) | (100u64 << 32);
        let out = projectile_advanced(10 | (10 << 16), input);
        assert_eq!(out & 0xFFFF, 15);
        assert_eq!((out >> 16) & 0xFFFF, 15);
        // Negative velocity clamps to 0.
        let neg = (0xFFFBu64) | (0xFFFBu64 << 16) | (100u64 << 32); // vx=vy=-5
        let out2 = projectile_advanced(2 | (2 << 16), neg);
        assert_eq!(out2 & 0xFFFF, 0);
        assert_eq!((out2 >> 16) & 0xFFFF, 0);
    }

    // Two-sided breed-rigor battery.
    // Legal: motion that stays strictly inside the play-field on both axes.
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (10 | (10 << 16), 5 | (5 << 16) | (100 << 32)),
            (50 | (50 << 16), 100 << 32),
        ]
    }
    // Extreme: motion past the upper field bound and below zero, which the kernel must clamp.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (90 | (90 << 16), 50 | (50 << 16) | (100 << 32)),
            (2 | (2 << 16), 0xFFFB | (0xFFFB << 16) | (100 << 32)),
        ]
    }
    // Weakened: omits the floor and the field clamp, leaking the raw integrated lane.
    fn weakened(s: u64, i: u64) -> u64 {
        let x = (s & 0xFFFF) as i64;
        let y = ((s >> 16) & 0xFFFF) as i64;
        let vx = ((i & 0xFFFF) as u16 as i16) as i64;
        let vy = (((i >> 16) & 0xFFFF) as u16 as i16) as i64;
        let nx = (saturating_add_i64(x, vx) as u64) & 0xFFFF;
        let ny = (saturating_add_i64(y, vy) as u64) & 0xFFFF;
        nx | (ny << 16)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                projectile_advanced(s, i),
                projectile_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                projectile_advanced(s, i),
                projectile_advanced_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != projectile_advanced_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_projectile_advanced(c: &mut Criterion) {
        let input = 5u64 | (5u64 << 16) | (100u64 << 32);
        c.bench_function("projectile_advanced", |b| {
            b.iter(|| {
                black_box(projectile_advanced(
                    black_box(10 | (10 << 16)),
                    black_box(input),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: both axes stay within [0, field_max] after integration.
// Hoare-logic Verification Line 2: integration saturates rather than overflowing the lane.
