// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (purchase_admitted)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: PurchaseAdmitted
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a purchase flow FSM one transition with [`bcinr_logic::dfa::dfa_advance`] over a
//! flat 5×5 transition table (IDLE, CART, CHECKOUT, PAID, FAILED) × (ADD, REMOVE, PAY,
//! CONFIRM, FAIL).

use bcinr_logic::dfa::dfa_advance;

/// Purchase FSM states.
pub const IDLE: usize = 0;
pub const CART: usize = 1;
pub const CHECKOUT: usize = 2;
pub const PAID: usize = 3;
pub const FAILED: usize = 4;

/// Purchase FSM symbols.
pub const ADD: usize = 0;
pub const REMOVE: usize = 1;
pub const PAY: usize = 2;
pub const CONFIRM: usize = 3;
pub const FAIL: usize = 4;

const ALPHABET: usize = 5;

#[rustfmt::skip]
const TABLE: [usize; 25] = [
    // input:       ADD     REMOVE   PAY      CONFIRM  FAIL
    /* IDLE     */  CART,   IDLE,    IDLE,    IDLE,    IDLE,
    /* CART     */  CART,   IDLE,    CHECKOUT,CART,    IDLE,
    /* CHECKOUT */  CART,   CART,    CHECKOUT,PAID,    FAILED,
    /* PAID     */  CART,   PAID,    PAID,    PAID,    PAID,
    /* FAILED   */  CART,   IDLE,    CHECKOUT,FAILED,  FAILED,
];

/// PurchaseAdmitted kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current purchase state (0..4, clamped to `[0, 5)`).
/// - `input`: bits[0..8] = event symbol (0..4, clamped to `[0, 5)`).
///
/// Returns the next purchase state in bits[0..8].
#[inline]
#[must_use]
pub fn purchase_admitted(state: u64, input: u64) -> u64 {
    let st = ((state & 0xFF) as usize).min(FAILED);
    let sym_raw = (input & 0xFF) as usize;
    // Branchless clamp: OOB symbols map to ADD (0), holding the default transition.
    let in_alphabet = (sym_raw < ALPHABET) as usize;
    let sym = (sym_raw & 0usize.wrapping_sub(in_alphabet)) as u8;
    let next = dfa_advance(st, sym, &TABLE, ALPHABET);
    (next as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn purchase_admitted_reference(state: u64, input: u64) -> u64 {
        let st = ((state & 0xFF) as usize).min(FAILED);
        let sym_raw = (input & 0xFF) as usize;
        let sym = if sym_raw < ALPHABET { sym_raw } else { 0 };
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !purchase_admitted_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        purchase_admitted_reference(s, i) ^ 0xFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(purchase_admitted_reference(s, i), purchase_admitted(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = purchase_admitted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = purchase_admitted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // IDLE + ADD -> CART.
        assert_eq!(purchase_admitted(IDLE as u64, ADD as u64), CART as u64);
        // CHECKOUT + CONFIRM -> PAID.
        assert_eq!(
            purchase_admitted(CHECKOUT as u64, CONFIRM as u64),
            PAID as u64
        );
        // CHECKOUT + FAIL -> FAILED.
        assert_eq!(
            purchase_admitted(CHECKOUT as u64, FAIL as u64),
            FAILED as u64
        );
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain (state, symbol) transitions.
        &[(IDLE as u64, ADD as u64), (CHECKOUT as u64, CONFIRM as u64)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain symbols (and state): the kernel masks OOB symbols to
        // ADD and clamps the state, holding the default transition.
        &[(CHECKOUT as u64, 200), (200, 200)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: clamps OOB symbols to the last column (FAIL) instead of
        // masking them to ADD, diverging on out-of-domain events.
        let st = ((s & 0xFF) as usize).min(FAILED);
        let sym = ((i & 0xFF) as usize).min(ALPHABET - 1);
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(purchase_admitted(s, i), purchase_admitted_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(purchase_admitted(s, i), purchase_admitted_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != purchase_admitted_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const STATE: u64 = 2; // CHECKOUT
    const INPUT: u64 = 3; // CONFIRM

    pub fn bench_purchase_admitted(c: &mut Criterion) {
        c.bench_function("purchase_admitted", |b| {
            b.iter(|| black_box(purchase_admitted(black_box(STATE), black_box(INPUT))))
        });
    }
}

// Hoare-logic Verification Line 1: table index is bounded by state clamping and OOB symbol masking.
// Hoare-logic Verification Line 2: PAID and FAILED are trap states absorbing their respective final events.
