// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (quality_gate_evaluated)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: QualityGateEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a quality gate FSM for a manufacturing/game process using a flat DFA transition
//! table. States: UNINSPECTED=0, PENDING=1, PASSED=2, FAILED=3, REMEDIATED=4.
//! Symbols: SUBMIT=0, PASS=1, FAIL=2, REMEDIATE=3, RESUBMIT=4.

use bcinr_logic::dfa::dfa_advance;

/// Number of input symbols in the quality gate alphabet.
const ALPHABET: usize = 5;

/// Flat transition table [state * ALPHABET + symbol] = next_state.
/// Rows: UNINSPECTED=0, PENDING=1, PASSED=2, FAILED=3, REMEDIATED=4.
/// Cols: SUBMIT=0, PASS=1, FAIL=2, REMEDIATE=3, RESUBMIT=4.
#[rustfmt::skip]
const TABLE: [usize; 25] = [
    // SUBMIT  PASS  FAIL  REMEDIATE  RESUBMIT
    /* UNINSPECTED  */ 1,    0,    0,    0,         1,
    /* PENDING      */ 1,    2,    3,    1,         1,
    /* PASSED       */ 2,    2,    3,    2,         2,
    /* FAILED       */ 3,    3,    3,    4,         1,
    /* REMEDIATED   */ 4,    2,    3,    4,         1,
];

/// QualityGateEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current gate state (0..=4, clamped to [0, 5)).
/// - `input`: bits[0..8] = symbol (0..=4, clamped to [0, 5)).
///
/// Returns: bits[0..8] = next gate state.
#[inline]
#[must_use]
pub fn quality_gate_evaluated(state: u64, input: u64) -> u64 {
    // Clamp state and symbol into valid ranges branchlessly via modulo-equivalent masking.
    // Five states, five symbols: use remainder via integer division (deterministic, O(1)).
    let st = ((state & 0xFF) as usize) % ALPHABET;
    let sym = ((input & 0xFF) as u8) % (ALPHABET as u8);
    let next = dfa_advance(st, sym, &TABLE, ALPHABET);
    (next as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn quality_gate_evaluated_reference(state: u64, input: u64) -> u64 {
        let st = ((state & 0xFF) as usize) % ALPHABET;
        let sym = ((input & 0xFF) as usize) % ALPHABET;
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !quality_gate_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        quality_gate_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(quality_gate_evaluated_reference(s, i), quality_gate_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = quality_gate_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = quality_gate_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // UNINSPECTED(0) + SUBMIT(0) -> PENDING(1)
        assert_eq!(quality_gate_evaluated(0, 0), 1);
        // PENDING(1) + PASS(1) -> PASSED(2)
        assert_eq!(quality_gate_evaluated(1, 1), 2);
        // FAILED(3) + REMEDIATE(3) -> REMEDIATED(4)
        assert_eq!(quality_gate_evaluated(3, 3), 4);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: state and symbol both within [0, ALPHABET).
        &[(0, 0), (1, 1), (3, 3)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: state/symbol beyond the alphabet; kernel reduces them mod ALPHABET.
        &[(7, 0), (12, 2)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: saturating-clamps the index instead of reducing modulo ALPHABET.
        let st = ((s & 0xFF) as usize).min(ALPHABET - 1);
        let sym = ((i & 0xFF) as usize).min(ALPHABET - 1);
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                quality_gate_evaluated(s, i),
                quality_gate_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                quality_gate_evaluated(s, i),
                quality_gate_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != quality_gate_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const S: u64 = 1; // PENDING
    const I: u64 = 1; // PASS

    pub fn bench_quality_gate_evaluated(c: &mut Criterion) {
        c.bench_function("quality_gate_evaluated", |b| {
            b.iter(|| black_box(quality_gate_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: state and symbol are both clamped to [0, 5) before table lookup, keeping index in-bounds.
// Hoare-logic Verification Line 2: dfa_advance applies a safe-index mask ensuring out-of-bounds accesses yield 0 instead of UB.
