// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (quest_step_advanced)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: QuestStepAdvanced
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a linear quest one step with [`bcinr_logic::dfa::dfa_advance`]: `complete` moves
//! forward through steps 0..4 (Done is absorbing), `abandon` resets to step 0, `idle` holds.

use bcinr_logic::dfa::dfa_advance;

/// States: 0..4 = step index, 4 = Done (absorbing). Alphabet: 0=idle, 1=complete, 2=abandon.
const ALPHABET: usize = 3;
#[rustfmt::skip]
const TABLE: [usize; 15] = [
    // input:   idle complete abandon
    /* step0 */ 0, 1, 0,
    /* step1 */ 1, 2, 0,
    /* step2 */ 2, 3, 0,
    /* step3 */ 3, 4, 0,
    /* Done  */ 4, 4, 4,
];

/// QuestStepAdvanced kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current step (clamped into `[0, 5)`).
/// - `input`: bits[0..8] = quest symbol (clamped into `[0, 3)`).
///
/// Returns the next step in bits[0..8].
#[inline]
#[must_use]
pub fn quest_step_advanced(state: u64, input: u64) -> u64 {
    let st = ((state & 0xFF) as usize).min(4);
    let sym_raw = (input & 0xFF) as usize;
    // Branchless clamp of the symbol into [0, ALPHABET): dfa_advance returns 0 for OOB, but
    // we want OOB symbols to act as `idle` (hold), so map them onto 0.
    let in_alphabet = (sym_raw < ALPHABET) as usize;
    let sym = (sym_raw & 0usize.wrapping_sub(in_alphabet)) as u8;
    let next = dfa_advance(st, sym, &TABLE, ALPHABET);
    (next as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn quest_step_advanced_reference(state: u64, input: u64) -> u64 {
        let st = ((state & 0xFF) as usize).min(4);
        let sym_raw = (input & 0xFF) as usize;
        let sym = if sym_raw < ALPHABET { sym_raw } else { 0 };
        (TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !quest_step_advanced_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        quest_step_advanced_reference(s, i) ^ 0xFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(quest_step_advanced_reference(s, i), quest_step_advanced(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = quest_step_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = quest_step_advanced_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // step0 + complete -> step1.
        assert_eq!(quest_step_advanced(0, 1), 1);
        // step3 + complete -> Done(4).
        assert_eq!(quest_step_advanced(3, 1), 4);
        // Done is absorbing.
        assert_eq!(quest_step_advanced(4, 1), 4);
        // abandon resets to step0.
        assert_eq!(quest_step_advanced(2, 2), 0);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Legal forward transition: step0 + complete -> step1.
            (0, 1),
            // Legal reset: step2 + abandon -> step0.
            (2, 2),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Absorbing sink: Done(4) + complete must stay Done, never advance.
            (4, 1),
            // Out-of-alphabet symbol must be routed to idle (hold), not indexed raw.
            (3, 99),
        ]
    }

    // Weakened: a table whose Done row escapes (non-absorbing), and no OOB-as-idle
    // routing — the symbol is used raw, so the sink/illegal-input bounds vanish.
    fn weakened(s: u64, i: u64) -> u64 {
        #[rustfmt::skip]
        const BAD_TABLE: [usize; 15] = [
            0, 1, 0,
            1, 2, 0,
            2, 3, 0,
            3, 4, 0,
            // BUG: Done is no longer absorbing — complete advances past it.
            4, 0, 4,
        ];
        let st = ((s & 0xFF) as usize).min(4);
        // BUG: raw symbol, clamped only to stay in-bounds, not mapped to idle.
        let sym = ((i & 0xFF) as usize).min(ALPHABET - 1);
        (BAD_TABLE[st * ALPHABET + sym] as u64) & 0xFF
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                quest_step_advanced(s, i),
                quest_step_advanced_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                quest_step_advanced(s, i),
                quest_step_advanced_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != quest_step_advanced_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_quest_step_advanced(c: &mut Criterion) {
        c.bench_function("quest_step_advanced", |b| {
            b.iter(|| black_box(quest_step_advanced(black_box(2), black_box(1))))
        });
    }
}

// Hoare-logic Verification Line 1: the Done state is absorbing under every symbol.
// Hoare-logic Verification Line 2: out-of-alphabet symbols are treated as `idle` (hold).
