// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (receipt_appended)
// Regenerate: `ggen sync`. Lowering: Receipt.

//! Pattern: ReceiptAppended
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Append one transition to a rolling receipt chain by folding the prior digest and the
//! new event word through [`bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt`].

use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;

/// ReceiptAppended kernel. Packed-u64 ABI:
/// - `state`: prior 64-bit chain digest (`DeterministicSubstrateReceipt::FNV_OFFSET` to seed).
/// - `input`: the event word to seal (e.g. a packed tick/activity/object tuple).
///
/// Returns the new 64-bit chain digest.
#[inline]
#[must_use]
pub fn receipt_appended(state: u64, input: u64) -> u64 {
    let mut r = DeterministicSubstrateReceipt {
        current_hash: state,
        steps: 0,
    };
    r.record(input, state, input ^ state);
    r.finalize()
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn receipt_appended_reference(state: u64, input: u64) -> u64 {
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        // steps starts at 0, then tag=input, state=state, aux=input^state.
        let mut h = state;
        h = mix(h, 0);
        h = mix(h, input);
        h = mix(h, state);
        h = mix(h, input ^ state);
        h
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !receipt_appended_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        receipt_appended_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(receipt_appended_reference(s, i), receipt_appended(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = receipt_appended_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = receipt_appended_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        let seed = DeterministicSubstrateReceipt::FNV_OFFSET;
        assert_eq!(
            receipt_appended(seed, 0),
            receipt_appended_reference(seed, 0)
        );
        // Determinism: same inputs -> same digest.
        assert_eq!(receipt_appended(seed, 42), receipt_appended(seed, 42));
        // Sensitivity: different event -> different digest.
        assert_ne!(receipt_appended(seed, 1), receipt_appended(seed, 2));
    }

    // Two-sided breed-rigor battery.
    // NOTE: this kernel is a pure FNV-1a fold with no value bound to clamp/saturate; its
    // invariant is order/field sensitivity, so the weakening drops a fold term (a wrong-branch
    // omission) rather than removing a numeric bound.
    // Legal: ordinary in-domain (prior digest, event) pairs.
    fn must_admit() -> &'static [(u64, u64)] {
        &[(0xCBF2_9CE4_8422_2325, 42), (0, 0), (0x1234, 7)]
    }
    // Extreme: all-bits-set operands where the xor-aux term is maximally nonzero.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(0, u64::MAX), (u64::MAX, 0)]
    }
    // Weakened: omits the final `input ^ state` aux fold, dropping a contributing field.
    fn weakened(s: u64, i: u64) -> u64 {
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        let mut h = s;
        h = mix(h, 0);
        h = mix(h, i);
        h = mix(h, s);
        // (input ^ state aux fold deliberately omitted here)
        h
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(receipt_appended(s, i), receipt_appended_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(receipt_appended(s, i), receipt_appended_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != receipt_appended_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_receipt_appended(c: &mut Criterion) {
        let seed = DeterministicSubstrateReceipt::FNV_OFFSET;
        c.bench_function("receipt_appended", |b| {
            b.iter(|| black_box(receipt_appended(black_box(seed), black_box(42))))
        });
    }
}

// Hoare-logic Verification Line 1: the fold is a pure function of (prior digest, event).
// Hoare-logic Verification Line 2: FNV-1a mixing makes the chain order-sensitive.
