// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (replay_frame_recorded)
// Regenerate: `ggen sync`. Lowering: Receipt.

//! Pattern: ReplayFrameRecorded
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Record a deterministic replay frame by folding (prior digest, tick, input, state) through
//! [`bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt`] so identical
//! frame streams reproduce identical digests.

use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;

/// ReplayFrameRecorded kernel. Packed-u64 ABI:
/// - `state`: prior rolling replay digest.
/// - `input`: bits[0..16] = tick, bits[16..40] = input word, bits[40..64] = state digest lo.
///
/// Returns the new rolling replay digest.
#[inline]
#[must_use]
pub fn replay_frame_recorded(state: u64, input: u64) -> u64 {
    let tick = input & 0xFFFF;
    let in_word = (input >> 16) & 0xFF_FFFF;
    let st_digest = (input >> 40) & 0xFF_FFFF;
    let mut r = DeterministicSubstrateReceipt {
        current_hash: state,
        steps: tick,
    };
    r.record(in_word, st_digest, state);
    r.finalize()
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn replay_frame_recorded_reference(state: u64, input: u64) -> u64 {
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        let tick = input & 0xFFFF;
        let in_word = (input >> 16) & 0xFF_FFFF;
        let st_digest = (input >> 40) & 0xFF_FFFF;
        // steps seeded to tick, then tag=in_word, state=st_digest, aux=state.
        let mut h = state;
        h = mix(h, tick);
        h = mix(h, in_word);
        h = mix(h, st_digest);
        h = mix(h, state);
        h
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !replay_frame_recorded_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        replay_frame_recorded_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(replay_frame_recorded_reference(s, i), replay_frame_recorded(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = replay_frame_recorded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = replay_frame_recorded_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        let seed = DeterministicSubstrateReceipt::FNV_OFFSET;
        assert_eq!(
            replay_frame_recorded(seed, 0),
            replay_frame_recorded_reference(seed, 0)
        );
        // Determinism across identical frames.
        assert_eq!(
            replay_frame_recorded(seed, 7),
            replay_frame_recorded(seed, 7)
        );
    }

    // Two-sided breed-rigor battery.
    // NOTE: this kernel is a pure FNV-1a fold with no value bound to clamp/saturate; its
    // invariant is "every frame field participates in the mix", so the weakening drops a
    // field (a wrong-branch omission) rather than removing a numeric bound.
    // Legal: ordinary in-domain frames (any prior digest folds deterministically).
    fn must_admit() -> &'static [(u64, u64)] {
        &[(0xCBF2_9CE4_8422_2325, 7), (0, 0), (0x1234, 42)]
    }
    // Extreme: all-bits-set frames where every field is saturated/nonzero.
    fn must_refuse() -> &'static [(u64, u64)] {
        &[(0, u64::MAX), (0x1234_5678, u64::MAX)]
    }
    // Weakened: omits the in_word fold step, so a nonzero input word no longer mixes in.
    fn weakened(s: u64, i: u64) -> u64 {
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        let tick = i & 0xFFFF;
        let st_digest = (i >> 40) & 0xFF_FFFF;
        let mut h = s;
        h = mix(h, tick);
        // (in_word fold deliberately omitted here)
        h = mix(h, st_digest);
        h = mix(h, s);
        h
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                replay_frame_recorded(s, i),
                replay_frame_recorded_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                replay_frame_recorded(s, i),
                replay_frame_recorded_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != replay_frame_recorded_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_replay_frame_recorded(c: &mut Criterion) {
        let seed = DeterministicSubstrateReceipt::FNV_OFFSET;
        c.bench_function("replay_frame_recorded", |b| {
            b.iter(|| black_box(replay_frame_recorded(black_box(seed), black_box(7))))
        });
    }
}

// Hoare-logic Verification Line 1: identical frame streams fold to identical digests.
// Hoare-logic Verification Line 2: every frame field participates in the rolling mix.
