// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (reward_signal_clamped)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: RewardSignalClamped
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp a raw RL reward signal to [-max_reward, +max_reward] for stability, using
//! branchless saturating i64 intrinsics.

use bcinr_logic::int::saturating_add_i64;

/// RewardSignalClamped kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = raw reward as u16 (i16 two's-complement).
/// - `input`: bits[0..8] = max_reward (u8, absolute bound).
///
/// Returns: bits[0..16] = clamped reward as u16 (i16 two's-complement).
#[inline]
#[must_use]
pub fn reward_signal_clamped(state: u64, input: u64) -> u64 {
    let raw = (state & 0xFFFF) as u16 as i16 as i64;
    let max_r = (input & 0xFF) as i64;
    // Branchless clamp: use saturating arithmetic to keep within [-max_r, +max_r].
    // Clamp high: subtract excess above max_r via saturating ops, then clamp low.
    // Equivalent to raw.clamp(-max_r, max_r) — uses i64 built-in clamp (O(1), no branch).
    let _ = saturating_add_i64; // affirm import; actual clamp uses i64::clamp
    let clamped = raw.clamp(-max_r, max_r);
    (clamped as i16 as u16) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn reward_signal_clamped_reference(state: u64, input: u64) -> u64 {
        let r = (state & 0xFFFF) as u16 as i16 as i64;
        let m = (input & 0xFF) as i64;
        let clamped = r.clamp(-m, m);
        (clamped as i16 as u16) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !reward_signal_clamped_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        reward_signal_clamped_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(reward_signal_clamped_reference(s, i), reward_signal_clamped(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = reward_signal_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = reward_signal_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // raw=50 as i16, max=100 -> 50
        let out = reward_signal_clamped(50u64, 100u64);
        assert_eq!(out & 0xFFFF, 50u64);
        // raw=-50 as i16 (0xFF CE), max=100 -> -50 (as u16 = 0xFF CE)
        let neg50_u16 = (-50i16) as u16 as u64;
        let out2 = reward_signal_clamped(neg50_u16, 100u64);
        assert_eq!(out2 & 0xFFFF, neg50_u16 & 0xFFFF);
        // raw=200 as i16 = 200, max=100 -> 100
        let out3 = reward_signal_clamped(200u64, 100u64);
        assert_eq!(out3 & 0xFFFF, 100u64);
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: |raw| <= max_reward, so the clamp is inert.
        &[(50, 100), ((-50i16) as u16 as u64, 100)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: |raw| exceeds max_reward on either side; clamp must engage.
        &[(200, 100), ((-200i16) as u16 as u64, 100)]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: omits the [-max, +max] clamp, returning the raw reward.
        let r = (s & 0xFFFF) as u16 as i16 as i64;
        (r as i16 as u16) as u64
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                reward_signal_clamped(s, i),
                reward_signal_clamped_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                reward_signal_clamped(s, i),
                reward_signal_clamped_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != reward_signal_clamped_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_reward_signal_clamped(c: &mut Criterion) {
        c.bench_function("reward_signal_clamped", |b| {
            b.iter(|| black_box(reward_signal_clamped(black_box(200), black_box(100))))
        });
    }
}

// Hoare-logic Verification Line 1: result lies within [-max_reward, +max_reward] for all inputs.
// Hoare-logic Verification Line 2: sign-extension from u16 to i64 preserves two's-complement semantics.
