// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (share_artifact_generated)
// Regenerate: `ggen sync`. Lowering: Receipt.

//! Pattern: ShareArtifactGenerated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Generate a shareable artifact id by receipt-stamping a player/content seed through
//! [`bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt`], yielding a
//! collision-resistant, deterministic id for the share link.

use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;

/// ShareArtifactGenerated kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = player id, bits[32..64] = session salt.
/// - `input`: content seed (e.g. the mastery-moment digest being shared).
///
/// Returns the deterministic 64-bit share-artifact id.
#[inline]
#[must_use]
pub fn share_artifact_generated(state: u64, input: u64) -> u64 {
    let player = state & 0xFFFF_FFFF;
    let salt = (state >> 32) & 0xFFFF_FFFF;
    let mut r = DeterministicSubstrateReceipt::new();
    r.record(player, input, salt);
    r.finalize()
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn share_artifact_generated_reference(state: u64, input: u64) -> u64 {
        const OFFSET: u64 = DeterministicSubstrateReceipt::FNV_OFFSET;
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        let player = state & 0xFFFF_FFFF;
        let salt = (state >> 32) & 0xFFFF_FFFF;
        // new() seeds OFFSET, steps=0; record(tag=player, state=input, aux=salt).
        let mut h = OFFSET;
        h = mix(h, 0);
        h = mix(h, player);
        h = mix(h, input);
        h = mix(h, salt);
        h
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !share_artifact_generated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        share_artifact_generated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(share_artifact_generated_reference(s, i), share_artifact_generated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = share_artifact_generated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = share_artifact_generated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            share_artifact_generated(0, 0),
            share_artifact_generated_reference(0, 0)
        );
        // Determinism and content-sensitivity.
        assert_eq!(
            share_artifact_generated(7, 9),
            share_artifact_generated(7, 9)
        );
        assert_ne!(
            share_artifact_generated(7, 9),
            share_artifact_generated(7, 10)
        );
    }

    // --- two-sided breed-rigor battery ---
    // The only domain bound here is field extraction: player = low 32 bits of
    // state, salt = high 32 bits. The refuse corpus exercises states whose high
    // bits MUST be masked out of the player field before hashing.

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // In-domain seeds with no high bits to mask.
            (7, 9),
            (0x0000_0001_0000_0002, 0xABCD),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // High bits in state are the salt; player must stay the low 32 bits.
            (0xFFFF_FFFF_0000_0007, 0),
            // All-ones state: player and salt are each masked to 0xFFFF_FFFF.
            (0xFFFF_FFFF_FFFF_FFFF, 0x1234_5678),
        ]
    }

    // Weakened: feed the full unmasked state as the player tag, so high bits
    // leak into the player field instead of being confined to the salt.
    fn weakened(s: u64, i: u64) -> u64 {
        const OFFSET: u64 = DeterministicSubstrateReceipt::FNV_OFFSET;
        const PRIME: u64 = DeterministicSubstrateReceipt::FNV_PRIME;
        let mix = |h: u64, x: u64| (h ^ x).wrapping_mul(PRIME);
        // BUG: no `& 0xFFFF_FFFF` mask on the player field.
        let player = s;
        let salt = (s >> 32) & 0xFFFF_FFFF;
        let mut h = OFFSET;
        h = mix(h, 0);
        h = mix(h, player);
        h = mix(h, i);
        h = mix(h, salt);
        h
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                share_artifact_generated(s, i),
                share_artifact_generated_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                share_artifact_generated(s, i),
                share_artifact_generated_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != share_artifact_generated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_share_artifact_generated(c: &mut Criterion) {
        c.bench_function("share_artifact_generated", |b| {
            b.iter(|| black_box(share_artifact_generated(black_box(7), black_box(9))))
        });
    }
}

// Hoare-logic Verification Line 1: the artifact id is a pure function of player/salt/seed.
// Hoare-logic Verification Line 2: distinct content seeds yield distinct artifact ids (FNV).
