// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (sigma_level_computed)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: SigmaLevelComputed
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Compute Six-Sigma level from defects per million opportunities (DPMO) via branchless
//! threshold comparisons. Sigma levels 1–6 correspond to DPMO bucket boundaries:
//! [3, 233, 6210, 66807, 308538, 691462] (ascending thresholds = descending sigma).

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// SigmaLevelComputed kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = dpmo value (u32, 0..=1_000_000).
/// - `input`: unused.
///
/// Returns: bits[0..8] = sigma level (1..=6).
#[inline]
#[must_use]
pub fn sigma_level_computed(state: u64, input: u64) -> u64 {
    let _ = input;
    let dpmo = (state & 0xFFFF_FFFF) as u32;

    // Thresholds (ascending DPMO = descending sigma level):
    // dpmo < 3       -> sigma 6
    // dpmo < 233     -> sigma 5
    // dpmo < 6210    -> sigma 4
    // dpmo < 66807   -> sigma 3
    // dpmo < 308538  -> sigma 2
    // dpmo >= 308538 -> sigma 1
    let b6 = lt_mask_u32(dpmo, 3);
    let b5 = lt_mask_u32(dpmo, 233);
    let b4 = lt_mask_u32(dpmo, 6_210);
    let b3 = lt_mask_u32(dpmo, 66_807);
    let b2 = lt_mask_u32(dpmo, 308_538);

    // Build sigma level branchlessly via nested select (highest priority wins):
    // start from bottom: if >= 308538 => sigma 1
    let s = select_u32(b2, 2, 1); // 2 if dpmo < 308538, else 1
    let s = select_u32(b3, 3, s); // 3 if dpmo < 66807, else previous
    let s = select_u32(b4, 4, s); // 4 if dpmo < 6210, else previous
    let s = select_u32(b5, 5, s); // 5 if dpmo < 233, else previous
    let s = select_u32(b6, 6, s); // 6 if dpmo < 3, else previous

    (s as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn sigma_level_computed_reference(state: u64, input: u64) -> u64 {
        let _ = input;
        let dpmo = (state & 0xFFFF_FFFF) as u32;
        let sigma = if dpmo < 3 {
            6u64
        } else if dpmo < 233 {
            5
        } else if dpmo < 6_210 {
            4
        } else if dpmo < 66_807 {
            3
        } else if dpmo < 308_538 {
            2
        } else {
            1
        };
        sigma & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !sigma_level_computed_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        sigma_level_computed_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(sigma_level_computed_reference(s, i), sigma_level_computed(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = sigma_level_computed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = sigma_level_computed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // dpmo=0 -> sigma 6 (below threshold 3)
        assert_eq!(sigma_level_computed(0, 0), 6);
        // dpmo=1000 -> sigma 4 (233 <= 1000 < 6210)
        assert_eq!(sigma_level_computed(1000, 0), 4);
        // dpmo=999999 -> sigma 1 (>= 308538)
        assert_eq!(sigma_level_computed(999_999, 0), 1);
    }

    // Two-sided breed-rigor battery. The kernel selects a sigma bucket from DPMO
    // thresholds; admit = mid-range buckets, refuse = the extreme top bucket
    // (dpmo < 3 -> sigma 6) whose threshold a weakening drops.
    fn must_admit() -> &'static [(u64, u64)] {
        &[
            (1000, 0),    // 233 <= 1000 < 6210 -> sigma 4
            (999_999, 0), // >= 308538 -> sigma 1
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Extreme low-defect bucket: only the dpmo < 3 threshold yields sigma 6.
        &[
            (0, 0), // sigma 6
            (2, 0), // sigma 6
        ]
    }
    fn weakened(s: u64, _i: u64) -> u64 {
        // Broken variant: drops the top (sigma 6) threshold; the best bucket caps at 5.
        let dpmo = (s & 0xFFFF_FFFF) as u32;
        let b5 = lt_mask_u32(dpmo, 233);
        let b4 = lt_mask_u32(dpmo, 6_210);
        let b3 = lt_mask_u32(dpmo, 66_807);
        let b2 = lt_mask_u32(dpmo, 308_538);
        let r = select_u32(b2, 2, 1);
        let r = select_u32(b3, 3, r);
        let r = select_u32(b4, 4, r);
        let r = select_u32(b5, 5, r);
        (r as u64) & 0xFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                sigma_level_computed(s, i),
                sigma_level_computed_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                sigma_level_computed(s, i),
                sigma_level_computed_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != sigma_level_computed_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const S: u64 = 6_210;
    const I: u64 = 0;

    pub fn bench_sigma_level_computed(c: &mut Criterion) {
        c.bench_function("sigma_level_computed", |b| {
            b.iter(|| black_box(sigma_level_computed(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: sigma is monotone-decreasing in dpmo — higher DPMO yields lower or equal sigma.
// Hoare-logic Verification Line 2: result is always in [1, 6], satisfying the Six-Sigma level invariant.
