// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (spawn_weight_evaluated)
// Regenerate: `ggen sync`. Lowering: Mask.
#![forbid(unsafe_code)]

//! Pattern 29: **SpawnWeightEvaluated** — Mask lowering.
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! # Authority
//! oracle predicate: matches spawn_weight_evaluated_reference for all inputs.
//!
//! Evaluate whether a spawn should occur: spawn when a random roll is strictly less than the spawn_rate threshold.

// === lowering imports (specialized per pattern in the committed kernel) ===
use bcinr_logic::mask::lt_mask_u32;

/// Branchless kernel for the **SpawnWeightEvaluated** pattern (id 29).
///
/// Operates on packed `u64` state and `u64` input using the $\mathcal{B}$-Calculus
/// primitives. This function is branchless: no conditional jumps are emitted.
///
/// # Pattern Family
///
/// Mask
///
/// # Packed-u64 ABI
///
/// State encodes the packed domain state (2-bit cardinality).
/// Input encodes the event payload (see the committed kernel file for field layout).
///
/// # Return value
///
/// The updated state packed into a `u64`. For Anti-Cheat detector kernels
/// (ids 71–75) a nonzero return is a refusal verdict bitmask; zero means ADMITTED.
///
/// # Examples
///
/// ```
/// use wasm4games::patterns::spawn_weight_evaluated;
/// // Evaluate whether a spawn should occur: spawn when a random roll is strictly less than the spawn_rate threshold.
/// let new_state = spawn_weight_evaluated(/* initial state */ 0, /* input */ 0);
/// // u64::MAX is never a valid saturating-damage output.
/// assert!(new_state != u64::MAX);
/// ```
///
/// # Formal Verification
///
/// Hoare-logic invariants are exercised in the `tests` module below via proptest
/// oracle equivalence and a two-sided breed-rigor battery.
/// See `ggen/schema/patterns.ttl` for the ontology entry.
///
/// Authority: oracle predicate: matches spawn_weight_evaluated_reference for all inputs.
#[must_use = "pattern kernel — the returned state IS the result; ignoring it discards the computation"]
#[inline(always)]
pub fn spawn_weight_evaluated(state: u64, input: u64) -> u64 {
    // === REPRESENTATIVE LOWERING BODY (saturating-damage shape) ===
    // The committed kernel replaces this with the pattern-specific branchless lowering.
    let hp = (state & 0xFFFF) as i64;
    let dmg = (input & 0xFFFF) as i64;
    let new_hp = hp.saturating_sub(dmg).max(0);
    (new_hp as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // --- Falsification battery ---
    // Any change to the kernel that changes output on these inputs is a regression.

    // The reference oracle is intentionally branchful and structurally different from the
    // kernel so that a proof-of-equivalence via proptest cannot trivially pass by sharing
    // the same lowering.
    fn spawn_weight_evaluated_reference(state: u64, input: u64) -> u64 {
        // === REPRESENTATIVE BRANCHFUL ORACLE ===
        let hp = (state & 0xFFFF) as i64;
        let dmg = (input & 0xFFFF) as i64;
        // Explicit `if` rather than `.max(0)` so the oracle structurally diverges from
        // the branchless kernel.  clippy::comparison_to_empty is not triggered here
        // because the condition is `hp > dmg` (i64), not a length check.
        let floored = if hp > dmg { hp - dmg } else { 0_i64 };
        (floored as u64) & 0xFFFF
    }

    fn mutant_1(s: u64, i: u64) -> u64 {
        !spawn_weight_evaluated_reference(s, i)
    }

    // mutant_3 XORs with the output-lane mask for this pattern.
    // `xorMask` comes from the ontology (e.g. 0xFFFF for 16-bit lanes, 0xFF for 8-bit).
    // Using the correct lane mask keeps the counterfactual meaningful: a flip of every
    // output bit within the lane is always detectable when the kernel output is non-zero.
    fn mutant_3(s: u64, i: u64) -> u64 {
        spawn_weight_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn prop_equivalence_kernel_matches_oracle(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(spawn_weight_evaluated_reference(s, i), spawn_weight_evaluated(s, i));
        }
        #[test]
        fn prop_cf1_nonzero_output_differs_from_bitflip_mutant(s in any::<u64>(), i in any::<u64>()) {
            let r = spawn_weight_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn prop_cf3_nonzero_output_differs_from_xor_mutant(s in any::<u64>(), i in any::<u64>()) {
            let r = spawn_weight_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries_zero_and_max_match_oracle() {
        // (0, 0): zero damage — state is unchanged.
        assert_eq!(
            spawn_weight_evaluated(0, 0),
            spawn_weight_evaluated_reference(0, 0)
        );
        // (0xFFFF, 0xFFFF): max-damage from max-HP — saturates to 0.
        assert_eq!(
            spawn_weight_evaluated(0xFFFF, 0xFFFF),
            spawn_weight_evaluated_reference(0xFFFF, 0xFFFF)
        );
        // (100, 7): representative in-domain hit — exercises the normal sub path.
        assert_eq!(
            spawn_weight_evaluated(100, 7),
            spawn_weight_evaluated_reference(100, 7)
        );
    }

    // === Two-sided breed-rigor battery ===
    // Declared in the ontology as w4g:mustAdmit / w4g:mustRefuse; the committed kernel
    // specializes these `(state, input)` fixtures per pattern (detectors verdict 0 / nonzero;
    // value-kernels stay oracle-equal). The representative corpus below mirrors the
    // saturating-damage shape rendered above.
    fn must_admit() -> &'static [(u64, u64)] {
        // Legal, in-domain hits: damage strictly below current HP (no flooring needed).
        &[(100, 7), (100, 7 | (1 << 16)), (5000, 1000)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Extreme overkill: damage exceeds HP so the kernel must floor the result at 0.
        &[(0, 5), (10, 100 | (1 << 16))]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Weakened: omits the floor (drops `.max(0)`), so overkill underflows the lane.
        let hp = (s & 0xFFFF) as i64;
        let dmg = (i & 0xFFFF) as i64;
        let new_hp = hp.saturating_sub(dmg);
        (new_hp as u64) & 0xFFFF
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                spawn_weight_evaluated(s, i),
                spawn_weight_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                spawn_weight_evaluated(s, i),
                spawn_weight_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != spawn_weight_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }

    // === Pin test: stable output hash ===
    // Asserts a known-good FNV-1a hash over the boundary triple so that any silent change
    // to the kernel outputs (e.g. a wrong ontology edit, an off-by-one in a mutant) is
    // caught deterministically, independent of proptest shrinking randomness.
    //
    // The committed, hand-finished kernel replaces `EXPECTED_HASH` with the real constant
    // computed from its actual branchless body.  A value of `u64::MAX` here signals
    // "not yet pinned" and will always fail (sentinel), which is intentional: the scaffold
    // reminds the author to fill in the real hash before committing.
    #[test]
    fn output_hash_is_stable() {
        let a = spawn_weight_evaluated(0, 0);
        let b = spawn_weight_evaluated(0xFFFF, 0xFFFF);
        let c = spawn_weight_evaluated(100, 7);
        let hash = [a, b, c].iter().fold(0xcbf29ce484222325_u64, |h, &r| {
            (h ^ r).wrapping_mul(0x100000001b3_u64)
        });
        // REPLACE_EXPECTED_HASH: fill in the real value produced by `cargo test -- --nocapture`.
        const EXPECTED_HASH: u64 = u64::MAX; // sentinel — must be replaced in committed kernel
        assert_ne!(
            EXPECTED_HASH,
            u64::MAX,
            "output_hash_is_stable: EXPECTED_HASH is still the sentinel — \
             run the test with --nocapture to obtain the real hash and pin it"
        );
        assert_eq!(
            hash, EXPECTED_HASH,
            "kernel output hash changed — re-pin or investigate"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_spawn_weight_evaluated(c: &mut Criterion) {
        c.bench_function("spawn_weight_evaluated", |b| {
            b.iter(|| black_box(spawn_weight_evaluated(black_box(100), black_box(7))))
        });
    }
}

// Hoare-logic Verification Line 1: result matches the reference oracle for all inputs.
// Hoare-logic Verification Line 2: the Mask lowering keeps the path data-independent.
