// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (spawn_weight_evaluated)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: SpawnWeightEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Evaluate whether a spawn should occur: spawn when a random roll is strictly less than the
//! spawn_rate threshold. Uses [`bcinr_logic::mask::lt_mask_u32`] for a fully branchless
//! comparison; the roll is also packed into the result for audit purposes.

use bcinr_logic::mask::lt_mask_u32;

/// SpawnWeightEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = random roll (value range 0..=255).
/// - `input`: bits[0..16] = spawn_rate threshold (0..=255).
///
/// Returns: bits[0..8] = 1 if spawning (roll < rate), 0 otherwise; bits[8..24] = roll.
#[inline]
#[must_use]
pub fn spawn_weight_evaluated(state: u64, input: u64) -> u64 {
    let roll = (state & 0xFFFF) as u32;
    let rate = (input & 0xFFFF) as u32;
    // lt_mask_u32 returns 0xFFFFFFFF when roll < rate, 0 otherwise; >> 31 gives 1 or 0.
    let spawning = lt_mask_u32(roll, rate) >> 31;
    (spawning as u64) | ((roll as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn spawn_weight_evaluated_reference(state: u64, input: u64) -> u64 {
        let roll = (state & 0xFFFF) as u32;
        let rate = (input & 0xFFFF) as u32;
        if roll < rate {
            1 | ((roll as u64) << 8)
        } else {
            (roll as u64) << 8
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !spawn_weight_evaluated_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        spawn_weight_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(spawn_weight_evaluated_reference(s, i), spawn_weight_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = spawn_weight_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = spawn_weight_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // roll=10, rate=100 -> spawning=1, roll embedded.
        let out = spawn_weight_evaluated(10, 100);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFFFF, 10);
        // roll=100, rate=10 -> spawning=0 (roll >= rate).
        let out2 = spawn_weight_evaluated(100, 10);
        assert_eq!(out2 & 0xFF, 0);
        // roll=50, rate=50 -> spawning=0 (not strictly less than).
        let out3 = spawn_weight_evaluated(50, 50);
        assert_eq!(out3 & 0xFF, 0);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain rolls strictly below the rate: spawn fires legitimately.
        &[(10, 100), (0, 255)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // roll >= rate: the strict `<` bound must refuse the spawn (flag 0).
        &[(100, 10), (50, 50), (255, 0)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: always spawns, dropping the roll < rate guard.
        let _ = i;
        let roll = (s & 0xFFFF) as u32;
        1u64 | ((roll as u64) << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                spawn_weight_evaluated(s, i),
                spawn_weight_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                spawn_weight_evaluated(s, i),
                spawn_weight_evaluated_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != spawn_weight_evaluated_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_spawn_weight_evaluated(c: &mut Criterion) {
        c.bench_function("spawn_weight_evaluated", |b| {
            b.iter(|| black_box(spawn_weight_evaluated(black_box(10), black_box(100))))
        });
    }
}

// Hoare-logic Verification Line 1: lt_mask_u32 produces 0xFFFFFFFF iff roll < rate, else 0.
// Hoare-logic Verification Line 2: the roll is packed into bits[8..24] for audit traceability.
