// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (status_effect_ticked)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: StatusEffectTicked
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Tick a status-effect set: optionally set/clear one effect bit with
//! [`bcinr_logic::bitset::set_bit_u64`] / [`bcinr_logic::bitset::clear_bit_u64`], decay the
//! shared duration with saturating subtraction, and re-count active effects via
//! [`bcinr_logic::bitset::rank_u64`].

use bcinr_logic::bitset::{clear_bit_u64, rank_u64, set_bit_u64};
use bcinr_logic::int::saturating_sub_i64;
use bcinr_logic::mask::select_u64;

/// StatusEffectTicked kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = effect bitmask (16 effect slots), bits[16..32] = duration.
/// - `input`: bits[0..4] = slot index, bit[4] = set(1)/clear(0), bit[5] = apply toggle,
///   bits[8..16] = duration decay amount.
///
/// Returns: bits[0..16] = effect bitmask, bits[16..32] = duration,
/// bits[32..40] = active effect count.
#[inline]
#[must_use]
pub fn status_effect_ticked(state: u64, input: u64) -> u64 {
    let mask = state & 0xFFFF;
    let duration = ((state >> 16) & 0xFFFF) as i64;

    let slot = (input & 0xF) as usize;
    let set_flag = 0u64.wrapping_sub((input >> 4) & 1);
    let apply = 0u64.wrapping_sub((input >> 5) & 1);
    let decay = ((input >> 8) & 0xFF) as i64;

    let with_set = set_bit_u64(mask, slot);
    let with_clear = clear_bit_u64(mask, slot);
    let toggled = select_u64(set_flag, with_set, with_clear);
    let new_mask = (select_u64(apply, toggled, mask)) & 0xFFFF;

    let new_dur = saturating_sub_i64(duration, decay).max(0) as u64 & 0xFFFF;
    let count = rank_u64(new_mask, 15) as u64 & 0xFF;

    new_mask | (new_dur << 16) | (count << 32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn status_effect_ticked_reference(state: u64, input: u64) -> u64 {
        let mask = state & 0xFFFF;
        let duration = ((state >> 16) & 0xFFFF) as i64;
        let slot = (input & 0xF) as u32;
        let set_flag = ((input >> 4) & 1) == 1;
        let apply = ((input >> 5) & 1) == 1;
        let decay = ((input >> 8) & 0xFF) as i64;

        let mut new_mask = mask;
        if apply {
            if set_flag {
                new_mask |= 1u64 << slot;
            } else {
                new_mask &= !(1u64 << slot);
            }
        }
        new_mask &= 0xFFFF;
        let nd = duration.saturating_sub(decay);
        let new_dur = (if nd < 0 { 0 } else { nd } as u64) & 0xFFFF;
        let count = (new_mask.count_ones() as u64) & 0xFF;
        new_mask | (new_dur << 16) | (count << 32)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !status_effect_ticked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        status_effect_ticked_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(status_effect_ticked_reference(s, i), status_effect_ticked(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = status_effect_ticked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = status_effect_ticked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            status_effect_ticked(0, 0),
            status_effect_ticked_reference(0, 0)
        );
        // Apply+set slot 2, no decay: mask bit2, count 1.
        let input = 2u64 | (1 << 4) | (1 << 5);
        let out = status_effect_ticked(0, input);
        assert_eq!(out & 0xFFFF, 0b100);
        assert_eq!((out >> 32) & 0xFF, 1);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Apply+set slot 2 with modest decay 3 against duration 10.
            ((10u64 << 16), 2u64 | (1 << 4) | (1 << 5) | (3u64 << 8)),
            // No apply, decay 1 against duration 5.
            ((0b0101 | (5u64 << 16)), 1u64 << 8),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Decay 0xFF overruns duration 1: must saturate at 0, not wrap.
            ((1u64 << 16), 0xFFu64 << 8),
            // Zero duration, max decay: floor pins to 0.
            (0, 0xFFu64 << 8),
        ]
    }

    // Weakened: omit the saturation floor, letting duration - decay wrap below 0.
    fn weakened(s: u64, i: u64) -> u64 {
        let mask = s & 0xFFFF;
        let duration = ((s >> 16) & 0xFFFF) as i64;
        let slot = (i & 0xF) as usize;
        let set_flag = 0u64.wrapping_sub((i >> 4) & 1);
        let apply = 0u64.wrapping_sub((i >> 5) & 1);
        let decay = ((i >> 8) & 0xFF) as i64;
        let with_set = set_bit_u64(mask, slot);
        let with_clear = clear_bit_u64(mask, slot);
        let toggled = select_u64(set_flag, with_set, with_clear);
        let new_mask = select_u64(apply, toggled, mask) & 0xFFFF;
        // BUG: raw wrapping subtraction with no .max(0) floor.
        let new_dur = duration.wrapping_sub(decay) as u64 & 0xFFFF;
        let count = rank_u64(new_mask, 15) as u64 & 0xFF;
        new_mask | (new_dur << 16) | (count << 32)
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                status_effect_ticked(s, i),
                status_effect_ticked_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                status_effect_ticked(s, i),
                status_effect_ticked_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != status_effect_ticked_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_status_effect_ticked(c: &mut Criterion) {
        let input = 2u64 | (1 << 4) | (1 << 5) | (3 << 8);
        c.bench_function("status_effect_ticked", |b| {
            b.iter(|| {
                black_box(status_effect_ticked(
                    black_box(0x0005_000F),
                    black_box(input),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: active count equals the popcount of the resulting mask.
// Hoare-logic Verification Line 2: duration decay saturates at zero, never underflowing.
