// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (terrain_height_quantized)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: TerrainHeightQuantized
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Clamp a raw terrain height sample to [min_h, max_h] using
//! [`bcinr_logic::fix::clamp_u32`], producing a bounded 16-bit height value.

use bcinr_logic::fix::clamp_u32;

/// TerrainHeightQuantized kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = raw height value (u16).
/// - `input`: bits[0..16] = min_height, bits[16..32] = max_height.
///
/// Returns: bits[0..16] = clamped height in [min_height, max_height].
#[inline]
#[must_use]
pub fn terrain_height_quantized(state: u64, input: u64) -> u64 {
    let raw = (state & 0xFFFF) as u32;
    let min_h = (input & 0xFFFF) as u32;
    let max_h = ((input >> 16) & 0xFFFF) as u32;
    clamp_u32(raw, min_h, max_h) as u64 & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn terrain_height_quantized_reference(state: u64, input: u64) -> u64 {
        let raw = (state & 0xFFFF) as u32;
        let min_h = (input & 0xFFFF) as u32;
        let max_h = ((input >> 16) & 0xFFFF) as u32;
        raw.clamp(min_h, max_h) as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !terrain_height_quantized_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        terrain_height_quantized_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(
            raw in 0u64..=0xFFFF,
            min_h in 0u64..=0xFFFF,
            max_h in 0u64..=0xFFFF,
        ) {
            // Ensure min <= max to avoid degenerate clamp; otherwise skip.
            let input = min_h | (max_h << 16);
            if min_h <= max_h {
                prop_assert_eq!(
                    terrain_height_quantized_reference(raw, input),
                    terrain_height_quantized(raw, input)
                );
            }
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let min_h = (i & 0xFFFF) as u32;
            let max_h = ((i >> 16) & 0xFFFF) as u32;
            prop_assume!(min_h <= max_h);
            let r = terrain_height_quantized_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let min_h = (i & 0xFFFF) as u32;
            let max_h = ((i >> 16) & 0xFFFF) as u32;
            prop_assume!(min_h <= max_h);
            let r = terrain_height_quantized_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // raw=50, min=100, max=200 -> clamped to 100 (below floor).
        assert_eq!(terrain_height_quantized(50, 100 | (200 << 16)), 100);
        // raw=150, min=100, max=200 -> unchanged at 150.
        assert_eq!(terrain_height_quantized(150, 100 | (200 << 16)), 150);
        // raw=250, min=100, max=200 -> clamped to 200 (above ceiling).
        assert_eq!(terrain_height_quantized(250, 100 | (200 << 16)), 200);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Inside the band: pass through unchanged.
            (150, 100 | (200 << 16)),
            // Exactly on the floor: unchanged.
            (100, 100 | (200 << 16)),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Below the floor: must clamp UP to min_h.
            (50, 100 | (200 << 16)),
            // Above the ceiling: must clamp DOWN to max_h.
            (250, 100 | (200 << 16)),
        ]
    }

    // Weakened: return the raw sample with no clamp, so out-of-band heights
    // escape the [min_h, max_h] window.
    fn weakened(s: u64, i: u64) -> u64 {
        let raw = (s & 0xFFFF) as u32;
        let _min_h = (i & 0xFFFF) as u32;
        let _max_h = ((i >> 16) & 0xFFFF) as u32;
        // BUG: no clamp_u32 — raw passes through unbounded.
        raw as u64 & 0xFFFF
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                terrain_height_quantized(s, i),
                terrain_height_quantized_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                terrain_height_quantized(s, i),
                terrain_height_quantized_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != terrain_height_quantized_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_terrain_height_quantized(c: &mut Criterion) {
        c.bench_function("terrain_height_quantized", |b| {
            b.iter(|| {
                black_box(terrain_height_quantized(
                    black_box(150),
                    black_box(100 | (200 << 16)),
                ))
            })
        });
    }
}

// Hoare-logic Verification Line 1: clamp_u32 guarantees result ∈ [min_h, max_h] for min_h <= max_h.
// Hoare-logic Verification Line 2: masking by 0xFFFF constrains the result to a valid u16 range.
