// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (tile_variant_selected)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: TileVariantSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select a tile variant index (0..4) from a weight value using
//! [`bcinr_logic::fix::bucketize_u32`]. Four buckets with boundaries at [64, 128, 192]
//! map weight values to variants 0, 1, 2, and 3.

use bcinr_logic::fix::{bucketize_u32, clamp_u32};

/// TileVariantSelected kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = N (reserved for biome context; unused).
/// - `input`: bits[0..8] = raw weight value (0..=255).
///
/// Returns: bits[0..8] = variant index (0..3).
#[inline]
#[must_use]
pub fn tile_variant_selected(state: u64, input: u64) -> u64 {
    let _ = state;
    let weight = (input & 0xFF) as u32;
    // Step size 64 partitions [0,255] into buckets 0,1,2,3 at boundaries 64,128,192.
    let bucket = bucketize_u32(weight, 64) / 64;
    clamp_u32(bucket, 0, 3) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn tile_variant_selected_reference(_state: u64, input: u64) -> u64 {
        let w = (input & 0xFF) as u32;
        if w < 64 {
            0
        } else if w < 128 {
            1
        } else if w < 192 {
            2
        } else {
            3
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !tile_variant_selected_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        tile_variant_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(tile_variant_selected_reference(s, i), tile_variant_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = tile_variant_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = tile_variant_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // weight=0 -> variant 0.
        assert_eq!(tile_variant_selected(0, 0), 0);
        // weight=64 -> variant 1 (first value in second bucket).
        assert_eq!(tile_variant_selected(0, 64), 1);
        // weight=255 -> variant 3 (last bucket).
        assert_eq!(tile_variant_selected(0, 255), 3);
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Low band: variant 0.
            (0, 10),
            // Second band lower edge: variant 1.
            (0, 64),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // Top band lower edge: must resolve to variant 2, not collapse low.
            (0, 192),
            // Saturated weight: must select the highest band, variant 3.
            (0, 255),
        ]
    }

    // Weakened: bucketize with the wrong step (128), collapsing the four bands
    // into two so the upper variants are never selected.
    fn weakened(s: u64, i: u64) -> u64 {
        let _ = s;
        let weight = (i & 0xFF) as u32;
        // BUG: step 128 yields only buckets 0 and 1, dropping variants 2 and 3.
        let bucket = bucketize_u32(weight, 128) / 128;
        clamp_u32(bucket, 0, 3) as u64
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                tile_variant_selected(s, i),
                tile_variant_selected_reference(s, i)
            );
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                tile_variant_selected(s, i),
                tile_variant_selected_reference(s, i)
            );
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != tile_variant_selected_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_tile_variant_selected(c: &mut Criterion) {
        c.bench_function("tile_variant_selected", |b| {
            b.iter(|| black_box(tile_variant_selected(black_box(0), black_box(100))))
        });
    }
}

// Hoare-logic Verification Line 1: bucketize_u32 with step=64 partitions [0,255] into 4 bands.
// Hoare-logic Verification Line 2: clamp_u32 ensures the result is bounded to [0, 3].
