// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (transition_legality_checked)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: TransitionLegalityChecked
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Authority: legality spec — a state transition is admissible iff the (from_state, symbol)
//! pair is a legal edge of the protocol DFA; edges that fall into the SINK state are
//! impossible/forbidden transitions (a state-desync cheat) and are refused. Lowered onto
//! [`bcinr_logic::dfa::dfa_advance`] with a flat transition table.

use bcinr_logic::dfa::dfa_advance;
use bcinr_logic::mask::eq_mask_u32;

/// States: 0..=3 are live protocol states, 4 = SINK (forbidden). Alphabet: symbols 0..=2.
const ALPHABET: usize = 3;
const SINK: usize = 4;
#[rustfmt::skip]
const TABLE: [usize; 15] = [
    // symbol:   0  1  2
    /* state 0 */ 1, 2, 4, // symbol 2 from state 0 is forbidden -> SINK
    /* state 1 */ 2, 3, 1,
    /* state 2 */ 3, 1, 2,
    /* state 3 */ 1, 2, 3,
    /* SINK   4 */ 4, 4, 4, // absorbing
];

/// TransitionLegalityChecked kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = from-state index (reduced into `[0, 5)`).
/// - `input`: bits[0..8] = transition symbol (reduced into `[0, 3)`).
///
/// Returns a verdict bitmask: `0` = ADMITTED (legal edge), nonzero = refusal.
/// - bit0 = illegal_transition (the edge lands on the SINK state).
#[inline]
#[must_use]
pub fn transition_legality_checked(state: u64, input: u64) -> u64 {
    let from = (state & 0xFF) as usize % 5;
    let sym = ((input & 0xFF) as u8) % 3;
    let next = dfa_advance(from, sym, &TABLE, ALPHABET);
    u64::from(eq_mask_u32(next as u32, SINK as u32)) & 1
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn transition_legality_checked_reference(state: u64, input: u64) -> u64 {
        let from = (state & 0xFF) as usize % 5;
        let sym = ((input & 0xFF) as usize) % 3;
        let next = TABLE[from * ALPHABET + sym];
        if next == SINK {
            1
        } else {
            0
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !transition_legality_checked_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        transition_legality_checked_reference(s, i) ^ 0xFFFF
    }

    // --- Two-sided breed battery: legality corpus + weakened detector ---
    fn must_admit() -> &'static [(u64, u64)] {
        // (from_state, symbol) pairs that land on a live state.
        &[
            (0, 0), // state 0 + sym 0 -> 1
            (1, 1), // state 1 + sym 1 -> 3
            (3, 2), // state 3 + sym 2 -> 3
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            (0, 2), // state 0 + sym 2 -> SINK (forbidden edge)
            (4, 0), // already in SINK -> stays SINK
            (4, 1), // SINK is absorbing for every symbol
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Deliberately broken: the SINK check is deleted, so forbidden transitions are
        // admitted as if they were legal edges.
        let _ = (s, i);
        0
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                transition_legality_checked_reference(s, i),
                transition_legality_checked(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = transition_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = transition_legality_checked_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(
            transition_legality_checked(0, 0),
            transition_legality_checked_reference(0, 0)
        );
        // Forbidden edge from a live state.
        assert_eq!(transition_legality_checked(0, 2), 1);
        // SINK is absorbing -> always illegal.
        assert_eq!(transition_legality_checked(4, 2), 1);
        // A legal advance.
        assert_eq!(transition_legality_checked(2, 0), 0);
    }

    #[test]
    fn two_sided_admit() {
        for &(s, i) in must_admit() {
            assert_eq!(
                transition_legality_checked(s, i),
                0,
                "legal case must be admitted"
            );
        }
    }
    #[test]
    fn two_sided_refuse() {
        for &(s, i) in must_refuse() {
            assert_ne!(
                transition_legality_checked(s, i),
                0,
                "cheat case must be refused"
            );
        }
    }
    #[test]
    fn weakened_fails_corpus() {
        assert!(
            must_refuse().iter().any(|&(s, i)| weakened(s, i) == 0),
            "a weakened detector must admit >=1 cheat from the corpus"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_transition_legality_checked(c: &mut Criterion) {
        c.bench_function("transition_legality_checked", |b| {
            b.iter(|| black_box(transition_legality_checked(black_box(1), black_box(1))))
        });
    }
}

// Hoare-logic Verification Line 1: verdict bit0 is set iff the DFA edge resolves to the SINK state.
// Hoare-logic Verification Line 2: the SINK state is absorbing, so it refuses every subsequent symbol.
