// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (volume_clamped)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: VolumeClamped
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Apply a volume change (delta) to current volume, clamping to [0, 255].

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::mask::select_u32;

/// VolumeClamped kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current volume (0..255).
/// - `input`: bits[0..8] = delta magnitude, bit[8] = direction (0=up, 1=down).
///
/// Returns bits[0..8] = new clamped volume.
#[inline]
#[must_use]
pub fn volume_clamped(state: u64, input: u64) -> u64 {
    let vol = (state & 0xFF) as u32;
    let delta = (input & 0xFF) as u32;
    let dir = ((input >> 8) & 1) as u32;
    let up_result = clamp_u32(vol.saturating_add(delta), 0, 255);
    let down_result = clamp_u32(vol.saturating_sub(delta), 0, 255);
    let dir_mask = 0u32.wrapping_sub(dir); // 0xFFFFFFFF if dir=1 (down)
    let result = select_u32(dir_mask, down_result, up_result);
    (result as u64) & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn volume_clamped_reference(state: u64, input: u64) -> u64 {
        let vol = (state & 0xFF) as u32;
        let delta = (input & 0xFF) as u32;
        let dir = ((input >> 8) & 1) as u32;
        if dir == 1 {
            (vol.saturating_sub(delta).min(255)) as u64
        } else {
            ((vol + delta).min(255)) as u64
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !volume_clamped_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        volume_clamped_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(volume_clamped_reference(s, i), volume_clamped(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = volume_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = volume_clamped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // vol=100/delta=20/dir=0 -> 120
        assert_eq!(volume_clamped(100, 20), volume_clamped_reference(100, 20));
        // vol=100/delta=20/dir=1 -> 80
        assert_eq!(
            volume_clamped(100, 20 | (1 << 8)),
            volume_clamped_reference(100, 20 | (1 << 8))
        );
        // vol=10/delta=30/dir=1 -> 0 (floor)
        assert_eq!(
            volume_clamped(10, 30 | (1 << 8)),
            volume_clamped_reference(10, 30 | (1 << 8))
        );
    }

    // Two-sided breed-rigor battery.
    fn must_admit() -> &'static [(u64, u64)] {
        // In-domain: vol +/- delta stays inside [0, 255], clamp does not fire.
        &[
            (100, 20),            // up 100+20 -> 120
            (100, 20 | (1 << 8)), // down 100-20 -> 80
        ]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // Out-of-domain: delta overflows/underflows the [0, 255] window, clamp fires.
        &[
            (200, 100),          // up 300 -> clamp 255
            (10, 30 | (1 << 8)), // down -20 -> clamp 0
        ]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken variant: omits the [0, 255] clamp (raw wrapping arithmetic).
        let vol = (s & 0xFF) as u32;
        let delta = (i & 0xFF) as u32;
        let dir = ((i >> 8) & 1) as u32;
        let result = if dir == 1 {
            vol.wrapping_sub(delta)
        } else {
            vol.wrapping_add(delta)
        };
        (result as u64) & 0xFFFF
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(volume_clamped(s, i), volume_clamped_reference(s, i));
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(volume_clamped(s, i), volume_clamped_reference(s, i));
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != volume_clamped_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 100;
    const I: u64 = 20;
    pub fn bench_volume_clamped(c: &mut Criterion) {
        c.bench_function("volume_clamped", |b| {
            b.iter(|| black_box(volume_clamped(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: dir_mask selects down_result when dir=1, up_result when dir=0, branchlessly via wrapping_sub.
// Hoare-logic Verification Line 2: clamp_u32 ensures result stays in [0, 255] for both directions regardless of delta magnitude.
