// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (waypoint_reached)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: WaypointReached
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Check if remaining distance to a waypoint is within tolerance and compute saturating remainder.

use bcinr_logic::int::saturating_sub_i64;
use bcinr_logic::mask::lt_mask_u32;

/// WaypointReached kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = current distance (u32, fixed-point units)
/// - `input`: bits[0..32] = tolerance threshold
///
/// Returns bits[0..8] = 1 if reached (dist <= tol), 0 otherwise; bits[8..40] = saturating remaining = max(dist - tol, 0).
#[inline]
#[must_use]
pub fn waypoint_reached(state: u64, input: u64) -> u64 {
    let dist = (state & 0xFFFF_FFFF) as u32;
    let tol = (input & 0xFFFF_FFFF) as u32;
    // reached = 1 when dist <= tol, i.e. NOT (tol < dist)
    let tol_lt_dist = lt_mask_u32(tol, dist);
    let reached = ((!tol_lt_dist) & 1) as u64;
    // remaining = max(dist - tol, 0) via saturating sub on i64
    let remaining = saturating_sub_i64(dist as i64, tol as i64).max(0_i64) as u64 & 0xFFFF_FFFF;
    reached | (remaining << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn waypoint_reached_reference(state: u64, input: u64) -> u64 {
        let dist = (state & 0xFFFF_FFFF) as u32;
        let tol = (input & 0xFFFF_FFFF) as u32;
        let reached: u64 = if dist <= tol { 1 } else { 0 };
        let remaining: u64 = if dist > tol { (dist - tol) as u64 } else { 0 };
        reached | (remaining << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !waypoint_reached_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        waypoint_reached_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test] fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(waypoint_reached_reference(s, i), waypoint_reached(s, i));
        }
        #[test] fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = waypoint_reached_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test] fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = waypoint_reached_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // dist=0/tol=5 -> reached=1, remaining=0
        assert_eq!(waypoint_reached(0, 5), waypoint_reached_reference(0, 5));
        // dist=100/tol=5 -> reached=0, remaining=95
        assert_eq!(waypoint_reached(100, 5), waypoint_reached_reference(100, 5));
        // dist=5/tol=5 -> reached=1, remaining=0
        assert_eq!(waypoint_reached(5, 5), waypoint_reached_reference(5, 5));
    }

    // --- two-sided breed-rigor battery ---

    fn must_admit() -> &'static [(u64, u64)] {
        &[
            // Within tolerance: reached, remaining 0.
            (5, 5),
            // Beyond tolerance: not reached, positive remaining.
            (100, 5),
        ]
    }

    fn must_refuse() -> &'static [(u64, u64)] {
        &[
            // dist far below tol: remainder must FLOOR to 0, not underflow-wrap.
            (0, 5),
            // dist well under a large tol: floor still pins remaining to 0.
            (3, 1000),
        ]
    }

    // Weakened: raw dist - tol with no saturating floor, so under-tolerance
    // distances wrap to a huge remainder instead of clamping to 0.
    fn weakened(s: u64, i: u64) -> u64 {
        let dist = (s & 0xFFFF_FFFF) as u32;
        let tol = (i & 0xFFFF_FFFF) as u32;
        let tol_lt_dist = lt_mask_u32(tol, dist);
        let reached = ((!tol_lt_dist) & 1) as u64;
        // BUG: no .max(0) floor — i64 difference can go negative and wrap.
        let remaining = (dist as i64 - tol as i64) as u64 & 0xFFFF_FFFF;
        reached | (remaining << 8)
    }

    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(waypoint_reached(s, i), waypoint_reached_reference(s, i));
        }
    }

    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(waypoint_reached(s, i), waypoint_reached_reference(s, i));
        }
    }

    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != waypoint_reached_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_waypoint_reached(c: &mut Criterion) {
        c.bench_function("waypoint_reached", |b| {
            b.iter(|| black_box(waypoint_reached(black_box(100), black_box(5))))
        });
    }
}

// Hoare-logic Verification Line 1: reached flag = NOT lt_mask(tol, dist) & 1, true iff dist <= tol — branchless.
// Hoare-logic Verification Line 2: remaining saturates at 0 when dist <= tol via saturating_sub_i64.max(0).
