// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (xp_threshold_crossed)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: XpThresholdCrossed
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Check whether accumulated XP crosses a level-up threshold and compute overflow XP using
//! branchless [`bcinr_logic::mask::lt_mask_u32`] and [`bcinr_logic::mask::select_u32`].

use bcinr_logic::mask::{lt_mask_u32, select_u32};

/// XpThresholdCrossed kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = current XP (u32).
/// - `input`: bits[0..32] = XP threshold for next level.
///
/// Returns: bits[0..8] = crossed flag (1 if xp >= threshold, 0 otherwise),
/// bits[8..40] = overflow XP (xp - threshold, 0 if not crossed).
#[inline]
#[must_use]
pub fn xp_threshold_crossed(state: u64, input: u64) -> u64 {
    let xp = (state & 0xFFFF_FFFF) as u32;
    let threshold = (input & 0xFFFF_FFFF) as u32;
    // not_lt is 0xFFFF_FFFF when xp >= threshold, 0 when xp < threshold.
    let not_lt = !lt_mask_u32(xp, threshold);
    let crossed = (not_lt >> 31) as u64;
    let overflow = xp.saturating_sub(threshold);
    // Zero the overflow when not crossed.
    let overflow_val = select_u32(not_lt, overflow, 0);
    crossed | ((overflow_val as u64) << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn xp_threshold_crossed_reference(state: u64, input: u64) -> u64 {
        let xp = (state & 0xFFFF_FFFF) as u32;
        let threshold = (input & 0xFFFF_FFFF) as u32;
        if xp >= threshold {
            1u64 | (((xp - threshold) as u64) << 8)
        } else {
            0u64
        }
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !xp_threshold_crossed_reference(s, i)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        xp_threshold_crossed_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(xp_threshold_crossed_reference(s, i), xp_threshold_crossed(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = xp_threshold_crossed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = xp_threshold_crossed_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // xp=100, threshold=50 -> crossed=1, overflow=50.
        let out = xp_threshold_crossed(100, 50);
        assert_eq!(out & 0xFF, 1);
        assert_eq!((out >> 8) & 0xFFFF_FFFF, 50);
        // xp=30, threshold=50 -> crossed=0, overflow=0.
        let out2 = xp_threshold_crossed(30, 50);
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFFFF_FFFF, 0);
        // xp=50, threshold=50 -> crossed=1, overflow=0.
        let out3 = xp_threshold_crossed(50, 50);
        assert_eq!(out3 & 0xFF, 1);
        assert_eq!((out3 >> 8) & 0xFFFF_FFFF, 0);
    }

    fn must_admit() -> &'static [(u64, u64)] {
        // Threshold crossed: flag set, overflow reported.
        &[(100, 50), (50, 50)]
    }
    fn must_refuse() -> &'static [(u64, u64)] {
        // xp < threshold: the guard must zero both flag and overflow.
        &[(30, 50), (0, 1)]
    }
    fn weakened(s: u64, i: u64) -> u64 {
        // Broken: always reports crossed, dropping the xp >= threshold guard.
        let xp = (s & 0xFFFF_FFFF) as u32;
        let threshold = (i & 0xFFFF_FFFF) as u32;
        let overflow = xp.saturating_sub(threshold) as u64;
        1u64 | (overflow << 8)
    }
    #[test]
    fn corpus_admit_matches_oracle() {
        for &(s, i) in must_admit() {
            assert_eq!(
                xp_threshold_crossed(s, i),
                xp_threshold_crossed_reference(s, i)
            );
        }
    }
    #[test]
    fn corpus_refuse_matches_oracle() {
        for &(s, i) in must_refuse() {
            assert_eq!(
                xp_threshold_crossed(s, i),
                xp_threshold_crossed_reference(s, i)
            );
        }
    }
    #[test]
    fn weakened_fails_refuse_corpus() {
        assert!(
            must_refuse()
                .iter()
                .any(|&(s, i)| weakened(s, i) != xp_threshold_crossed_reference(s, i)),
            "a weakened impl must diverge from the oracle on >=1 refuse case"
        );
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};

    const STATE: u64 = 100;
    const INPUT: u64 = 50;

    pub fn bench_xp_threshold_crossed(c: &mut Criterion) {
        c.bench_function("xp_threshold_crossed", |b| {
            b.iter(|| black_box(xp_threshold_crossed(black_box(STATE), black_box(INPUT))))
        });
    }
}

// Hoare-logic Verification Line 1: crossed flag is 1 iff xp >= threshold (complement of lt_mask).
// Hoare-logic Verification Line 2: overflow is zero-masked when the threshold is not crossed.
