// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl (anticheat_verdict)
// Regenerate: `ggen sync`. JTBD: Anti-cheat verdict: movement law, resource bound,
//   cooldown, action rate, transition law, entity kill, OCEL link, receipt seal.

#[cfg(test)]
mod anticheat_verdict_chain {
    use crate::patterns::*;

    fn run_chain() -> u64 {
        // Step 1: Movement law: cur=100, proposed=104, max_speed=5 → delta=4 ≤ 5 ADMITTED.
        let step1 = movement_legality_checked(100u64, 104u64 | (5u64 << 16));
        // Step 2: Resource bound: hp=500 ≤ cap=1000 → ADMITTED (no overflow).
        let step2 = resource_bound_checked(500u64, 1000u64);
        // Step 3: Cooldown: remaining=10 (positive) → ADMITTED (not fast-fire).
        let step3 = cooldown_legality_checked(10u64, 0u64);
        // Step 4: Action rate: actions=3 ≤ budget=5 → within rate limit.
        let step4 = action_rate_bounded(3u64, 5u64);
        // Step 5: Transition legality DFA: from_state=0, symbol=1 → legal transition.
        let step5 = transition_legality_checked(0u64, 1u64);
        // Step 6: Entity DFA: Active(1) + kill(3) → Dead(3).
        let step6 = entity_state_transitioned(1u64, 3u64);
        // Step 7: Link OCEL verdict event: gate=7, proposed=5.
        let step7 = ocel_event_linked(0x7u64, 0x5u64);
        // Step 8: Seal transition verdict (step5) into FNV-1a receipt chain.
        let step8 = receipt_appended(0xcbf29ce484222325_u64, step5);
        [step1, step2, step3, step4, step5, step6, step7, step8]
            .iter()
            .fold(0xcbf29ce484222325_u64, |h, &r| {
                (h ^ r).wrapping_mul(0x100000001b3_u64)
            })
    }

    #[test]
    fn chain_deterministic() {
        assert_eq!(run_chain(), run_chain(), "JTBD chain must be deterministic");
    }
}
