// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl (audio_cascade)
// Regenerate: `ggen sync`. JTBD: Audio cascade: trigger FSM, priority select, volume clamp, fade, distance atten, tick advance, OTEL span, receipt seal.

#[cfg(test)]
mod audio_cascade_chain {
    use crate::patterns::*;

    fn run_chain() -> u64 {
        // Step 1: Audio FSM: STOPPED(0) + PLAY(0) → PLAYING(1).
        let step1 = audio_trigger_evaluated(0u64, 0u64);
        // Step 2: Priority select: ch0 p=80 id=0 vs ch1 p=75 id=1 → ch0 wins (p0>p1).
        let step2 = audio_priority_selected(80u64 | (0u64 << 8), 75u64 | (1u64 << 8));
        // Step 3: Volume clamp: vol=200, delta=20 up → 220 (≤255).
        let step3 = volume_clamped(200u64, 20u64);
        // Step 4: Fade: vol=220, rate=30 → max(220-30,0)=190.
        let step4 = audio_fade_applied(220u64, 30u64);
        // Step 5: Distance atten: max_vol=220, atten=4, dist=5 → 220-4*5=200.
        let step5 = audio_distance_attenuated(220u64 | (4u64 << 8), 5u64);
        // Step 6: Tick advance: acc=500, elapsed=16, step=16 → bucketize(516,16)=32.
        let step6 = fixed_tick_advanced(500u64, 16u64 | (16u64 << 32));
        // Step 7: Emit OTEL span code for slot 2.
        let step7 = otel_span_emitted(0u64, 2u64);
        // Step 8: Seal faded volume result (step4=190) into FNV-1a receipt chain.
        let step8 = receipt_appended(0xcbf29ce484222325_u64, step4);
        // Fold all step outputs into a single FNV-1a hash so any change in any kernel
        // output is immediately visible as a test failure.
        [step1, step2, step3, step4, step5, step6, step7, step8]
            .iter()
            .fold(0xcbf29ce484222325_u64, |h, &r| {
                (h ^ r).wrapping_mul(0x100000001b3_u64)
            })
    }

    /// Chain must produce the same result on every call (no hidden mutable state).
    #[test]
    fn chain_deterministic() {
        assert_eq!(run_chain(), run_chain(), "JTBD chain must be deterministic");
    }

    /// Pin test: asserts a known-good hash so silent kernel regressions are caught.
    ///
    /// The committed chain file replaces `EXPECTED_HASH` with the real value.
    /// A sentinel of `u64::MAX` signals "not yet pinned" and always fails loudly.
    #[test]
    fn chain_hash_is_stable() {
        // REPLACE_EXPECTED_HASH: fill in the value printed by `cargo test -- --nocapture`.
        const EXPECTED_HASH: u64 = u64::MAX; // sentinel — must be replaced in committed chain
        assert_ne!(
            EXPECTED_HASH,
            u64::MAX,
            "chain_hash_is_stable: EXPECTED_HASH is still the sentinel — \
             run the test with --nocapture to obtain the real hash and pin it"
        );
        assert_eq!(
            run_chain(),
            EXPECTED_HASH,
            "chain output hash changed — re-pin or investigate"
        );
    }
}
