// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl
// Regenerate: `ggen sync`. Declares the 8 JTBD chain test modules.
// COVERAGE: complements corpus.rs (all 75 kernels) with integration paths —
// corpus.rs is the portability oracle (frozen digest), chain tests are the
// composition oracle (non-determinism + cross-kernel data-flow correctness).

mod anticheat_verdict;
mod audio_cascade;
mod combat_hit;
mod mp_resync;
mod nav_quest;
mod procgen_tile;
mod quality_loop;
mod shop_purchase;
