// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl (nav_quest)
// Regenerate: `ggen sync`. JTBD: Nav-quest pipeline: nav DFA, A* node expansion, waypoint, cost bound, quest step, AI selection, OCEL link, receipt seal.

#[cfg(test)]
mod nav_quest_chain {
    use crate::patterns::*;

    fn run_chain() -> u64 {
        // Step 1: Advance nav DFA: IDLE(0) + MOVE(1) → MOVING(1).
        let step1 = nav_state_advanced(0u64, 1u64);
        // Step 2: A* expand: candidate cost=150 < current=200, select candidate node id=2.
        let step2 = path_node_expanded(200u64 | (1u64 << 32), 150u64 | (2u64 << 32));
        // Step 3: Waypoint check: dist=5 ≤ tol=10 → REACHED.
        let step3 = waypoint_reached(5u64, 10u64);
        // Step 4: Path cost check: acc=800 ≤ budget=1000 → within budget, over_flag=0.
        let step4 = path_cost_bounded(800u64, 1000u64);
        // Step 5: Quest DFA: step0 + complete(1) → step1.
        let step5 = quest_step_advanced(0u64, 1u64);
        // Step 6: AI argmax: util=[100,200,50,75] → action 1 (highest utility=200).
        let step6 = ai_action_selected(
            0u64,
            100u64 | (200u64 << 16) | (50u64 << 32) | (75u64 << 48),
        );
        // Step 7: Link OCEL event: gate=0xF, proposed=0x5 → admitted.
        let step7 = ocel_event_linked(0xFu64, 0x5u64);
        // Step 8: Seal quest step result (step5=1) into FNV-1a receipt chain.
        let step8 = receipt_appended(0xcbf29ce484222325_u64, step5);
        // Fold all step outputs into a single FNV-1a hash so any change in any kernel
        // output is immediately visible as a test failure.
        [step1, step2, step3, step4, step5, step6, step7, step8]
            .iter()
            .fold(0xcbf29ce484222325_u64, |h, &r| {
                (h ^ r).wrapping_mul(0x100000001b3_u64)
            })
    }

    /// Chain must produce the same result on every call (no hidden mutable state).
    #[test]
    fn chain_deterministic() {
        assert_eq!(run_chain(), run_chain(), "JTBD chain must be deterministic");
    }

    /// Pin test: asserts a known-good hash so silent kernel regressions are caught.
    ///
    /// The committed chain file replaces `EXPECTED_HASH` with the real value.
    /// A sentinel of `u64::MAX` signals "not yet pinned" and always fails loudly.
    #[test]
    fn chain_hash_is_stable() {
        // REPLACE_EXPECTED_HASH: fill in the value printed by `cargo test -- --nocapture`.
        const EXPECTED_HASH: u64 = u64::MAX; // sentinel — must be replaced in committed chain
        assert_ne!(
            EXPECTED_HASH,
            u64::MAX,
            "chain_hash_is_stable: EXPECTED_HASH is still the sentinel — \
             run the test with --nocapture to obtain the real hash and pin it"
        );
        assert_eq!(
            run_chain(),
            EXPECTED_HASH,
            "chain output hash changed — re-pin or investigate"
        );
    }
}
