// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl (procgen_tile)
// Regenerate: `ggen sync`. JTBD: Procgen tile: noise sample, terrain height,
//   biome class, tile variant, spawn weight, physics render, object spawn, receipt seal.

#[cfg(test)]
mod procgen_tile_chain {
    use crate::patterns::*;

    fn run_chain() -> u64 {
        // Step 1: Hash-noise: seed=12345, x=42, y=17 → noise byte [0,255].
        let step1 = noise_value_sampled(12345u64, 42u64 | (17u64 << 16));
        // Step 2: Quantize noise (step1) into height buckets of size 10, max 200.
        let step2 = terrain_height_quantized(step1, 10u64 | (200u64 << 16));
        // Step 3: Biome class: flags=0b00010110 (forest+lake bits), selector=1.
        let step3 = biome_class_selected(0b0001_0110u64, 1u64);
        // Step 4: Tile variant: use noise value (step1) as weight for variant selection.
        let step4 = tile_variant_selected(step1, 0u64);
        // Step 5: Spawn weight: noise roll (step1) vs spawn rate threshold=180.
        let step5 = spawn_weight_evaluated(step1, 180u64);
        // Step 6: Physics render: value=1200, clamp to [0, 1000] → 1000.
        let step6 = physics_value_rendered(1200u64, 1000u64 << 16);
        // Step 7: Spawn object: type=1, variant=2.
        let step7 = object_spawned(1u64, 2u64);
        // Step 8: Seal spawn event (step7) into FNV-1a receipt chain.
        let step8 = receipt_appended(0xcbf29ce484222325_u64, step7);
        [step1, step2, step3, step4, step5, step6, step7, step8]
            .iter()
            .fold(0xcbf29ce484222325_u64, |h, &r| {
                (h ^ r).wrapping_mul(0x100000001b3_u64)
            })
    }

    #[test]
    fn chain_deterministic() {
        assert_eq!(run_chain(), run_chain(), "JTBD chain must be deterministic");
    }
}
