// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl (quality_loop)
// Regenerate: `ggen sync`. JTBD: Quality loop: CTQ threshold, sigma level, defect rate, quality gate DFA, bridge state, command opcode, adapter rank, capability flag.

#[cfg(test)]
mod quality_loop_chain {
    use crate::patterns::*;

    fn run_chain() -> u64 {
        // Step 1: CTQ check: value=50 within [LSL=30, USL=80] → ADMITTED.
        let step1 = ctq_threshold_evaluated(50u64, 30u64 | (80u64 << 16));
        // Step 2: Sigma level: DPMO=1500 → approximately 4.5 sigma (LUT bucket).
        let step2 = sigma_level_computed(1500u64, 0u64);
        // Step 3: Defect rate: 15 defects / 1000 samples → quantized bucket.
        let step3 = defect_rate_quantized(15u64, 1000u64);
        // Step 4: Quality gate DFA: state=0, symbol=1 → next gate state.
        let step4 = quality_gate_evaluated(0u64, 1u64);
        // Step 5: Bridge DFA: from_state=0, symbol=1 → bridge next state.
        let step5 = bridge_state_transitioned(0u64, 1u64);
        // Step 6: Command opcode: cmd=45 → count how many of {32,64,96} it exceeds = 1.
        let step6 = command_opcode_encoded(45u64, 0u64);
        // Step 7: Adapter rank: priorities=[300,200,400,100] → sort descending via bitonic network.
        let step7 = adapter_priority_ranked(
            300u64 | (200u64 << 16) | (400u64 << 32) | (100u64 << 48),
            0u64,
        );
        // Step 8: Capability flag: flags=0xAA, check bit idx=3 → bit 3 of 0b10101010 = 1.
        let step8 = capability_flag_evaluated(0b1010_1010u64, 3u64);
        // Fold all step outputs into a single FNV-1a hash so any change in any kernel
        // output is immediately visible as a test failure.
        [step1, step2, step3, step4, step5, step6, step7, step8]
            .iter()
            .fold(0xcbf29ce484222325_u64, |h, &r| {
                (h ^ r).wrapping_mul(0x100000001b3_u64)
            })
    }

    /// Chain must produce the same result on every call (no hidden mutable state).
    #[test]
    fn chain_deterministic() {
        assert_eq!(run_chain(), run_chain(), "JTBD chain must be deterministic");
    }

    /// Pin test: asserts a known-good hash so silent kernel regressions are caught.
    ///
    /// The committed chain file replaces `EXPECTED_HASH` with the real value.
    /// A sentinel of `u64::MAX` signals "not yet pinned" and always fails loudly.
    #[test]
    fn chain_hash_is_stable() {
        // REPLACE_EXPECTED_HASH: fill in the value printed by `cargo test -- --nocapture`.
        const EXPECTED_HASH: u64 = u64::MAX; // sentinel — must be replaced in committed chain
        assert_ne!(
            EXPECTED_HASH,
            u64::MAX,
            "chain_hash_is_stable: EXPECTED_HASH is still the sentinel — \
             run the test with --nocapture to obtain the real hash and pin it"
        );
        assert_eq!(
            run_chain(),
            EXPECTED_HASH,
            "chain output hash changed — re-pin or investigate"
        );
    }
}
